### ISSUE TITLE
PFH features pcl::computePairFeatures --> order of points/normals in arg list  matters in some cases

### ISSUE THREAD

**Issue by strothmw** [PointCloudLibrary/pcl#1187]
Looking at 

https://github.com/PointCloudLibrary/pcl/blob/master/features/src/pfh.cpp#L65 

I assume it is intended that the order p1 and p2 may not influence the returned features, i. e. calling pcl::computePairFeatures with points/normals in order p1 p2 may return the same feature values as calling with order p2 p1.

However, in the current implementaion this behaviour is not assured! It is such in most of the cases. But angle1 and angle2 at https://github.com/PointCloudLibrary/pcl/blob/master/features/src/pfh.cpp#L67 can have identical values, and if the order of p1 and p2 changes the the will still have identical values but with opposite sign, i. e. the returned features wo'nt be identical it this case for different orders of p1 and p2!

**Comment by mvieth** [comment]
It is almost impossible in practice that two floats (angle1 and angle2) have the exact same value, considering that the normals are usually estimated from noisy data. So while this might be theoretically possible, it is okay to accept this very unlikely problem. Correct me if I am wrong, but I don't think it will make the classes/functions that use `computePairFeatures` fail. And I don't even have any idea how to distinguish between the two points if the angles _were_  exactly the same.
Since this is pretty old and nobody seemed to have this problem in the meantime, I will close this issue, but feel free to comment here/open a new issue if this is still a problem.
