### ISSUE TITLE
build failure. pcl_io has an unchecked python dependency

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#1349]
Cloned trunk as-is (06e467ad8a27dfca7e41b83d5d1c3bd76aa5812d). Tested on an up-to-date Ubuntu 14.04 LTS, a fresh VM. Installed the following libraries through aptitude:
- libeigen3-dev
- libflann-dev  (1.8)
- libvtk6-dev
- libboost-system-dev  (1.55) 
- libboost-thread-dev  (1.55)
- libboost-filesystem-dev  (1.55) 
- libboost-date-time-dev  (1.55)
- libboost-iostreams-dev  (1.55)

No additional options were passed to cmake. The build is failing because it doesn't find python. This should have error'ed out during the configuration stage.

```
[ 26%] Building CXX object io/CMakeFiles/pcl_io.dir/src/libpng_wrapper.cpp.o
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libpython2.7.so', needed by `lib/libpcl_io.so.1.8.0'.  Stop.
make[1]: *** [io/CMakeFiles/pcl_io.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by tom-maier** [comment]
Hello,

run into the same problem today on a Ubuntu 14.04 based fresh install. 

Apparently the makefile refers to */usr/lib/x86_64-linux-gnu/libpython2.7.so* but on Ubuntu the lib seems to be named */usr/lib/x86_64-linux-gnu/libpython2.7.so.1* ...

A quick and dirty `sudo ln /usr/lib/x86_64-linux-gnu/libpython2.7.so.1 /usr/lib/x86_64-linux-gnu/libpython2.7.so` allows you to build pcl on your system. 

Tom

**Comment by jspricke** [comment]
This is a bug in the VTK package and has been fixed in [1]. So either install a more recent VTK package (6.0.0-7 should be fine), or install `libpython-dev` yourself (doing `sudo ln` sounds like a bad idea). Also, would be great if you could fill this as a bug at Ubuntu.

[1] https://anonscm.debian.org/cgit/debian-science/packages/vtk6.git/commit/debian/control?id=9796292755d0fd94789ba1798762325ab9b839a0

**Comment by SergioRAgostinho** [comment]
Wilco. Thanks
