### ISSUE TITLE
VoxelGridOcclusionEstimation: Methods 'int occlusionEstimation(...)' do not return the occlusion state

### ISSUE THREAD

**Issue by maxgabler** [PointCloudLibrary/pcl#1437]
The documentation states, that the methods
- int VoxelGridOcclusionEstimation::occlusionEstimation(int&, Eigen::Vector3i) and
- int VoxelGridOcclusionEstimation::occlusionEstimation(int&, vector<Eigen::Vector3i>, Eigen::Vector3i)

return the occlusion state of the given voxel. As they do as expected via the first int argument, they don't via their return value, which is always '0'. 
How should the return value of those methods be interpreted? Something like an exit code?
The documentation is misleading as it uses the \return keyword, which I think refers to a methods return value, in a wrong way...

**Comment by VictorLamoine** [comment]
The documentation is not only mis-leading, it is false; the functions never returns 1 as the [documentation states](http://docs.pointclouds.org/trunk/classpcl_1_1_voxel_grid_occlusion_estimation.html#ab9caaf4a51888c55c4aecba30fd55695). See [voxel_grid_occlusion_estimation.hpp#L69-L129](https://github.com/PointCloudLibrary/pcl/blob/a654fe4188382416c99322cafbd9319c59a7355c/filters/include/pcl/filters/impl/voxel_grid_occlusion_estimation.hpp#L69-L129).

These methods returns `0` if everything went fine, `-1` otherwise.

But those methods clearly modifies the input, that's why the parameters are marked `[out]` in the doxygen documentation.

The doc needs to be fixed.
