### ISSUE TITLE
Depth sense SDK color lost when NaN depth

### ISSUE THREAD

**Issue by VictorLamoine** [PointCloudLibrary/pcl#1464]
When capturing data using the Depth Sense SDK, points registered with NaN coordinates seems to throw up color information from the RGB camera.

Reported on [StackOverflow]( http://stackoverflow.com/questions/33727575/point-cloud-library-1-8-depthsense-grabber-does-not-seem-to-provide-rgb-data-f).

**Comment by taketwo** [comment]
The `DepthSense` grabber receives two streams from the driver: depth and color. They are merged into a single point cloud with colors, which is then returned to the end user. Due to the fact that the two sensors involved (IR and color camera) have a certain displacement and different resolutions (QVGA and VGA respectively), the mapping between depth and color pixels in the streams is not trivial. In fact, for each depth/color frame the camera driver additionally produces so-called UV-map, which can be used to establish correspondences. Unfortunately, it fails to set UV-coordinates for invalid depth pixels, which makes it impossible to find corresponding RGB values for the NaN points.

Closing as this is not a bug and can not be fixed.
