### ISSUE TITLE
kd_flann compilation issue when using PCL with OpenCV

### ISSUE THREAD

**Issue by Mariusmssj** [PointCloudLibrary/pcl#1481]
There seems to be an issue in the RaspbianOS Jessie when using PCL and OpenCV. If libpcl-dev and libopencv-dev are installed using apt-get install the flann library has issues and will not allow project to compile causing the:
"error: field 'param_k_' has incomplete type" and "error: field 'param_radius_ 'has incomplete type" errors.

I fixed this by completely removing openCV by "sudo apt-get purge libopencv-dev" then "sudo apt-get autoremove" but that still does not remove the opencv_flann lib files those need to be removed manually from file system directories.

To get things to work again I needed to compile Opencv from source and exclude the flann from compilation. I can see this issue has happened before : https://github.com/PointCloudLibrary/pcl/issues/483 and I assume other users might have this as well

**Comment by Sun-ch122** [comment]
try this. I am using 1.8
and I modify these two files
because of the forward declaration,we can only declare a pointer
::flann::SearchParams *param_k_;
instead of a instance
::flann::SearchParams param_k_;

cited by https://github.com/strands-project/strands_3d_mapping/issues/67#issuecomment-271258586

**Comment by kunaltyagi** [comment]
Is this fixed in PCL HEAD? If not, would you mind creating a PR?

**Comment by kunaltyagi** [comment]
Closing due to lack of response

**Comment by nhewitt99** [comment]
I've just faced the same issue and the same fix worked for me. Ubuntu 18.04.4 LTS, with OpenCV 3.4 and PCL 1.8 both installed from apt. I'd be happy to make a PR if the issue can be reopened.

I'm confused why this issue is only present in a select few cases though, and isn't causing problems for everyone who includes normal_3d.h, feature.h, etc (any of the files that end up including kdtree_flann.h). Maybe it's more likely that this is due to our own configurations / user error, and isn't fit to be pushed to head?

**Comment by kunaltyagi** [comment]
A PR is welcome. I tried to create an MCVE, but couldn't.
