### ISSUE TITLE
Missing PointXYZRGBANormal point type

### ISSUE THREAD

**Issue by andreaskoepf** [PointCloudLibrary/pcl#1483]
It is currently not possible to use the concatenateFields() function to combine a  `PointXYZRGBA` cloud with a `pcl::Normal` cloud into a `PointXYZRGBNormal` cloud. 

```
pcl::PointCloud<pcl::PointXYZRGBA> poscolor;
pcl::PointCloud<pcl::Normal> normals;
pcl::PointCloud<pcl::PointXYZRGBNormal> full;
pcl::concatenateFields(poscolor, normals, full);
```

Here are the two probably relevant lines of the error- avalanche generated by gcc:
```
/usr/local/include/pcl-1.8/pcl/point_traits.h:170:7: error: no matching function for call to ‘assertion_failed(mpl_::failed************ (pcl::traits::datatype<pcl::_PointXYZRGBNormal, pcl::fields::rgba>::POINT_TYPE_NOT_PROPERLY_REGISTERED::************)(pcl::_PointXYZRGBNormal&))’
/usr/local/include/pcl-1.8/pcl/common/concatenate.h:81:7: error: ‘assert_arg’ is not a member of ‘mpl_assert_arg83 {aka pcl::NdConcatenateFunctor<PointInT, PointOutT>::operator()() [with Key = pcl::fields::rgba; PointInT = pcl::PointXYZRGBA; PointOutT = pcl::PointXYZRGBNormal]::POINT_IN_AND_POINT_OUT_HAVE_DIFFERENT_TYPES_FOR_FIELD83}’
```

I wonder whether this is this by-design and nobody else needs this? The effective memory layout (e.g. struct members) of `PointXYZRGBA` und `PointXYZRGB` are the same and normal copy operations e.g. `pcl::copyPointCloud` can copy between those two formats without problems but the point-type registration differs slightly.

For my torch/lua [pcl wrapper](https://github.com/xamla/torch-pcl) I ended now up defining my own `PointXYZRGBANormal` point type with a `uint32_t rgba` enty for `POINT_CLOUD_REGISTER_POINT_STRUCT()`. As the state of `PointXYZRGB` is probably somewhat 'deprecated' I think an official PointXYZRGBANormal is missing in the pcl.

**Comment by taketwo** [comment]
Yes, the effective memory layout or `RGB` and `RGBA` fields is the same. But they have different tags and types, therefore various meta-programming functions treat them as different types. It's still possible to associate them with a fair amount of meta-programming magic (e.g. see how [copyPoint()](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/impl/copy_point.hpp) works). In principle, `NdConcatenateFunctor` can be modified to handle `rgb` <-> `rgba` association, however it would require a really serious time investment.

This whole `RGB` vs. `RGBA` thing is ugly, but there is not much we can do now. It's definitely something to get rid of in PCL 2.0 (if it ever happens). Adding new `PointXYZRGBANormal` is possible, but it would increase compilation time and library size even further (because we precompile for all types).

Depending on your situation, I'd suggest to either switch to `PointXYZRGB` clouds completely or, if time is not critical, copy from a `PointXYZRGBA` cloud to `PointXYZRGB` cloud before concatenation.

**Comment by andreaskoepf** [comment]
Unfortunately as long as `pcl::io::OpenNI2Grabber` spits out tons of warnings complaining about using a deprecated PointXYZRGB callback I think I do not want to use PointXYZRGB (that is what I was doing before). My goal of [torch-pcl](https://github.com/xamla/torch-pcl) is to cover at some point in 2016 most relevant functionality of the pcl instantly. Currently it takes <0.2 seconds and provides basic functionality for 6 types (XYZ, XYZI, XYZRGBA, + Normals): e.g. IO, Filters, CloudViewer, OpenNI2Grabber, PCA, (Incremental)ICP, Octree, KdTree, MeshSampling. I hope to fully offer the functionality required for in-handscanner in the next two weeks.

For now I decided to go the real hard way and explicitly instantiate every class/function that I use for my custom PointXYZRGBANormal type ([xyzrgbanormal.h](https://github.com/Xamla/torch-pcl/blob/dev/src/xyzrgbanormal.h), [xyzrgbanormal.cpp](https://github.com/Xamla/torch-pcl/blob/dev/src/xyzrgbanormal.cpp)).

**Comment by andreaskoepf** [comment]
I am personally not a boost::mpl expert but I think a modification of NdConcatenateFunctor to handle rgb<->rgba would be awesome.

**Comment by andreaskoepf** [comment]
I finally reverted adding a custom data type since this quickly became a maintenance nightmare. Regarding `concatenateFields` I will use a custom template specialization for now, e.g. see [xyzrgba.cpp#L12](https://github.com/Xamla/torch-pcl/blob/dev/src/xyzrgba.cpp#L12).
