### ISSUE TITLE
Possible race condition in FPFH feature, OMP implementation

### ISSUE THREAD

**Issue by MMiknis** [PointCloudLibrary/pcl#1593]
I am performing point cloud registration with a feature based methods ISS3D, FPFH and computing normals. For all these method I used the OMP version of them. But I found that with OpenMP enabled (4 threads) I get inconsistent results between the runs on the registration. Further looking into OpenMP it does say some implementation can suffer from "race condition".

I've done multiple runs and tests with OMP on and off. With ooff always gives me same result but with OMP results are inconsistent. 

Has anyone else seen this happen?

**Comment by andersgb1** [comment]
Could you please provide a working code example so others can reproduce the error?

**Comment by MMiknis** [comment]
Sure, I'll make a stand-alone code solution so other could run and test it

**Comment by andersgb1** [comment]
:+1:

**Comment by MMiknis** [comment]
OK here is most minimal pipeline I could make that shows it. So essentially if you run 10 tests with OMP off you will have same result and if you run 10 tests with OMP enabled you will get 3-4 different results.

System: Windows
PCL: 1.7.2

Code:
[Main.txt](https://github.com/PointCloudLibrary/pcl/files/228545/Main.txt)

Point clouds (can't upload .pcd files, so just remove the .txt ending):
[Source.pcd.txt](https://github.com/PointCloudLibrary/pcl/files/228547/Source.pcd.txt)
[Target.pcd.txt](https://github.com/PointCloudLibrary/pcl/files/228548/Target.pcd.txt)

**Comment by andersgb1** [comment]
I can confirm the bug! I added a line in your code where I saved your source descriptors **descriptors_src** to a PCD file. Then I ran your code multiple times without OpenMP and did a **diff** between the descriptor files. All the same

However, with OpenMP enabled, the descriptor files changed. I further had a look into the files. It seems that the parallelization shuffles the order of the descriptors. So basically I was able to identify the same descriptors between any two files, but in different offsets in the file.

**Comment by MMiknis** [comment]
I found for SHOT and SHOT colour as well. Found few papers which do say OpenMP can cause such issues and is called "race condition"

**Comment by andersgb1** [comment]
Yes, I agree it looks like a race condition, but the thing is I cannot see where inside the code that these would occur.

**Comment by MMiknis** [comment]
I will try do to some more tests to narrow down which part could be causing this if I get the time of course.

**Comment by carbomap** [comment]
By the way Ed, next week I'm presenting at the ICF conference in Newcastle.
I'll be talking about available RS technologies to map forest from the broader to small scale, meaning from satellite to UAV.
Because the audience will be mainly manager and decisions maker, we want to put some costing to give them an idea and also no one dare to put costing usually.
I've a good idea of the costing for airborne and uav but have no clue for satellite.
Do you have an idea of costing for such data that I could present? ballpark figures will suffice.
 
Cheers.
Antoine
 
--------- Original Message --------- Subject: Re: [PointCloudLibrary/pcl] Inconsistent registration results using OpenMP (#1593)

**Comment by andersgb1** [comment]
Antoine,

That's all very nice, but I don't see how that helps us solve any race conditions in our code.........

**Comment by vseib** [comment]
Dear all, 

in the discussion above, the problem was mentioned to occur with OMP implementations of FPFH, SHOT and COLORSHOT.
I was able to trace down the problem in the OMP implementation of COLORSHOT. However, I do not observe any inconsistencies in the OMP implementation of SHOT.

The problem occurs because the two look up tables 
`sRGB_LUT`
and
`sXYZ_LUT`
defined in shot.h are not computed on initialization of the class, but by the first thread arriving at the corresponding code in shot.hpp.

More precisely:
In shot_omp.hpp, lines 240-243 the OMP parameters are set for the following for loop to compute the descriptors. In line 280 the method computePointSHOT is called, this happens within the mentioned for loop with the pragma "omp parallel for".
This method is implemented starting on line 645 in shot.hpp. On line 685 the first call to the method RGB2CIELAB occurs. This method can be found starting on line 95 in shot.hpp. Please note that we are still within the "omp parallel for" context.
Line 101 in this method is
`if (sRGB_LUT[0] < 0)`
The first arriving thread evaluates this if-clause to true and starts computing the values and filling the LUT. Other threads arrive at this line and evaluate the if-clase to false, since the first value of the LUT was already computed by the first thread that arrived. However, the following computation accesses values of the LUT that might have not been computed, yet.

This race condition leads to inconsistent results for ColorSHOT descriptors. However, after both LUTs have been initialized the computed descriptors are consistent.

Possible solutions are:
1. initialize the sRGB_LUT and sXYZ_LUT when initializing the class
2. initialize both LUTs during compile time (in fact in the code a comment stating this TODO is already added)
3. add the pragma `#pragma omp critical` around the code in lines 101-120 in shot.hpp

My temporary workaround in my private project (without changing the PCL code) is the following:
1. create the ColorSHOT OMP object `pcl::SHOTColorEstimationOMP<PointT, pcl::Normal, pcl::SHOT1344> shotEst;`
2. Insert the Code from lines 101-120 in shot.hpp after creating the shotEst object.
3. Replace the occurances of `sRGB_LUT` and `sXYZ_LUT` in the _inserted_ code by `shotEst.sRGB_LUT` and `shotEst.sXYZ_LUT`, since both LUTs happen to be public in this context.

I hope this helps solving this bug. If you find this helpful, I would be willing to contribute a pull request.

Best,
Viktor

**Comment by kunaltyagi** [comment]
Beautiful writeup @vseib 

I think I have a solution that follows from your analysis of the bug. Could you check #4640 ?

**Comment by vseib** [comment]
Hi kunaltyagi,
I have checked your pull request #4640 - seems fine to me.
Thank you for fixing the bug.
I am not sure if I am allowed to approve a pull request, therefore I just created a review with a general comment.
