### ISSUE TITLE
ConvexHull/QHull does not work with Multithreading

### ISSUE THREAD

**Issue by soulslicer** [PointCloudLibrary/pcl#1618]
It seems that internally QHull is using some static libraries with Global objects, resulting in crashing or pointer initialization issues when calling the PCL functions:

http://www.pointclouds.org/documentation/tutorials/hull_2d.php

However, it seems that QHull seems to have published a multithreading friendly version of it's library:

https://www.researchgate.net/post/Does_anyone_know_how_to_perform_mutliple_concurrent_calls_to_the_qHull_C_library

http://www.qhull.org/src/Changes.txt

Unfortunately, doing an issue search on the Library yields nothing. Can I know what is PCL's status on this

**Comment by stefanbuettner** [comment]
Hi,

AFAIK PCL only uses the libqhull_p library, so no multithreading supported. However, using the multithreadable one when available makes sense and would be cool.
If you would provide a non-working example, because you already experienced the problem (and I'm lazy ;) ) I would have a look at it.

Cheers,
Stefan

**Comment by soulslicer** [comment]
i am working on seeing how to integrate the convex and concave hull classes to the libqhull_r library. the documentation on the libqhull side is challenging, hopefully i make some progess

**Comment by mvieth** [comment]
PCL now uses the reentrant interface of QHull, so using ConvexHull and ConcaveHull in multithreaded applications should be possible
