### ISSUE TITLE
cannot open include file:pcl/common/io.h: no such file or directory! Help pls..

### ISSUE THREAD

**Issue by loopyunicorn** [PointCloudLibrary/pcl#1646]
## Your Environment

* Operating System and version:64bit, windows 10
* Compiler:visual studio 2015 (64bit compiling)
* PCL Version:1.8 (64 bit installation) all-in-one installer

## Problem faced
Trying to compile a pcd read program from the tutorial (http://pointclouds.org/documentation/tutorials/reading_pcd.php). But, I consistently get the error : cannot open include file:pcl/common/io.h: no such file or directory

I have checked the common folder and the file io.h exists. They why is the compiler throwing the error? Is there error in the installer itself? Can anyone help me?

**Comment by SergioRAgostinho** [comment]
Hi @loopyunicorn . Given what you described this doesn't really look like a PCL issue, and therefore I will close it and suggest we continue this conversation on the mailing list. 

Nevertheless, how exactly are you setting up your project in visual studio? Are you using CMake to generate the project file? Because at first sight I, it looks like you're not telling your compiler where to look for pcl/common/io.h , which is something CMake would do for you automatically.

**Comment by loopyunicorn** [comment]
Hi,@SergioRAgostinho <https://github.com/SergioRAgostinho>

Thanks for replying. . And you are right. I do not use Cmake to generate
project file. I am new to the area and not that comfortable with CMake. If
there is a way I can tell my compiler to look for puzzle/common/io.h in
visual studio properties itself, it would be helpful. Any way I can do
that?

Btw, I have now posted on the mailing list too.And sorry for spamming  git
hub.



*Regards,*
*Madhumitha Senthilvel*

**Comment by yanyan-li** [comment]
add this code in your Cmakelists.txt file. ”find_package(PCL 1.7 REQUIRED)“
