### ISSUE TITLE
Local minimum problem with template aligment tutorial

### ISSUE THREAD

**Issue by piranna** [PointCloudLibrary/pcl#1655]
## Your Environment
* Operating System and version: Ubuntu Mate 16.10
* Compiler: gcc 5.4.0
* PCL Version: 1.7

![ajuste 1 y 7 limpios](https://cloud.githubusercontent.com/assets/532414/16949314/6fa912a8-4dba-11e6-8027-0c5eb2b64cbd.png)

## Expected Behavior
The attached image has two meshes in the background from two different scans, and we tried to make the one on the left to align with the one on the right. We have used the ICP algorithm as defined in the [template aligment](http://pointclouds.org/documentation/tutorials/template_alignment.php#template-alignment) tutorial.

## Current Behavior
In the attached image, the orange points cloud is the mesh on the left "adjusted" to the one on the right. Seems that instead of doing an aligment of the full mesh is doing a partial one and got stick to a local minimum solution where some fragments of the branches got aligment, instead of using the main fragment as reference.

## Possible Solution
Exec the ICP algorithm from several starting points, or try to find other solutions to prevent to find a local minimum one and keep searching for an optimal one.

## Context
I'm trying to align and combine some overlapping meshes from several scans since it's not possible to do the scan fully from one pass.

**Comment by SergioRAgostinho** [comment]
Hey @piranna. This is not a PCL bug. The optimization problem is most likely non-convex, so there's not much ICP can do you can if you provide a bad starting point. If you're providing a perfect initial alignment and ICP is diverging, you should try tunning your maximum correspondence distance and enforcing two way correspondence to see if it helps. From a generic perspective, we cannot "exec the ICP algorithm from several starting points" since that's something specific to everyone's particular problem.

**Comment by piranna** [comment]
Thank you very much for your answer, our intention was not report a bug on PCL, we just wanted to know if there was a way to fix that. We'll try your advice and come back with updates.

**Comment by taketwo** [comment]
I would recommend to concentrate on obtaining good initial alignment. Maybe extract some shape features and try to match them.

**Comment by VictorLamoine** [comment]
Please post your problem on the PCL mailing list, this is the best place to talk about these problems:
http://www.pcl-users.org/ (don't forget to register)
