### ISSUE TITLE
Bug in PointCloudColorHandlerRGBField

### ISSUE THREAD

**Issue by dudds4** [PointCloudLibrary/pcl#1656]
When using PointCloudColorHandlerRGBField on any pointcloud which contains points that are not finite (infinite or NaN), the coloring is misaligned, and points at the end of the cloud become black.
## Environment

- Operating System and version: Linux
- Compiler: gcc version 4.8.5
- PCL Version: 1.7
## Expected Behavior

For points that are infinite or NaN, coloring should not matter, since points should not be rendered
For clouds containing points that are infinite or NaN, finite points should all be colored according to their RGB field
## Current Behavior

For clouds containing points that are infinite or NaN, finite points are not all colored according to their RGB Field.
## Cause of Problem

```
in file "pcl/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp"
    lines 170-179

also in file "pcl/visualization/src/point_cloud_handlers.cpp"
    lines 167-173

  if (!pcl_isfinite (x_data) || !pcl_isfinite (y_data) || !pcl_isfinite (z_data))
    continue;

  colors[j    ] = rgb_data.r;
  colors[j + 1] = rgb_data.g;
  colors[j + 2] = rgb_data.b;
  j += 3;
```
## Possible Solution

```
  if (!pcl_isfinite (x_data) || !pcl_isfinite (y_data) || !pcl_isfinite (z_data)) {
       ; //Do nothing
  } else {
       colors[j    ] = rgb_data.r;
       colors[j + 1] = rgb_data.g;
       colors[j + 2] = rgb_data.b;
  }

  j += 3;
```
## Code to Reproduce

[exampleFiles.zip](https://github.com/PointCloudLibrary/pcl/files/374884/exampleFiles.zip)
## Context

I was trying to visualize a segmented organized point cloud. In order to keep the point cloud organized during filtering, points were made NaN.

**Comment by taketwo** [comment]
Looks strange. In geometry handler the invalid points are skipped as well (see [here](https://github.com/PointCloudLibrary/pcl/blob/62600eec99340138b802bb21a8201c0b099d10a7/visualization/include/pcl/visualization/impl/point_cloud_geometry_handlers.hpp#L98)). It makes no sense to write out colors for them.

**Comment by stefanbuettner** [comment]
Ah good point Sergey. It looked similar to another organized-cloud-issue I was looking at lately and I was just too lazy to look at it thoroughly.

@dudds4 The problem in the example is that you invalidate points of the point cloud but don't set the is_dense flag to false. If it's set to true,  the geometry handler copies all the spatial data including the NaNs. The color handler does not check that flag but the individual points no matter what. That's why the color information is shifted to the wrong points. Actually, if you set it to false, your version of the `ColorHandlerRGBField` produces wrong colors.

For completeness, it seems as `ColorHandlerCustom` and `ColorHandlerRandom` don't respect the NaN/is_dense convention at all. The produce a color array with the size of `cloud->points` which is always larger for non-dense clouds see [here](https://github.com/PointCloudLibrary/pcl/blob/62600eec99340138b802bb21a8201c0b099d10a7/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp#L49) and [here] (https://github.com/PointCloudLibrary/pcl/blob/62600eec99340138b802bb21a8201c0b099d10a7/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp#L77).

So, in my opinion, there is a bug in terms of inconsistent behavior. So the question is how to deal with that:

1. Not at all
2. Should the `ColorHandlerRGBField` also check the is_dense flag in order to speed up copying (which I think can also be optimized in the geometry hander)
3. Should the `GeometryHandlerXYZ` ignore the is_dense flag and check every point individually as the `ColorHandlerRGBField` does.

I'd like option 3, since people seem to forget about the is_dense flag and it is not unset automatically when a point is set to NaN. However, I don't know how often these methods are called and if a speedup really would make sense here. What do you think @taketwo?

Cheers,
Stefan

**Comment by taketwo** [comment]
`is_dense` tests are ubiquitous in the library; a lot of functions accelerate iteration this way. In visualization, however, speed is not critical, especially for one-time operations such as adding a point cloud to the visualizer. I think the third option is the best.

**Comment by dudds4** [comment]
I think that we can use option 2 in a way that satisfies your concern over users improperly setting the is_dense flag.

Looking at the file "pcl/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp"
line 164, we can change from 
     if (x_idx != -1)
to
     if (x_idx != -1 && !cloud_->is_dense)

This makes sense to me in that if the cloud is dense, there should be no need to check that all the xyz values are legal. We do end up copying color values for points that won't be rendered anyways, but that is only when the flag is misused, and as you said, this is a one-time operation 

I'm not sure if this speeds up copying, but I like it in that it respects the is_dense flag, but also is robust enough to handle misuse. What do you guys think?

**Comment by jspricke** [comment]
I don't agree that visualization is not critical, it totally depends on the size of the clouds. We surely don't use is_dense consistently over the lib, but as we have it, I would argue for relying on it.

Would it make sense to automatically set the the flag to false when a nan value is written to the cloud?

**Comment by taketwo** [comment]
> Would it make sense to automatically set the the flag to false when a nan value is written to the cloud?

This would be awesome, but how? Point cloud storage is not properly encapsulated, there are million ways to get access to it and modify individual values without the point cloud object knowing that something is happening.

**Comment by jspricke** [comment]
Right, but we could at a test to the operators in `point_cloud.h` and if someone fills the points manually (for speed for example) he is on it's own.

**Comment by kunaltyagi** [comment]
User setting flags improperly is violating the contract. We can't protect the user and give unfettered access for speed at the same time
