### ISSUE TITLE
Add option that build with FLANN dynamic linking on Windows

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#1918]
PCL always search static library of FLANN on Windows.
It is good operation as default settings.
But, I think that FLANN search should be introduce an option to search for dynamic libraries like a Boost for Windows users. ([PCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32](https://github.com/PointCloudLibrary/pcl/blob/46cb8fe5589e88e36d79f9b8b8e5f4ff4fceb5de/cmake/pcl_options.cmake#L22-L23))
What do you think about this proposal?

* pcl/pcl_options.cmake#add_new_line
```cmake
# Build with dynamic linking for FLANN (advanced users)
option(PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32 "Build against a dynamically linked FLANN on Win32 platforms." OFF)
mark_as_advanced(PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32)
```

* [CMakeLists.txt#L281-283](https://github.com/PointCloudLibrary/pcl/blob/master/CMakeLists.txt#L281-L283)
```cmake
if(NOT PCL_SHARED_LIBS OR ((WIN32 AND NOT MINGW) AND NOT PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32))
    set(FLANN_USE_STATIC ON)
endif()
```

**Comment by SergioRAgostinho** [comment]
I think the developer should always have the option to select if its dependencies are static or dynamic, so in that sense I endorse the proposal.

Now the question we should be asking is why weren't we allowing to link against a dynamic flann on Windows? What happens if we simply do this?
```cmake
if(NOT PCL_SHARED_LIBS)
    set(FLANN_USE_STATIC ON)
endif()
```

We can wait for you to submit the PR with the proposal.

**Comment by UnaNancyOwen** [comment]
I don't know the reason why it was implemented this.
However, FLANN is a required library in some major modules of PCL.
I think that it is better to static link FLANN in default settings on Windows.
(Boost is also static link in default settings on Windows.
I think that FLANN is better for the same action as Boost.)

**Comment by SergioRAgostinho** [comment]
@UnaNancyOwen Can you try on your windows environment to modify the CMakeLists.txt to removed the check for windows and report on the results?

```cmake
if(NOT PCL_SHARED_LIBS)
    set(FLANN_USE_STATIC ON)
endif()
```

> However, FLANN is a required library in some major modules of PCL.
I think that it is better to static link FLANN in default settings on Windows.
(Boost is also static link in default settings on Windows.
I think that FLANN is better for the same action as Boost.)

If there's no real known reason at this point, then we should try to see what happens if we just try to mimic the linking behavior of the other OSs.

**Comment by UnaNancyOwen** [comment]
I sent a pull request (#1919). This change does not affect other OS.
It will same setting as before by default settings on Windows.
FLANN is dynamically linked only when explicitly setting option by user.

@SergioRAgostinho I will confirm that.
It was able to build successfully when I tried it before.

**Comment by UnaNancyOwen** [comment]
@SergioRAgostinho I tried some tutorials, and confirmed that these tutorials can be built and ran successfully.

**Comment by SergioRAgostinho** [comment]
Then we definitely needs to revise things after this release.

**Comment by SergioRAgostinho** [comment]
(new pretty labels nice :D)

**Comment by SergioRAgostinho** [comment]
Superseeded by #2089.
