### ISSUE TITLE
PCL property sheet for 1.8.1

### ISSUE THREAD

**Issue by arianaa30** [PointCloudLibrary/pcl#1935]
Hi,
I need helps on using visual studio 2017 for PCL. I downloaded a all-in-one installer for the latest 1.8.1 from your page at here:
https://github.com/PointCloudLibrary/pcl/releases/tag/pcl-1.8.1rc1

But where to find the **PCL 1.8.1** property sheet? I had one for 1.8.0 but with that my project can not compile.

**Comment by UnaNancyOwen** [comment]
We don't have a plan to provide property sheets.
Please generate your own project using CMake.
Please read this [documents](http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php).

I will tell you the history about PCL on Windows.
Previously, I had been provide unofficial all-in-one installer of PCL 1.7.
It was not possible to generate a user own project using CMake, because PCL 1.7 had some problems about configuration files. (It has not been maintained for a long time.)
For this reason, I was provide property sheets for setting the user own project.
It was a temporary alternative method.

I fixed all problems about configuration files to generate a user own project of Visual C++ using CMake.
Therefore, Since PCL 1.8 (or later), You can generate your own project using CMake.
This project that generated using CMake has already been setting to use PCL.
You no longer don't need to use property sheets.

We recommend using CMake.
And, We can't support use property sheets.

**Comment by arianaa30** [comment]
So you mean we should only use CMake generators to generate VS project files?

**Comment by SergioRAgostinho** [comment]
That's the only method we officially support.

**Comment by raghav2984** [comment]
Hi All,
I'm a newbie to PCL. Can anyone help me to install PCL to use with .net platform. Thank you in advance.

Regards,
Raghav
