### ISSUE TITLE
Bug about mesh loading in simulation

### ISSUE THREAD

**Issue by freedomabcd** [PointCloudLibrary/pcl#2028]
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: GCC 5.4
* PCL Version: Latest

## Expected Behavior
Input a mesh with color, hoping to display it with color.

## Current Behavior
The displayed mesh is always in red color.

## Possible Solution
In pcl/simulation/src/model.cpp.

change line 119
from
`if (plg->cloud.fields[i].name.compare ("rgb") == 0)`
to
`if (plg->cloud.fields[i].name.compare ("rgb") == 1)`

## Context
I use simulation module to display a mesh with color.
But the mesh color is always in red.
I find that when loading mesh, the condition to judge the color existing may be wrong.
I change the condition and the result goes as expected

**Comment by taketwo** [comment]
Good catch! But the fix is wrong and works by accident ;)

Observe that `compare` function is used to check if the name of the field matches "rgb". According to the [documentation](http://www.cplusplus.com/reference/string/string/compare/), this function returns `0` when strings are equal. So the existing code is correct.

I think the problem might be that your mesh contains colors in the "rgba" field. Can you try to test if this field exists?

**Comment by freedomabcd** [comment]
Well, you are right, the filed is "rgba".

So how can I load the color?

**Comment by taketwo** [comment]
Just change the line to

```cpp
if (plg->cloud.fields[i].name.compare ("rgb") == 0 || plg->cloud.fields[i].name.compare ("rgba") == 0)
```

**Comment by freedomabcd** [comment]
Ok, I add corresponding code and everything is OK.
Thanks for your help!
