### ISSUE TITLE
compile really slow when using PCL

### ISSUE THREAD

**Issue by mechaZYK** [PointCloudLibrary/pcl#2033]
when using PCL library， the compilation process is  really slow, this may be caused by the boost library, is there any way too accelarate the process? Every time I change a little bit of my code, some of the boost headers will be compiled again.

**Comment by moriarty** [comment]
Do you mean when using PCL in your project, or when compiling PCL itself?

**Comment by jasjuang** [comment]
If you are on linux, try `make -j` instead of just `make`.

**Comment by moriarty** [comment]
PCL has a lot of template code, which is slow to compile, and it also requires a lot of ram, so if you have less than 4Gb ram, adding more jobs with ```-j``` won't help.

But that's about compiling PCL itself. Once it's compiled and installed on your system, it runs fine.

I'm gonna say that Boost, is not the issue... Boost is one of the most common C++ libraries, not that it doesn't have bugs, but if it was causing compilation to be slow, that would be noticed and fixed.

I compile a large amount of code, which uses a large amount of Boost daily, and it takes just a few minutes for a full build (million lines). Or seconds for a small change. If your small change, is in a very core component which other things depend on in a way which they need to be recompiled, then yes it will recompile those modules and take a little longer...

There is likely, an issue with your code, or your makefiles. Taking a quick look at one of your git repositories:
* You should try to put your includes into your cpp files unless you _really_ use it in the header file.
http://www.cplusplus.com/forum/articles/10627/ ... I just grabbed a random reference off of Google.
* You should also use the pimpl method, and Google for "Compilation Firewall"
* You makefiles or cmake files should break the project up in ways which make sense and guard against independent components so that the whole project isn't recompiled.

But I think that this issue can be closed unless you can provide proof that the issue is a problem with PCL.

**Comment by mechaZYK** [comment]
I finally found the reason. This is due to some code in the head "pcl_visualizer.h"
causing by the delaration of <PointXYZL>
` inline bool
        addPointCloud (const pcl::PointCloud<pcl::PointXYZL>::ConstPtr &cloud,
                       const std::string &id = "cloud", int viewport = 0)
        {
          pcl::visualization::PointCloudColorHandlerLabelField<pcl::PointXYZL> color_handler (cloud);
          return (addPointCloud<pcl::PointXYZL> (cloud, color_handler, id, viewport));
        }`

but the "cpp" file doese not do an instantiation of <PointXYZL>, so when I include this header. Every time I complie, there will be an instantiation of <PointXYZL>
