### ISSUE TITLE
A heap-overflow issue in src/pcd_io.cpp 

### ISSUE THREAD

**Issue by PengPengHub** [PointCloudLibrary/pcl#2045]
Hi There 

We found a heap overread bug in src/pcd_io.cpp, you could reproduce the issue through docx file. If you have any questions, please contact me at lipeng28@baidu.com. One more question here, do you provide any CVEs for vulnerabilities?
[pcl.zip](https://github.com/PointCloudLibrary/pcl/files/1428337/pcl.zip)

Thanks
Peng

**Comment by SergioRAgostinho** [comment]
Hey. Thanks for reporting.

> We found a heap overread bug in src/pcd_io.cpp, you could reproduce the issue through docx file

Your archive doesn't include a docx file.

> One more question here, do you provide any CVEs for vulnerabilities?

I never heard of it so assume that we don't.

From my size here's the summary:
- I tried tried passing your -fsanitize=address flags to both gcc and clang and none complains.
- I ran both compiled version through valgrind and I still get no complains.
- You did tamper with the field type, which will cause your point cloud to be filled with bit trash, since `getFieldSize` won't be able to infer the size properly any more and it will return 0 instead of the original 4. Nevertheless I see no situation in which we are reading outside of the memory we (pre)allocated. 
- I also questioned if it could be the memory map we request, since we read the size value from the PCD, but from what I can tell, it cannot map more than the entire content of the file.

I'm out of ideas.

**Comment by PengPengHub** [comment]
Hi Sergio

Thanks for your response, sorry that I forgot attaching the documentation, please see the it here. 
[PCL_heap_overflow.docx](https://github.com/PointCloudLibrary/pcl/files/1516583/PCL_heap_overflow.docx)

However, I tried to run again with the latest master branch of PCL, the bug disappeared. I guess it got fixed. 

Thanks
Peng

**Comment by SergioRAgostinho** [comment]
Ok now I know where to look  :) We did push some changes after 1.8.1 which affected the behavior of `getFieldType` and `getFieldSize`. I'm nevertheless gonna confirm all the steps in your report just to be sure that we're out of the loop.

**Comment by SergioRAgostinho** [comment]
I confirm that the current master doesn't suffer from it anymore
```cpp
data_size = 120000;
std::vector<char> buf (data_size);
pters[0] = &buf[0];
pters[1] = &buf[0];
pters[2] = &buf[40000];
std::vector<int> fields_size = {0, 4, 4};
cloud.width = 10000;
cloud.height = 1;
```
with the following values, the memcpy that happens, never reads out of bounds.

Thanks for reporting.
