### ISSUE TITLE
QVTKWidget "unknown pixel format, no opengl support"

### ISSUE THREAD

**Issue by buhoche** [PointCloudLibrary/pcl#2052]
I have a QT application with a qvtkwidget inside.
On my laptop (intel i5 with intel graphic) everything is working
On my desktop Intel i5 with NVIDIA graphic I get the message "unknown pixel format, no opengl support" on startup and the app ends
Any suggestions?

## Your Environment
* Operating System and version:
Windows10
* Compiler:
VS2015
* PCL Version:
PCL 1.8.0, VTK 7.1 QT5.7

## Expected Behavior
runnig app as on my laptop

## Current Behavior
error message

**Comment by taketwo** [comment]
This is a bug tracker, not a support forum. Please forward such questions to pcl-users mailing list.
Besides, this problem is not related to PCL, rather Qt+VTK. Quick googling of your error message [reveals](http://vtk.1045678.n5.nabble.com/Invalid-pixel-format-no-OpenGL-support-td5734668.html) that it's recommended to use `QVTKWidget2`.
