### ISSUE TITLE
Provide proper depreciation to EuclideanClusterComparator

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2091]
Following up on the discussion of https://github.com/PointCloudLibrary/pcl/pull/1542#issuecomment-344933466

**Comment by taketwo** [comment]
I am not aware of any proper way to deprecate the removed template parameter, so I think we will break API anyway.

But of course, It would be nice to add depreciation warnings to removed functions. The user will see a compiler error (because of mismatched template list) and these warnings from follow-up function calls. So perhaps it would be handy to put a note about what happened with template parameters in these warnings.

**Comment by SergioRAgostinho** [comment]
we can leave the template parameter there and remove it in the future.

**Comment by taketwo** [comment]
True. So when users use deprecated functions they will be warned both about the functions themselves and about the future template parameter removal. Sounds good for me.
