### ISSUE TITLE
Running Tests on AppVeyor CI

### ISSUE THREAD

**Issue by UnaNancyOwen** [PointCloudLibrary/pcl#2136]
We implemented build test on Windows CI.
Next, We should consider running tests on Windows CI.

I implemented [google test](https://github.com/Microsoft/vcpkg/pull/2261) to vcpkg.
I confirmed that it can be used in PCL on my local environments.

```patch
  install:
-   - vcpkg install boost eigen3 flann qhull --triplet %PLATFORM%-windows
+   - vcpkg install boost eigen3 flann qhull gtest --triplet %PLATFORM%-windows
```
```patch
  build_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - mkdir build
    - cd build
    - cmake -G"%GENERATOR%"
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake
            -DPCL_BUILD_WITH_BOOST_DYNAMIC_LINKING_WIN32=ON
            -DPCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32=ON
-           -DPCL_NO_PRECOMPILE=ON
+           -DPCL_NO_PRECOMPILE=OFF
            -DBUILD_simulation=ON
-           -DBUILD_global_tests=OFF
+           -DBUILD_global_tests=ON
            -DBUILD_examples=OFF
            -DBUILD_tools=OFF
            -DBUILD_apps=OFF
            ..
    - cmake --build . --config %CONFIGURATION%
+   - ctest -C %CONFIGURATION% -V
```

Probably, I think it have probrem that long build time will be time-out on AppVeyor.
Therefore, I propose to turn off <code>PCL_NO_PRECOMPILE</code>.
The build time is as follows on my local environments.
<table>
  <tr>
    <th>PCL_NO_PRECOMPILE</th>
    <th>Build Time</th>
  </tr>
  <tr>
    <td>ON</td>
    <td>1hour 30min over</td>
  </tr>
  <tr>
    <td>OFF</td>
    <td>30min</td>
  </tr>
</table>

If this is not desirable, We should consider splitting jobs like Travis.

BTW:
However, the some tests fails on Windows.
It is known issues. (https://github.com/PointCloudLibrary/pcl/issues/1719)

```
93% tests passed, 7 tests failed out of 103

Total Test time (real) = 152.72 sec

The following tests FAILED:
	 13 - common_eigen (Failed)
	 23 - feature_rift_estimation (Failed)
	 25 - feature_cppf_estimation (Failed)
	 27 - feature_pfh_estimation (Failed)
	 50 - filters_sampling (Failed)
	 68 - io_grabbers (Failed)
	 80 - registration_api (Failed)
```

**Comment by SergioRAgostinho** [comment]
Super thanks for extending this.

> <table>
>   <tr>
>     <th>PCL_NO_PRECOMPILE</th>
>     <th>Build Time</th>
>   </tr>
>   <tr>
>     <td>ON</td>
>     <td>1hour 30min over</td>
>   </tr>
>   <tr>
>     <td>OFF</td>
>     <td>30min</td>
>   </tr>
> </table>

I confess this is somewhat a surprising result, since in theory it should only compile the types which are instantiated. But I set it to ON before exactly to reduce build times. If you verify that this better to use the precompile mechanism let's go with it of course. It mgiht be worth to also set `PCL_ONLY_CORE_TYPES=ON` let's go with that.

> If this is not desirable, We should consider splitting jobs like Travis.

I didn't do it on the first iteration because it require some windows bash scripting and I'm lacking a dev environment to test it.

> However, the some tests fails on Windows.
It is known issues. (https://github.com/PointCloudLibrary/pcl/issues/1719)

We would need to disable them in an initial stage, but we can do that as well.
