### ISSUE TITLE
There are some errors while running GreedyProjectionTriangulation test

### ISSUE THREAD

**Issue by SmileJohnson** [PointCloudLibrary/pcl#2139]
:warning: This is a issue tracker, please use our mailing list for questions: www.pcl-users.org. :warning: 

## Your Environment

* Operating System and version: Win7
* Compiler: VS 2010
* PCL Version: 1.6.0

## Context

error C2039: “PCLPointCloud2”: not a member of “pcl”
error C2039: “fromPCLPointCloud2”: not a member of “pcl”

The related codes are following:

pcl::PointCloud<pcl::PointXYZ>::Ptr cloud(new pcl::PointCloud<pcl::PointXYZ>);
pcl::PCLPointCloud2 cloud_blob;
pcl::io::loadPCDFile("Bunny.pcd", cloud_blob);
pcl::fromPCLPointCloud2(cloud_blob,  *cloud);

**Comment by SergioRAgostinho** [comment]
I think you're not including the right headers, but I can't really tell because the code you posted is not enough to verify it. 

Nevertheless, this is an issue tracker, and your problem is definitely not a library issue. You're taking your first steps into using the library and probably making some mistakes along the way.

Please our user mailing lists for questions and support. http://www.pcl-users.org/
