### ISSUE TITLE
Invalid use of Incomplete Type 'pcl::PointXYZ'

### ISSUE THREAD

**Issue by AcrimoniousMirth** [PointCloudLibrary/pcl#2180]
I've been signed up to the mailing list for 6 months now and followed all the steps necessary but still don't seem able to ask questions, nor do admin seem willing or able to help (thanks guys).
So I'm posting this here, also my brief research suggests this is an issue with the library itself and not my code, so...
Programming C++ in Xcode,
`#include <pcl/impl/point_types.hpp>
`
and using PointXYZ to push values to the point cloud:
` totalCloud.push_back (PointXYZ (xVal, yVal, zVal));`

which returns the error given. Did some digging, looks like this comes from an improper setup of the code, so is an error in the library itself.

**Comment by ThorstenHarter** [comment]
You should include `PCL/common/include/pcl/point_types.h`, the hpp contains the implementation.

**Comment by SergioRAgostinho** [comment]
We're not a company and you're not paying us to provide you a service. We're not on top of everything that happens all the time since like every other human, we check a limited number of things a day. The underlying tone on your message is borderline rude and unnecessary. That being said let's get back to the matters at hand.

Mailing list: contact me directly over email. My email is splattered in every commit I did to the repo so it's fairly easy to find it. Here's one for instance https://github.com/PointCloudLibrary/pcl/commit/075539da3f2da4e705db157e8149584e184bc945. Send me the email you're trying to register in the mailing list for me to check things and let's move the conversation there.

Thorsten provided you the answer that is likely to solve your problem.

As you already know and once the ml things is settled, use it for these types of questions. We only deal with bug reports and code submissions here.

**Comment by AcrimoniousMirth** [comment]
@SergioRAgostinho hi, I’m sorry for coming across as rude. Truth be told I’ve been plodding away at trying to get this library to work for over 6 months now in between my university studies. I’m not a programmer so it’s been tough going and to be honest I’d say it speaks in my favour that it took me 6 months of trying and repeatedly getting bounce messages from the mailing list to finally get rude.
That being said I’m really not that good at programming so I don’t really have a leg to stand on, so I apologise.

@ThorstenHarter thanks for that, I was copying the headers etc from example code on the PCL so I assumed it to be correct! I’ll keep my eye out for that in the future :)
