### ISSUE TITLE
Support for Realsense ?

### ISSUE THREAD

**Issue by CesMak** [PointCloudLibrary/pcl#2350]
hey there I currently used this line:

`  pcl::Grabber* interface = new pcl::OpenNI2Grabber (device_id);`

Now I would like to use a realsense r200 camera - is there an easy way to use this camera with pcl. Or is there a grabber to grab realsense data?

**Comment by UnaNancyOwen** [comment]
You can use [pcl::RealSenseGrabber](http://docs.pointclouds.org/trunk/classpcl_1_1_real_sense_grabber.html) for RealSense R200.
(It is required PCL that built with WITH_RSSDK option. This grabber only works on Windows, because RealSense SDK 1.x is only supported Windows.)

This is an issue tracker, Please use our mailing list for questions: [www.pcl-users.org](http://www.pcl-users.org).
