### ISSUE TITLE
unable to execute xyz2pcd.cpp from tools section

### ISSUE THREAD

**Issue by nikhilbv** [PointCloudLibrary/pcl#2362]
Can you please tell me how to execute xyz2pcd.cpp file in the tools section. I am not able to execute it.
I want the procedue to build and execute it. 

I am getting the following error -
terminate called after throwing an instance of 'pcl::IOException'
  what():  : [pcl::PCDWriter::writeBinaryCompressed] Input point cloud has no data!
Aborted (core dumped)

## Your Environment

Operating System and version: ubuntu 16.04
* Compiler:
* PCL Version: 1.8

**Comment by frozar** [comment]
Hum, it's still pretty hard to help you because you explain your problem in a poor way. I cannot catch what's wrong there: do you have a compiling problem? a environment problem? a dependancy problem? a configuration problem?  
You don't show what you actual do to get stuck and it's hard someone which is not watching you in your back to understand what's wrong. Well, let say from your message I guess your issue.

The file `xyz2pcd.cpp` have to be compile before getting the final executable.  
Did you check the documentation page about [Compiling PCL](http://www.pointclouds.org/documentation/tutorials/compiling_pcl_posix.php). If not, it should be a great start to read it carefully.

Assuming that the PCL repository is in the directory `~/wk/pcl`, to generate the `pcl_xyz2pcd` executable, you should type:
```bash
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ~/wk/pcl && make -j2 pcl_xyz2pcd
```

After that your build directory should contain the file `./bin/pcl_xyz2pcd` which is what you want.

I test it on the attached file and it works indeed.
[toto.xyz.zip](https://github.com/PointCloudLibrary/pcl/files/2144537/toto.xyz.zip)

**Comment by nikhilbv** [comment]
Hi,

Can you please check with the attached file once

​
 47_ll.xyz.zip
<https://drive.google.com/file/d/1PJp7cG4uaNf0Ngyk3JQXKrTcZYaYLvrB/view?usp=drive_web>
​

**Comment by frozar** [comment]
I tried it with your file, effectively, it doesn't work because your file don't have the good format. What is expected in an .xyz file is, for each line, `<coord_x> <coord_y> <coord_z>`. But in your file, on each line you provide 6 fields, which are ignored by the reader.

So I modified your file and I was assuming that the 3 first fields are the point coordinates. To make it works, I type the following:
```bash
cat ~/tmp/47_ll.xyz | cut -d" " -f-3 > ~/tmp/47_ll_wk.xyz
./bin/pcl_xyz2pcd ~/tmp/47_ll_wk.xyz ~/tmp/47_ll.pcd
```

And guess what, it works gracefully.

The Issue tracker is not done for this kind of question. Please use the user mailing, it would be really more appropriated in your case. I will not answer any more question on this issue tracker about your problem.

Cheers

**Comment by taketwo** [comment]
Thanks for looking into this, Fabien.
