### ISSUE TITLE
Plane coefficient comparator compares angles wrong

### ISSUE THREAD

**Issue by Kaju-Bubanja** [PointCloudLibrary/pcl#2365]
Looking at the plane_coefficient comparator [here
](https://github.com/PointCloudLibrary/pcl/blob/master/segmentation/include/pcl/segmentation/plane_coefficient_comparator.h) regarding the compare method on line 182-200 I think the comparison of the angles is wrong. I think the line 199 should be 
`&& (1.0 - fabs(normals_->points[idx1].getNormalVector3fMap ().dot (normals_->points[idx2].getNormalVector3fMap () )) < angular_threshold_)
`
## Your Environment

* Operating System and version: Ubuntu 16.04
* Compiler: gcc
* PCL Version: 1.8

## Context

I'm trying to use the multiple plane segmentation algorithm and tried to improve it, while looking at the code I found this potential bug.

## Expected Behavior

I propose this as a fix:
` (1.0 - fabs(normals_->points[idx1].getNormalVector3fMap ().dot (normals_->points[idx2].getNormalVector3fMap () )) < angular_threshold_)
`

## Current Behavior

This small snippet shows an example where the result is wrong:

```cpp
bool compare ()
{
  double angular_threshold_ = pcl::deg2rad(2.0);
  Eigen::Vector3f a(0,0,1);
  Eigen::Vector3f b(0,sqrt(0.75),0.5);
  double angle = pcl::rad2deg(acos(b.dot (a)));
  std::cout << angle << std::endl;
  return (b.dot (a) > angular_threshold_ );
}
```

## Code to Reproduce

This small snippet shows an example where the result is wrong:
```cpp
bool compare ()
{
  double angular_threshold_ = pcl::deg2rad(2.0);  

  Eigen::Vector3f a(0,0,1);  
  Eigen::Vector3f b(0,sqrt(0.75),0.5);  
  double angle = pcl::rad2deg(acos(b.dot (a)));  
  std::cout << angle << std::endl;  
  return (b.dot (a) > angular_threshold_ );  
}
```

## Possible Solution

I propose this as a fix:
` (1.0 - fabs(normals_->points[idx1].getNormalVector3fMap ().dot (normals_->points[idx2].getNormalVector3fMap () )) < angular_threshold_)
`

**Comment by taketwo** [comment]
This does look like a bug. But in your proposal, why `fabs`ing the dot product?

**Comment by Kaju-Bubanja** [comment]
Because if the normals are not all orientated the same way you might get -1. I had this when I wanted to compare every point normal to the already found plane equation in the segment step.

**Comment by taketwo** [comment]
So you mean that planes with opposite normals should be treated as same by the plane comparator? Well maybe, depends on the use case I suppose. It's not documented though.

**Comment by frozar** [comment]
I would say it's noraml to take the `fabs` in this case, because the computation of the normals if usually done by solving the eigen value/vector of the covariance matrix around a given point, and the orientation of the final normal vector it is not really consider in this problem. The direction yes, but orientation depend in which this algorithm converges...

**Comment by taketwo** [comment]
That's true, for this reason one usually post-processes normals to make their orientations consistent (e.g. for single-view point clouds by orient them towards the camera origin).

But generally I agree, we can have this `abs`. Ideally with a bool property to disable it, if desired.

**Comment by frozar** [comment]
For me, definitly the normal orientation is tricky, because when you have a build, with inside and outside point, what you want is not necessary the orientation toward the center of a camera. Usually what people want when they say "consistant orientation", for point from the outside, let say normal orientation toward the ouside, but for the point of inside, orientation toward the center of the building.

You have also the smooth way that orient the normal neighbour after neighbour by keeping the orientation which minimize the angle with a given normal vector of reference. But this doesn't ork either blindly for every kind of geometry, so is still tricky.

I don't know a magical way to solve this problem. And I agree with you, the user should have the choice with a `bool` option to disable it if he wants.

**Comment by Kaju-Bubanja** [comment]
Should I write a PR? Seems like a small thing, so this can be closed.

**Comment by taketwo** [comment]
You are certainly welcome to send a PR. Note, however, that this code is duplicated in multiple comparator classes, so this calls for a small refactoring.

**Comment by Kaju-Bubanja** [comment]
Opening PCL in Clion and searching for instances of these lines: `(fabs ((*plane_coeff_d_)[idx1] - (*plane_coeff_d_)[idx2]) < threshold)
                 && (normals_->points[idx1].getNormalVector3fMap ().dot (normals_->points[idx2].getNormalVector3fMap () ) > angular_threshold_ )` I could not find this line duplicated somewhere. Could you point me to the duplicates or show me how to find them? I would like to fix this and send a PR.

**Comment by SergioRAgostinho** [comment]
We started very recently merging PRs which replace `fabs` for `std::fabs` and others, which might be the reason you're not finding it. See
https://github.com/PointCloudLibrary/pcl/blob/4dfde2071063a863dc59c57b974b0f6de33b5dfd/segmentation/include/pcl/segmentation/plane_coefficient_comparator.h#L197-L198

**Comment by Kaju-Bubanja** [comment]
PR here: https://github.com/PointCloudLibrary/pcl/pull/3299
