### ISSUE TITLE
RangeLikelihood getters lack const qualifier

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2398]
All the get methods need a const qualifier.
https://github.com/PointCloudLibrary/pcl/blob/master/simulation/include/pcl/simulation/range_likelihood.h

**Comment by JamesGiller** [comment]
I'm working on this issue.

FYI there are four get methods that shouldn't take a const qualifier:
`getColorBuffer`, `getDepthBuffer`, and `getScoreBuffer` because they set member variables `depth_buffer_dirty_`,  `color_buffer_dirty_`, `score_buffer_dirty_` respectively.
`getPointCloud` because it calls `getColorBuffer`.

**Comment by SergioRAgostinho** [comment]
No problem. Just apply it to the ones you can. Thanks.

**Comment by taketwo** [comment]
If these member fields are for caching only and do not belong to the observable object _state_, then they can be marked as `mutable` and be modified in `const`-qualified methods. But I am not familiar with the code base, so you need to use your own judging of whether this is appropriate or not.

**Comment by SergioRAgostinho** [comment]
It's as you pointed out. They are used as a caching mechanism and they have no getters, making them not observable from the outside.
