### ISSUE TITLE
GCC 8 warning in octree_key.h:143 type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]

### ISSUE THREAD

**Issue by pumaking** [PointCloudLibrary/pcl#2404]
https://github.com/PointCloudLibrary/pcl/blob/5b89b76243f03b601db47efa38181f4ac72c4538/octree/include/pcl/octree/octree_key.h#L143

## Your Environment

* Compiler: gcc (Ubuntu 8-20180414-1ubuntu2) 8.0.1 20180414 (experimental) [trunk revision 259383]
* PCL Version: 1.8

## Expected Behavior

The header files should compile without warnings.

## Current Behavior

The header file octree_key.h fails to compile with the GCC 8 warning -Wignored-qualifiers.

## Possible Solution
I believe const unsigned char should be changed to unsigned char in the static_cast.

**Comment by SergioRAgostinho** [comment]
> The header file octree_key.h fails to compile with the GCC 8 warning -Wignored-qualifiers.

How exactly is it **failing** to compile if it's a warning and not an error?

> I believe const unsigned char should be changed to unsigned char in the static_cast.

The idea from the original author is that `maxDepth` is not meant to be changed and that is why it is has a `const` qualifier. At first sight, the only thing I see "wrong" with that line is the fact that the initialization is done inline instead of being done on the implementation file.

I'm surprised about the warning and I'm confused why it is appearing. Thanks for reporting.

**Comment by SergioRAgostinho** [comment]
Makes sense. Care to open a PR with the change. I’ll merge it ASAP.

Cheers

--

**Comment by pumaking** [comment]
Done, thanks!
