### ISSUE TITLE
No assignment operators for PCL point types.

### ISSUE THREAD

**Issue by csukuangfj** [PointCloudLibrary/pcl#2468]
## Your Environment

* PCL Version: the master branch

## Context

Some pcl point types have a copy constructor defined but no assignment operator is available.

For example, see the code
https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L287-L298

https://github.com/PointCloudLibrary/pcl/blob/9467b944ee3e30bb4cf8445d861c280f0fba1020/common/include/pcl/impl/point_types.hpp#L339-L350

## Expected Behavior

Since all PCL point types are POD no copy constructor is required. But if a copy constructor is provided then an assignment operator should also be implemented.

## Current Behavior

Copy constructor is available but assignment operator is missing.

## Code to Reproduce

See the code above.
## Possible Solution

Either remove the copy constructors or add the corresponding assignment operators.

**Comment by taketwo** [comment]
As is often the case, I have no explanation for the old PCL code. The copy constructors are superfluous indeed. As for assignment, there is a generic `copyPoint()` function which is capable of copying point data, even between points of different type. I think it's preferable if algorithms use this function explicitly rather than assignment operator.

**Comment by kunaltyagi** [comment]
`inline PointXYZ (const _PointXYZ &p)` is not a copy ctor. As per [standard](https://en.cppreference.com/w/cpp/language/copy_constructor), only `inline PointXYZ (const PointXYZ &p)` (notice the lack of `_` prefix) can be a copy-ctor.
