### ISSUE TITLE
Migrate Tracis CI from GitHub Services to GitHub App

### ISSUE THREAD

**Issue by SergioRAgostinho** [PointCloudLibrary/pcl#2531]
@jspricke  GitHub Services are being phased out. We need to start using Travis CI through the GitHub Apps interface. 

See more information here 
https://developer.github.com/changes/2018-04-25-github-services-deprecation/

**Comment by jspricke** [comment]
On it

**Comment by jspricke** [comment]
I changed them to Apps, not sure if they work already..

**Comment by SergioRAgostinho** [comment]
Probably all is well. I’ll ping you again if needed.

**Comment by SergioRAgostinho** [comment]
Ok, we there's something: I don't see GitHub CI added to the checks section of the repo.

**Comment by jspricke** [comment]
Seems to work now, except the doc job not sure if that should work @taketwo maybe you can have a look?

Also, we have a 100 minute timeout :).

**Comment by SergioRAgostinho** [comment]
Let me get everything to run green just to confirm and then we disable the old webhook to travis-ci.org and update the badge.

**Comment by jspricke** [comment]
Should I ask for a longer timeout? Do you have an example where it failed because of the timeout?

**Comment by taketwo** [comment]
[Here](https://travis-ci.com/PointCloudLibrary/pcl/builds/87456813) Sergio tried with a single build/test job and it failed with a timeout. After this he split the task into two and they became [shorted than 100 minutes](https://travis-ci.com/PointCloudLibrary/pcl/builds/87613025)

It's hard to estimate how much more time we would need for the single job approach. Probably 30 minutes will be sufficient, but only empirical test can show. But anyway, if they give us longer timeout we will use _less_ of their resources since now a lot of compilation is duplicated between our build and test tasks (despite the name, "test" actually means "build tests + test").

**Comment by jspricke** [comment]
Thanks, I would propose to leave it slit and fix the failing tests first. One we are sure that compiling everything makes sense, we can still ask for more.

**Comment by SergioRAgostinho** [comment]
FYI, I just learned Travis CI started rolling out Windows environments. It's not supporting C/C++ yet though.

**Comment by taketwo** [comment]
Did Anna tell you this? :wink:

**Comment by SergioRAgostinho** [comment]
Reopening because of the issue with the docs job in #2538 .
