### ISSUE TITLE
probelm in pairwise_incremental_registration tutorial

### ISSUE THREAD

**Issue by anranx** [PointCloudLibrary/pcl#2578]
* Operating System and version: Windows10
* Compiler: VS2017
* PCL Version:PCL1.8.1

I am a  beginner in PCL. There is a small probelm confused me a lot. I am studying the pairwise_incremental_registration tutorial, I download the code from this link http://pointclouds.org/documentation/tutorials/pairwise_incremental_registration.php
 and compiled it sucessfully. when I run it in the command prompt, frist it shows that the picure is loaded, then I press  q to continue the registration. After this , it shows that something wrong in the VoxelGrid and NormalEstimation.  It says that input is empty, so the ICP process is failure.
![image](https://user-images.githubusercontent.com/43948166/47292318-2f4f3480-d639-11e8-86aa-dbff3adcb5ec.png)

1.input the commad:  pairwise_incremental_registration.exe capture0001.pcd capture0002.pcd capture0003.pcd capture0004.pcd capture0005.pcd
![image](https://user-images.githubusercontent.com/43948166/47292597-109d6d80-d63a-11e8-8997-5d7732ef334e.png)
2.press  q to continue the registration
![image](https://user-images.githubusercontent.com/43948166/47292621-290d8800-d63a-11e8-9c57-91e39cfaea60.png)

I change the .pcd and the parameter of leafsize, but it is the same mistake.
so I am wondering which step is wrong?

**Comment by mvieth** [comment]
Sorry that you did not get an earlier answer. I am not able to reproduce your problem. The error in VoxelGrid::applyFilter is the main issue, everything after that is caused by that. That can only appear if the VoxelGrid is instructed to additionally filter by a field ([see here](https://github.com/PointCloudLibrary/pcl/blob/39732f5a7c8455ed51fd0f6278d8b25322a68dd9/filters/include/pcl/filters/impl/voxel_grid.hpp#L274)). That is done via [setFilterFieldName](https://github.com/PointCloudLibrary/pcl/blob/39732f5a7c8455ed51fd0f6278d8b25322a68dd9/filters/include/pcl/filters/voxel_grid.h#L393), but this function is called nowhere in the tutorial. Is it possible that you modified the code?
I am going to close this issue. If still have this problem, feel free to comment here/reopen this issue/open a new issue.
