### ISSUE TITLE
Normal estimation / moving sensor origin

### ISSUE THREAD

**Issue by Jaykob** [PointCloudLibrary/pcl#2723]
Hi,
I successfully built PCL for iOS and I'm using it with the point cloud generated by the ARKit.
The results are really promising, however I came across a problem with inconsistent normal orientations in the context of Poisson reconstruction.

As far as I can tell, the PCL currently doesn't really support storing the position of a moving sensor, in my case the iPhone's position obtained through ARKit. This seems odd, as the Kinect also provides its position, right?
The motivation for storing and using the sensor's position is that it would allow to easily estimate a consistent normal orientation. So before I start from scratch, I'd like to ask if there's something that I missed or if you can give me some hints on where to start? It seems to me that this is a basic feature which others probably stumbled upon ages before me ;-)

**Comment by kunaltyagi** [comment]
> PCL currently doesn't really support storing the position of a moving sensor,

That's false. It has been in PCL for years IIRC.

Please see `sensor_origin_` and `sensor_orientation_` in class [`PointCloud`](https://pointclouds.org/documentation/classpcl_1_1_point_cloud.html)

**Comment by Jaykob** [comment]
And how would you store a moving sensor in a single Vector4f object? 
I’m talking about a sensor which is moving during the acquisition of a point cloud ;-)

**Comment by kunaltyagi** [comment]
You can use a global frame of reference, such as the initial pose (aka frame 1). Each subsequent cloud has it's pose computed with respect to the original frame.

This is quite common in SLAM implementations, where there's another sequence of poses, which contain the deviation of the sensor pose (stored with point cloud) from ground truth. In post processing, these 2 sequences are joined together.

In order to integrate global information such as GPS, the coordinates of initial pose are all that's required.

> pose of a sensor which is moving during the acquisition of a point cloud

The core assumption is that the sensor acquires the point cloud instantaneously. If that's false, it opens up floodgates to a host of other problems. If that's also your assumption, then estimating the sensor pose based on environment data is an active area of research and not a solved problem by any measure, though a lot of good approaches exist (beyond the scope of PCL), but most of them adhere to the technique above.

**Comment by Jaykob** [comment]
Thanks for your information @kunaltyagi!
Indeed, my work is related to SLAM.
I just discovered the offset parameter and the hint at the tar files for storing these multiple PCDs. I guess I'm on the right track?
Is there already something similar for writing or would I have to implement the creation of such a tar file consisting of multiple PCDs?

**Comment by kunaltyagi** [comment]
> Is there already something similar for writing or would I have to implement the creation of such a tar file consisting of multiple PCDs?

I don't know about this. Please use StackOverflow or Discord to capture a larger community for questions like this
