### ISSUE TITLE
Removing deprecated methods changed behavior

### ISSUE THREAD

**Issue by abellgithub** [PointCloudLibrary/pcl#2724]
## Your Environment

* Operating System and version: OSX
* Compiler: Clang
* PCL Version: 1.9

## Context

Commit 16d3a26d9fbd890beb87bbeab8b0d39936ec2837 broke existing behavior of 1.8.  IterativeClosestPoint::setInputCloud() was removed.  It had been marked as deprecated.  But since setInputCloud() exists in PCLBase, a base class of IterativeClosestPoint, code continued to compile and run with no warnings after IterativeClosestPoint::setInputCloud() was removed.  This is bad.

## Expected Behavior

Removing a deprecated function should cause code using the deprecated function not to build.

## Code to Reproduce

The code still builds without warning -- it just runs improperly.

## Possible Solution

Replace setInputCloud() and have it throw an exception.  Or it could be renamed.  Someone who knows more about the code base would have to decide such things.

**Comment by taketwo** [comment]
Thanks for bringing this up. I agree that we have a problem here.

The `setInputCloud()` method in `Registration` (and all its derived classes) has been deprecated in favor of `setInputSource()` many years ago, in pre-Github times. As @abellgithub highlighted, this method is a part of the base PCL interface and therefore can not be removed. So I would actually challenge the decision to deprecate it. I think the right approach is to a) encourage usage of the consistently named pair of methods `setInputSource`/`setInputTarget`; b) discourage usage of `setInputCloud`; c) even though it's discouraged, let `setInputCloud` do the right thing (i.e. call `setInputSource` internally).

The point (a) is already addressed since throughout the library code base the recommended method is used. The point (b) is not present anymore after the aforementioned commit, so we need to reintroduce it. Similarly, (c) was removed and needs to be added back.

What I am not sure about is how strong the discouragement should be. Before it was a compiler deprecation warning. Currently some of the classes that derive from `Registration` still have `setInputCloud()` overrides that warn users with console output that they are deprecated: https://github.com/PointCloudLibrary/pcl/blob/223eecdae8dee15894e0b4085914aead211fd51e/registration/include/pcl/registration/correspondence_rejection_poly.h#L112-L118 We could go the latter way. However, given that (c) is in place, does this actually matter which method is used? If `setInputCloud` is equivalent to `setInputSource`, do we want to nag users that they should necessarily switch to `setInputSource`?

**Comment by taketwo** [comment]
@kunaltyagi why did you close this?

**Comment by kunaltyagi** [comment]
While the concern is valid and should be noted, we've not removed the member functions, just deprecated them. This would be an open issue if there was something to address.

Since there isn't anything actionable yet, I closed the issue. If needed, we can reopen it (for PCL 1.12 when the functions will be replaced) now or in future.

**Comment by taketwo** [comment]
> This would be an open issue if there was something to address.

Issue: user code that uses deprecated functions continues to compile without a warning and does the wrong thing.

> Since there isn't anything actionable yet

Item c) from my list is actionable provided there is an agreement between maintainers that this is the right thing to do.
