### ISSUE TITLE
PCL in Universal Windows Platform

### ISSUE THREAD

**Issue by kemangjaka** [PointCloudLibrary/pcl#2797]
Hi, all.
Is it possible to use Point Cloud Library in Universal Windows Platform Application?
I'm new to use UWP, sorry for the dumb question.

**Comment by traversaro** [comment]
Late night I actually did the test of trying to compile the `pcl`'s [`vcpkg`](https://github.com/Microsoft/vcpkg) port using the `x64-uwp` [triplet](https://github.com/Microsoft/vcpkg/blob/master/docs/users/triplets.md) to see if that would work out of the box. 

It turns out that (at least on vcpkg) a few PCL dependencies do not compile out of the box on `uwp`, as of vcpkg commit https://github.com/Microsoft/vcpkg/commit/10d5e84b0135b07f9665418aebb42bc44ab2c7ca the list includes: 
* boost-filesystem
* boost-iostreams 
* hdf5
* liblzma 
* glew
* expat 

For a few of them patch for compiling with uwp seems to be available even if not integrated in the released version (see https://github.com/boostorg/filesystem/pull/18 and https://github.com/boostorg/filesystem/pull/19 for `boost-filesystem`). I guess you could patch also the other projects to add `uwp` support, but it is probably a non-trivial amount of work.

**Comment by kemangjaka** [comment]
Thank you so much for your response.
