### ISSUE TITLE
A question about 3D reconstruction

### ISSUE THREAD

**Issue by PabloLIborra** [PointCloudLibrary/pcl#2872]
Hi, I comment on my question. 

I have to do a final career project, which I have oriented to 3D reconstruction with semantic segmentation. After several guidelines and processes, I have reached the point where I have to get a reconstruction of an image of depth and an RGB, and then I will have to get the reconstruction done live. It should be noted that I am using the HTC Vive Pro, taking advantage of its front cameras, but I'm thinking of switching to another camera for the quality of these. 

After reading a lot of time, I thought about using the function "pcl :: PointCloudDepthAndRGBtoXYZRGBA" for the reconstruction using the depth image and the RGB, but I have some doubts about how to get the parameters that it asks for: 

```cpp
Const PointCloud <Intensity> & depth 
Const PointCloud <RGB> & image 
```

These are two of the paradores that he asks, but I have no idea how to get those variables through my images. I can say that the images I keep in cv :: Mat with imread. Do you know how to get those parameters from the images? As much as I read and look for information, I do not find anything. 

Subsequently, I will have to do the reconstruction live, some idea that I should use the PCL to get to that point? (from this moment I have not read, that's what I get once I get to solve the other problem) 

Thank you so much and Regards.

I´m using PCL version 1.9.1. I installed with the "allInOne".

*Maintainer Edit:* code formatting

**Comment by SergioRAgostinho** [comment]
The `Intensity` type is just a single float (32bits). Which means the `depth` needs to be an organized (with proper  width and heigh) point cloud of float values. Basically a single channel float image. It should be fairly straightforward to copy contents from a `cv::Mat` to a `PointCloud<Intensity>` and I suspect that with some luck you can do everything with a `std::copy` as long as the destination container is properly initialized.

For the `RGB` case things are slightly different because of the multiple color channels, but the same concepts apply. The point cloud needs to be organized and each `RGB` point is represented by a `uint32_t` with the following layout `a|r|g|b`, each 8 bits. Your conversion function might be a little more involved because of the variety of color formats OpenCV supports but I assume [`cvtColor`](https://docs.opencv.org/3.4.5/d8/d01/group__imgproc__color__conversions.html#ga397ae87e1288a81d2363b61574eb8cab) might help getting things closer to what you need.

**Comment by taketwo** [comment]
I hope Sergio answered your question. Please re-open if you have any follow-ups.
