### ISSUE TITLE
catkin_make with pcl error

### ISSUE THREAD

**Issue by crankler** [PointCloudLibrary/pcl#3104]
I use ubuntu 16.04 and pcl version is pcl-1.9，
when I use catkin_make with my ros package,
there show error:

> In file included from /usr/local/include/pcl-1.9/pcl/pcl_macros.h:39:0,
                 from /usr/local/include/pcl-1.9/pcl/PCLHeader.h:10,
                 from /usr/local/include/pcl-1.9/pcl/point_cloud.h:47,
/usr/local/include/pcl-1.9/pcl/pcl_config.h:7:4: error: #error PCL requires C++14 or above
   #error PCL requires C++14 or above
    ^
In file included from /usr/local/include/pcl-1.9/pcl/console/print.h:44:0,
                 from /usr/local/include/pcl-1.9/pcl/conversions.h:53,
                 from /opt/ros/kinetic/include/pcl_conversions/pcl_conversions.h:44,
/usr/local/include/pcl-1.9/pcl/pcl_config.h:7:4: error: #error PCL requires C++14 or above
   #error PCL requires C++14 or above
In file included from /usr/local/include/pcl-1.9/pcl/io/pcd_io.h:43:0,
                 from /opt/ros/kinetic/include/pcl_conversions/pcl_conversions.h:70,
/usr/local/include/pcl-1.9/pcl/io/file_io.h:235:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
   std::enable_if_t<std::is_floating_point<Type>::value>
/usr/local/include/pcl-1.9/pcl/io/file_io.h:266:18: error: expected initializer before ‘<’ token
   copyValueString<int8_t> (const pcl::PCLPointCloud2 &cloud,
/usr/local/include/pcl-1.9/pcl/io/file_io.h:280:18: error: expected initializer before ‘<’ token
   copyValueString<uint8_t> (const pcl::PCLPointCloud2 &cloud,
                  ^
/usr/local/include/pcl-1.9/pcl/io/file_io.h:304:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
   std::enable_if_t<std::is_floating_point<Type>::value, bool>
        ^
/usr/local/include/pcl-1.9/pcl/io/file_io.h:317:8: error: ‘enable_if_t’ in namespace ‘std’ does not name a template type
   std::enable_if_t<std::is_integral<Type>::value, bool>

> 

my cmakelist as follow:

> find_package(PCL 1.9 REQUIRED)

catkin_package(
  INCLUDE_DIRS
  ${EIGEN3_INCLUDE_DIR}
  ${PCL_INCLUDE_DIRS}
  CATKIN_DEPENDS
  roscpp
)

include_directories(
  include ${catkin_INCLUDE_DIRS}
  include 
    ${catkin_INCLUDE_DIRS}
  ${EIGEN3_INCLUDE_DIR}
  ${PCL_INCLUDE_DIRS}
)

my cpp file as follow:

> #include<ros/ros.h>
#include<pcl/point_cloud.h>
#include<pcl_conversions/pcl_conversions.h>
#include<sensor_msgs/PointCloud2.h>
#include<pcl/io/pcd_io.h>
int main (int argc, char **argv)
{
  ros::init (argc, argv, "loadpcd");
  ros::NodeHandle nh;
  ros::Publisher pcl_pub = nh.advertise<sensor_msgs::PointCloud2> ("pcl_load", 10);
  pcl::PointCloud<pcl::PointXYZ> cloud;
  sensor_msgs::PointCloud2 output;
  pcl::io::loadPCDFile ("/home/0-sim_bag/loam.pcd", cloud);
  //Convert the cloud to ROS message
  pcl::toROSMsg(cloud, output);
  output.header.frame_id = "odom";//this has been done in order to be able to visualize our PointCloud2 message on the RViz visualizer
  ros::Rate loop_rate(1);
  while (ros::ok())
  {
    pcl_pub.publish(output);
    ros::spinOnce();
    loop_rate.sleep();
  }
  return 0;
}

> 
So can you tell me how to solve this problem ? Thank you !

**Comment by SergioRAgostinho** [comment]
Add these two line at the top of your CMake file after defining the project. Hopefully it will compile.
```cmake
# Set target C++ standard and required compiler features
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```

Alternatively, use pcl 1.9.1 instead of the development version from GitHub.

**Comment by crankler** [comment]
Yes, I try this way yesterday, but there stiil have error in catkin_make, just as follow:

> CMakeFiles/loadpcd. Dir/SRC/loadpcd. CPP. O: in function 'photo: : PCDReader: : PCDReader ()' :
Loadpcd.cpp :(.text._zn3pcl9pcdreaderc2ev [_ZN3pcl9PCDReaderC5Ev]+0x19) : undefined reference to 'vtable for PCL ::PCDReader'
CMakeFiles/loadpcd. Dir/SRC/loadpcd. CPP. O: in function 'photo: : PCDReader: : ~ PCDReader ()' :
Loadpcd.cpp :(.text._zn3pcl9pcdreaderd2ev [_ZN3pcl9PCDReaderD5Ev]+0xd) : undefined reference to 'vtable for PCL ::PCDReader'
CMakeFiles/loadpcd. Dir/SRC/loadpcd. CPP. O: in function 'void PCLS: : detail: : FieldMapper < photo: : PointXYZ > : : operator () < photo: : fields: : x > ()' :
Loadpcd. CPP: (. Text. _ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1xEEEvv [_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1xEEEvv] + 0 x1b2) : Print (PCL ::console::print(PCL ::console::VERBOSITY_LEVEL, char const*... An undefined reference
CMakeFiles/loadpcd. Dir/SRC/loadpcd. CPP. O: in function 'void PCLS: : detail: : FieldMapper < photo: : PointXYZ > : : operator () < photo: : fields: : y > ()' :
Loadpcd. CPP: (. Text. _ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1yEEEvv [_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1yEEEvv] + 0 x1b2) : Print (PCL ::console::print(PCL ::console::VERBOSITY_LEVEL, char const*... An undefined reference
CMakeFiles/loadpcd. Dir/SRC/loadpcd. CPP. O: in function 'void PCLS: : detail: : FieldMapper < photo: : PointXYZ > : : operator () < photo: : fields: : z > ()' :
Loadpcd. CPP: (. Text. _ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1zEEEvv [_ZN3pcl6detail11FieldMapperINS_8PointXYZEEclINS_6fields1zEEEvv] + 0 x1b2) : Print (PCL ::console::print(PCL ::console::VERBOSITY_LEVEL, char const*... An undefined reference
Collect2: error: ld returned 1 exit status

**Comment by SergioRAgostinho** [comment]
In your CMake snippet I see no command linking against `${PCL_LIBRARIES}`. That would cause the compile issues you're seeing here.

**Comment by crankler** [comment]
OK, I add this and it worked ! 
Thank you!

**Comment by anujgpatil** [comment]
@SergioRAgostinho I have the linking commands in my CMakeLists.txt but still getting **undefined reference to** errors. Any inputs?

**Comment by taketwo** [comment]
Please follow our guidelines and post such support questions on Stack Overflow. Make sure to provide more detailed information as it is virtually impossible to give any meaningful suggestions to a request like "Stuff does not work -- help!"

**Comment by parkerlreed** [comment]
@taketwo Is that a joke? Stack Overflow is the worst place for quick questions. Hell I can't even answer questions because of the bullcrap points system. I have to ask questions to be able to answer? That's freaking stupid.

@SergioRAgostinho Thanks for the solution.

**Comment by anujgpatil** [comment]
Compared to StackOverflow, https://gitter.im/PointCloudLibrary/pcl is a good forum to get PCL related "help" @parkerlreed 
:)

**Comment by chrisfernam2** [comment]
Hey guys could you please help me with this error. 

I get this same error PCL requires c++14 or above error.
I tried adding to the CMakeLists.txt found in the sick_scan/, right below cmake_minimum_required(VERSION2.8.3) but i still face the same error.

# Set target C++ standard and required compiler features
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
![Capture](https://user-images.githubusercontent.com/40682788/83445723-591a3100-a402-11ea-9a41-e2ffb827599f.PNG)

Here is the content of my /sick_scan/CMakeLists.txt file, which is exactly the same content found in the sick_scan github page under the master branch:


I would greatly appreciate your assistance!



####################################################
# CMakeLists.txt for project sick_scan
#
#
####################################################
cmake_minimum_required(VERSION 2.8.3)


macro(use_cxx11)
    if (CMAKE_VERSION VERSION_LESS "3.1")
        if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++11")
        endif ()
    else ()
        set(CMAKE_CXX_STANDARD 11)
    endif ()
endmacro(use_cxx11)

#set(CMAKE_BUILD_TYPE Debug) #uncomment to activate debug mode for lib_sick as well
#set(CMAKE_ENABLE_EXPORTS 1) #uncomment to activate debug mode for lib_sick as well
# https://cmake.org/cmake/help/v3.5/prop_tgt/ENABLE_EXPORTS.html
# set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++03")

# Switch on, if you use c11-specific commands
use_cxx11()

# set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
# set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wpedantic")

project(sick_scan)

# By uncommenting the following lines you can list all variable names ...
# --- CUT ---
# get_cmake_property(_variableNames VARIABLES)
# list (SORT _variableNames)
# foreach (_variableName ${_variableNames})
#	message(STATUS "${_variableName}=${${_variableName}}")
# endforeach()
# --- CUT ---

# For warning <catkin_workspace>/devel/include' should be placed in
# the devel space instead of the build space
# see: https://answers.ros.org/question/67244/qtcreator-with-catkin/


# message(${CMAKE_BINARY_DIR})

# set(CATKIN_DEVEL_PREFIX "${CMAKE_BINARY_DIR}/devel")
# set(CMAKE_PREFIX_PATH "${CMAKE_BINARY_DIR}/devel;/opt/ros/melodic")


find_package(catkin REQUIRED
        COMPONENTS
        roscpp
        sensor_msgs
        diagnostic_updater
        dynamic_reconfigure
        geometry_msgs
        std_msgs
        sensor_msgs
        visualization_msgs
        message_generation
        pcl_conversions
        pcl_ros
        )


find_package(PkgConfig REQUIRED)

find_package(Boost REQUIRED COMPONENTS system)

generate_dynamic_reconfigure_options(
        cfg/SickScan.cfg
        cfg/tf_dyn.cfg
)

add_message_files(

        FILES
        SickImu.msg
        RadarObject.msg
        RadarPreHeaderDeviceBlock.msg
        RadarPreHeaderMeasurementParam1Block.msg
        RadarPreHeaderStatusBlock.msg
        RadarPreHeaderEncoderBlock.msg
        RadarPreHeader.msg
        RadarScan.msg
        Encoder.msg
)

generate_messages(
        DEPENDENCIES
        std_msgs
        geometry_msgs
        sensor_msgs
)

catkin_package(
        DEPENDS Boost
        CATKIN_DEPENDS message_runtime roscpp sensor_msgs diagnostic_updater dynamic_reconfigure
        LIBRARIES sick_scan_lib
        INCLUDE_DIRS include)

include_directories(include include/tinyxml ${catkin_INCLUDE_DIRS} include/sick_scan)

add_library(sick_scan_lib
        driver/src/dataDumper.cpp
        driver/src/sick_scan_common.cpp
        driver/src/abstract_parser.cpp
        driver/src/tcp/tcp.cpp
        driver/src/tcp/Mutex.cpp
        driver/src/tcp/SickThread.cpp
        driver/src/tcp/errorhandler.cpp
        driver/src/tcp/toolbox.cpp
        driver/src/tcp/Time.cpp
        driver/src/tcp/colaa.cpp
        driver/src/tcp/colab.cpp
        driver/src/binScanf.cpp
        driver/src/sick_scan_common_tcp.cpp
        driver/src/sick_generic_radar.cpp
        driver/src/sick_generic_imu.cpp
        driver/src/sick_generic_parser.cpp
        driver/src/sick_scan_common_nw.cpp
        include/sick_scan/sick_scan_config_internal.h
        driver/src/sick_scan_config_internal.cpp
        include/sick_scan/softwarePLL.h
        driver/src/softwarePLL.cpp
        )

add_dependencies(sick_scan_lib ${PROJECT_NAME}_gencfg ${catkin_EXPORTED_TARGETS} ${${PROJECT_NAME}_EXPORTED_TARGETS})

target_link_libraries(sick_scan_lib
        ${catkin_LIBRARIES})

add_executable(sick_generic_caller
        driver/src/sick_generic_laser.cpp
        driver/src/sick_generic_caller.cpp
        )

#
#  radar_object_marker (receives radar msg. and publishes marker array for rviz or similar
#
add_executable(radar_object_marker
        tools/radar_object_marker/src/radar_object_marker.cpp
        tools/pcl_converter/src/gnuplotPaletteReader.cpp
        include/radar_object_marker/radar_object_marker.h)
target_link_libraries(radar_object_marker sick_scan_lib)
#
#
#


add_executable(pcl_converter tools/pcl_converter/src/pcl_converter.cpp tools/pcl_converter/src/gnuplotPaletteReader.cpp)

target_link_libraries(pcl_converter
        ${catkin_LIBRARIES}
        ${roslib_LIBRARIES}
        ${PCL_LIBRARIES})


# add_executable( pcl_find_plane tools/pcl_converter/src/pcl_find_plane.cpp)
# target_link_libraries(pcl_find_plane ${catkin_LIBRARIES})


target_link_libraries(sick_generic_caller sick_scan_lib)

add_executable(sick_scan_test
        test/src/sick_scan_test.cpp
        driver/src/tinyxml/tinystr.cpp
        driver/src/tinyxml/tinyxml.cpp
        driver/src/tinyxml/tinyxmlerror.cpp
        driver/src/tinyxml/tinyxmlparser.cpp
        )
target_link_libraries(sick_scan_test
        ${catkin_LIBRARIES}
        ${roslib_LIBRARIES}
        sick_scan_lib)

#
#  Sensor alignment tool
#
#  currently disabled for trusty support
# add_executable(sensor_alignment
#		tools/sensor_alignment/sensor_alignment_tf_dyn.cpp
#		)
#
# target_link_libraries(sensor_alignment
#		${catkin_LIBRARIES}
#		)
# add_dependencies(sensor_alignment ${PROJECT_NAME}_gencfg)

# target_link_libraries(${PROJECT_NAME}_pointcloud2_refresh
#		${catkin_LIBRARIES}
#	)


# Destinations:
# LIB for library
# BIN for Binaries
# INCLUDE for Includes
# SHARE for config files, launch files etc.


install(TARGETS sick_scan_lib
        DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION})

install(
        TARGETS
        sick_generic_caller
        RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})

install(
        TARGETS
        sick_scan_test
        RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})


install(FILES include/${PROJECT_NAME}/abstract_parser.h
        include/${PROJECT_NAME}/sick_scan_common.h
        DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION})

install(DIRECTORY test/
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/test
        FILES_MATCHING PATTERN "*.xml"
        PATTERN "test/src" EXCLUDE)

install(DIRECTORY launch/
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/launch)

install(DIRECTORY meshes/
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/meshes)

install(DIRECTORY urdf/
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/urdf)

**Comment by SergioRAgostinho** [comment]
You're setting the standard to C++11 in your CMake file. PCL 1.10 requires C++14 as the minimum.

**Comment by chrisfernam2** [comment]
Hi Sergio. I actually added:
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

Right below the project(sick_scan) in my Sick_Scan/CMakeLists.txt and this change alone seemed to fix most of my issue. The compilation is almost succeeding 100%. Now I only face 2 small errors, both of which are relative the same.

Could you please assist me?
I added 2 screenshots of both of them. 
![Capture2](https://user-images.githubusercontent.com/40682788/83461498-c5565e00-a41d-11ea-9c2a-bed4364c8acc.PNG)
![Capture3](https://user-images.githubusercontent.com/40682788/83461500-c5eef480-a41d-11ea-9982-4fb40be9ff0a.PNG)

The compiler doesn't really know how to compare between the boost::system::error_code object and the integer itself; i'm just not too familiar with boost::system.

Care to elaborate if possible?

**Comment by chrisfernam2** [comment]
Actually got it to compile completely, it was a simple mistake in the sick_scan-provided sick_scan_common.cpp. Changed ec == 0 to: ec.value() == boost::system::errc::success. Thank you!
