### ISSUE TITLE
Ask a question: Is acceleration structure been reused between different feature estimation which are using same search surface. 

### ISSUE THREAD

**Issue by dogod621** [PointCloudLibrary/pcl#3148]
Hi,

Sorry for asking questions via git hub issue, but I cannot find related information...
For example: If I am doing normal estimation and another whatever estimation at same search surface, and I am using K-D tree as search method. Is the K-D tree been reused?

**Comment by taketwo** [comment]
Reuse is attainable, though not automatically. Have a look at these getter/setter in the base `Feature` class:

https://github.com/PointCloudLibrary/pcl/blob/a9e27d81de343a889c2f88320bb37381342d2a79/features/include/pcl/features/feature.h#L165-L173

After computing normals you can get the tree from there and pass it to another feature computation class. Note, however, that you need to pass exactly same input cloud pointer, otherwise the tree will be reinitialized:

https://github.com/PointCloudLibrary/pcl/blob/a9e27d81de343a889c2f88320bb37381342d2a79/features/include/pcl/features/impl/feature.hpp#L126-L127

**Comment by dogod621** [comment]
Thanks~
