### ISSUE TITLE
Slow performance principle component analysis

### ISSUE THREAD

**Issue by BingEdison** [PointCloudLibrary/pcl#3285]
Howdy folks was hopeful that someone could enlighten me as to why obtaining eigen vectors are so slow(seconds to minutes ) when using feature_extractor when calculating the nearest neighbor of 1000 points of my pointxyzInormal cloud , Changing the setAngleStep has helped but still has been a persistent bottleneck. Any solutions ideas , would be much appreciated.

Thanks in advance!
Eddy

**Comment by SergioRAgostinho** [comment]
I suspect no one can provide you with a good answer to this. Find a way to isolate and profile your code to discover the where the bottlenecks exist and why. If you suspect a given implementation is being inefficient, you are able to isolate the problem and you have an alternative proposal, then open an issue/PR and present your discoveries. As it is, the issue is just too vague. 

Here's a good example on how to expose a problem and maximize your chances of getting meaningful feedback. #2403
