### ISSUE TITLE
Inaccurate results with gpu octree search example

### ISSUE THREAD

**Issue by clams-casino** [PointCloudLibrary/pcl#3583]
Getting inaccurate results from the octree radius search example in gpu/examples/octree/src/octree_search.cpp

## Your Environment
* Operating System and version: Ubuntu 16.04 LTS
* Compiler: gcc 5.4.0, nvcc and CUDA toolkit version 10.2
* PCL Version: 1.9.1
* GPU: Quadro T2000

Also tested on an Nvidia Jetson TX2
* Operating System and version: Ubuntu 18.04 LTS
* Compiler: gcc 7.4.0, nvcc and CUDA toolkit version 10.0
* PCL Version: 1.9.1

## Context
Trying do a radius search with multiple query points in a pointcloud on the gpu

## Expected Behavior
Expect points within a circle of the query points to be found in the radius search

## Current Behavior
Radius search seems to just find an irregular block of points around the query points. I tried the CPU octree radius search and it works as expected. 

## Code to Reproduce
https://github.com/PointCloudLibrary/pcl/blob/master/gpu/examples/octree/src/octree_search.cpp

**Comment by kunaltyagi** [comment]
> Code to Reproduce

Sends example link...... That's a power move 😛 

Thanks @clams-casino for bringing this to our notice. The GPU modules have suffered a lack of supervision and this might be a result of that.

**Comment by Cazadorro** [comment]
@kunaltyagi  While trying to look into this I had a few questions. Why is the PIMPL method defined with `void*` pointers instead of forward declared types here? 
https://github.com/PointCloudLibrary/pcl/blob/master/gpu/octree/include/pcl/gpu/octree/octree.hpp 

If that line instead referenced what the actually pointer type was, It would have saved me a few minutes of hunting down what the actual type of the pointer was supposed to be, and I don't see the advantage of it being a void pointer, as far as I can tell, it will only ever be one type.   It makes the code obnoxious to read. 


IIUC Looks like the radius code is located here:

https://github.com/PointCloudLibrary/pcl/blob/23690b4101b0a048134895bd9472c0bcdaef44b8/gpu/octree/src/cuda/radius_search.cu

though I'm not sure how it works from a glance. 

found this as well

https://github.com/PointCloudLibrary/pcl/blob/23690b4101b0a048134895bd9472c0bcdaef44b8/gpu/octree/src/cuda/octree_builder.cu

appears to be what build() is calling, 

I believe these should be the only two places were nontrivial GPU functionality is called (not necessarily where the bug is)?

Additionally, and I may be mis-interpreting the guidelines, but shouldn't `internal.hpp` inside of pcl/gpu/octree/src/ be <internal.hpp> instead of "internal.hpp" when included in the subdirectories of pcl/gpu/octree/src/?  That threw me off too, because it clearly wasn't from the same directory, and could potentially mimic other internal.hpp so I couldn't use it as a source for finding the implementation of this octree stuff.

**Comment by taketwo** [comment]
> Why is the PIMPL method defined with `void*` pointers instead of forward declared types here?

Like @kunaltyagi said, this module suffered a lack of supervision. Furthermore, it was added in pre-peer-review times, so unconventional decisions (e.g. using `void*` in PIMPL) haven't been challenged.

**Comment by Cazadorro** [comment]
@taketwo  Thanks, that makes sense.

This SemStorage code is a big code smell

            struct SmemStorage
            {                             
                volatile int per_warp_buffer[WARPS_COUNT];
                volatile int cta_buffer[CTA_SIZE];
            };                                
        };

        __shared__ KernelPolicy::SmemStorage storage;

The use of volatile here is suspect, there are cases where it makes sense, but it is very rare today in CUDA to need that kind of construct, typically synchronization is all that is needed.   

It is used purely here:

__device__ __forceinline__ void processLeaf(int leaf)
            {   
                int mask = __ballot_sync(0xFFFFFFFF, leaf != -1);            

                while(mask)
                {                
                    unsigned int laneId = Warp::laneId();
                    unsigned int warpId = Warp::id();            

                    int active_lane = __ffs(mask) - 1; //[0..31]

                    mask &= ~(1 << active_lane);              

                    //broadcast active_found_count                                
                    if (active_lane == laneId)                
                        storage.per_warp_buffer[warpId] = found_count;                                            
                    int active_found_count = storage.per_warp_buffer[warpId];

                    int node_idx = leaf & ~KernelPolicy::CHECK_FLAG;

                    //broadcast beg
                    if (active_lane == laneId)
                        storage.per_warp_buffer[warpId] = batch.octree.begs[node_idx];                    
                    int beg = storage.per_warp_buffer[warpId];

                    //broadcast end
                    if (active_lane == laneId)
                        storage.per_warp_buffer[warpId] = batch.octree.ends[node_idx];
                    int end = storage.per_warp_buffer[warpId];

                    //broadcast active_query_index
                    if (active_lane == laneId)
                        storage.per_warp_buffer[warpId] = query_index;
                    int active_query_index = storage.per_warp_buffer[warpId];

                    int length = end - beg;

                    int *out = batch.output + active_query_index * batch.max_results + active_found_count;                    
                    int length_left = batch.max_results - active_found_count;

                    int test = __any_sync(0xFFFFFFFF, active_lane == laneId && (leaf & KernelPolicy::CHECK_FLAG));

                    if (test)
                    {                                        
                        float3 active_query;

                        //broadcast warp_query
                        if (active_lane == laneId)
                            storage.per_warp_buffer[warpId] = __float_as_int(query.x);
                        active_query.x = __int_as_float(storage.per_warp_buffer[warpId]);

                        if (active_lane == laneId)
                            storage.per_warp_buffer[warpId] = __float_as_int(query.y);
                        active_query.y = __int_as_float(storage.per_warp_buffer[warpId]);

                        if (active_lane == laneId)
                            storage.per_warp_buffer[warpId] = __float_as_int(query.z);
                        active_query.z = __int_as_float(storage.per_warp_buffer[warpId]);                            

                        float radius2 = batch.bradcastRadius2((float*)&storage.per_warp_buffer[warpId], (active_lane == laneId), radius);                            

                        length = TestWarpKernel(beg, active_query, radius2, length, out, length_left);                    
                    }
                    else
                    {                            
                        length = min(length, length_left);                        
                        Warp::copy(batch.indices + beg, batch.indices + beg + length, out);
                    }

                    if (active_lane == laneId)
                        found_count += length;
                }            
            }    

as a way to check on the state of all warps within the current block, but with out synchronization anywhere, I don't see how this is happening reliably.  If that isn't the goal, I don't see why there needs to be a value in share memory taken put by warps, and is probably a performance concern in the first place. 

The fact that this code was made in 2011 makes me think that maybe there are some GPUs out there where it works correctly, so maybe we could get a better picture of what is going on with more testing from people with different systems. 

I'm not sure if I'll have a chance to look at this any time soon or have enough time to fix this.  It will take me a while to be in a place where I can build the code myself and where I can understand all the pieces that go into it.  Right now I'm seeing more questionable decisions, dead code and large commented out sections that are uncharacteristic for the rest of the code base, so there's likely a lot of guideline stuff that will need to be fixed along side as well.

**Comment by haritha-j** [comment]
@clams-casino I ran across the same problem, a quick hack I can recommend if your use case requires the radius to be the same for all queries, is to use the radiusSearch() method that takes in a single float as the radius rather than a pcl::gpu::Octree::Radiuses object. This method seems to produce the exact same results as the CPU method. Even in the example you linked, the author could've gone with this method, since all queries search within the same radius.
