### ISSUE TITLE
Is this library actually useful?

### ISSUE THREAD

**Issue by Passworteingeben** [PointCloudLibrary/pcl#3596]
Hello,

I have tried to get the examples of the recogntion pipeline from Correspondence Grouping

http://pointclouds.org/documentation/tutorials/correspondence_grouping.php#correspondence-grouping

up and running but apparently failed miserably.

To put it this way, the whole method takes way to long, even when not using hough and the results are barely or absolutely not correct, even on the original example with the milk boxes.

The ICP example I also couldn't get to run on the milk box example, possibly because it is an unordered point cloud, in which case it would be nice if somebody put a note on it somewhere.

So far this library is not really useable and although I admit that I'm not proficient with C++, it is absolutely unclear how any of these feature functions actually compute stuff.

The documentation is essentially non existent, unless the parameters are self explanatory, there are no actual indications on what they do or possible options that somebody has. (even in the docs)

I would appreciate it if this project would actually take an example from the python community or if somebody could send me an actually working code with this library that uses it for recognition.

**Comment by kunaltyagi** [comment]
> tried to get ... up and running ... apparently failed miserably

Please provide more details. This is not sufficient. Which PCL version? Which flags used for compilation?

> the whole method takes way to long

What's the time taken? If you could use perf to point where the issue lies, the maintainers can look into it.

> the results are barely or absolutely not correct

Which one is it?

> if somebody put a note on it somewhere

This is open source. Feel free to create a PR to update the tutorial.

> it is absolutely unclear how any of these feature functions actually compute stuff

Again, this is open source. Feel free to dig in the code to satisfy yourself, and if you feel like, add to the documentation to improve it.

> The documentation is essentially non existent

This is work done by volunteers, so documentation is patchy. We'd love if you could help

> there are no actual indications on what they do or possible options that somebody has. (even in the docs)

Please explain more. Most of the options are self-explanatory. Which ones are stumping you?

> if somebody could send me an actually working code with this library that uses it for recognition

Not a homework service. Sorry.

> this project would actually take an example from the python community

In what sense? You have said a lot, but conveyed very little of substance.

**Comment by rimmartin** [comment]
Yes.
