### ISSUE TITLE
Follow up better type on pcl::index_t

### ISSUE THREAD

**Issue by jingyangcarl** [PointCloudLibrary/pcl#3682]
Hi, as described in PR #3651, and issue #3351, it's recommended to create a new indices type, say pcl::index_t, instead of the plain container std::vector<int>, std::vector<std::uint32_t>, or other types.

When I went through here: 
https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/include/pcl/conversions.h#L191
https://github.com/PointCloudLibrary/pcl/blob/4316e111380fe5ffef80fdec0a2228546ebcae65/common/include/pcl/conversions.h#L208

The iterator here is defined as std::uint32_t. I think if we want to have a better indices type, should the iterator here be modified to some flexible type as well?

@kunaltyagi @taketwo

**Comment by kunaltyagi** [comment]
> should the iterator here be modified to some flexible type as well

Technically, indices are not needed for input in IO. They are mostly for algorithms. We can use `std::size_t` for input and output.

Some points to consider:
* std::size_t *technically* fails for multi-dimension data (each dimension's max index_type multiplied together can be more than max uint64)
* common-use imaging sensors aren't even at 2^16 per dimension, so for images, 2^32 is ok (since the product for 2D will be 2^64, our max index size)
* Beyond 2^64 should not be the topic right now. We'll cross the bridge when we have to (probably never)
