### ISSUE TITLE
[Registration] NDT implementation flaws

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3734]
Hey, this merged PR is not good.
I noticed this problem because ndt didn't work well  in the latest version.

First,the following line is redundant and confusing.
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt_2d.hpp#L478

```
double cos_angle = 0.5 * (transformation_delta.coeff (0, 0) + transformation_delta.coeff (1, 1) + transformation_delta.coeff (2, 2) - 1);
```

the following code is enough.

```
double cos_angle = 0.5 * (transformation_delta.coeff (0, 0) + transformation_delta.coeff (1, 1));
```

or

```
double cos_angle = transformation_delta.coeff (0, 0);
```

Secondly, it is wrong to use `cos_angle`  in 3d like as 2d.

https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L153

```
double cos_angle = 0.5 * (transformation_.coeff (0, 0) + transformation_.coeff (1, 1) + transformation_.coeff (2, 2) - 1);
```

_Originally posted by @rsasaki0109 in https://github.com/PointCloudLibrary/pcl/pull/1724#issuecomment-597978365_

**Comment by kunaltyagi** [comment]
@rsasaki0109 Could you please give some examples to show the flaws in the existing implementation?

If possible, would you like to create a PR?

**Comment by rsasaki0109** [comment]
It is a mathematical problem.
the 2d homogeneous transformation matrix H(x,y,θ) in 2d is as below.
![ndt1](https://user-images.githubusercontent.com/18298605/76486273-3a8b4600-6462-11ea-81f9-0603db420df0.png)

So, using the change of `cos_ang` in ndt_2d.hpp is correct for the convergence judgment of scan-matching algorithms because `cos_ang` is

![ndt2](https://user-images.githubusercontent.com/18298605/76486285-437c1780-6462-11ea-9bd0-dfb7977f3350.png)

But in 3d, H(p) is,using the Euler sequence z-y-x,

![ndt3](https://user-images.githubusercontent.com/18298605/76486301-50990680-6462-11ea-8cc9-7d69a0b74f78.png)

where ci = cosφi and si = sinφi.
(reference:page 63 of [thesis about ndt in reserchgate.](https://www.researchgate.net/publication/229213868_The_Three-Dimensional_Normal-Distributions_Transform_---_an_Efficient_Representation_for_Registration_Surface_Analysis_and_Loop_Detection))

So, `cos_ang` in ndt.hpp is nonsense because `cos_ang` is

![ndt4](https://user-images.githubusercontent.com/18298605/76486310-58f14180-6462-11ea-8aec-7d010c1f2050.png)

**Comment by kunaltyagi** [comment]
Thanks for the explanation. Would you mind creating a PR? It might take lesser effort for you 😄

**Comment by rsasaki0109** [comment]
I'm sorry, I misunderstood.

Any rotation R(θ) in three-dimensional space can be represented by a rotation axis r and a rotation angle θ.
And trace{R(θ)} is 2cosθ + 1.
In the convergence judgment of scan-matching algorithms, this theta is considered.
I think that there is an another cause that ndt-scanmatching don't work well in my environment.
I will let you know the details once I find out.

**Comment by kunaltyagi** [comment]
> another cause that ndt-scanmatching don't work well in my environment

Sure. Please share your findings with us once you debug it, even if the issue wasn't in PCL 😄
