### ISSUE TITLE
[CI] The deprecation list is showing weird things

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3825]
The deprecation list is showing weird things on https://pointcloudlibrary.github.io/documentation/deprecated.html but not on http://docs.pointclouds.org/trunk/deprecated.html.

EDIT: and CI is reporting this
```
/__w/1/s/common/include/pcl/common/io.h:82: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:111: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:121: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/common/io.h:335: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/common/include/pcl/point_cloud.h:142: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
/__w/1/s/segmentation/include/pcl/segmentation/supervoxel_clustering.h:291: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
```
and more new ones

_Originally posted by @aPonza in https://github.com/PointCloudLibrary/pcl/pull/3808#issuecomment-605535873_

**Comment by aPonza** [comment]
> But that PR #3701 didn't touch the same lines I did (in the header file).

I explained myself poorly: all of the `warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)` were gone after that #3701 which means some new ones were introduced. Some of these (if not all) coincide with the new `PCL_DEPRECATED`. This basically only means I have to hurry up if I want to see less new warnings in Documentation: the faster I fix all of them and turn on `-Werror`, the faster no new ones will arise.

**Comment by kunaltyagi** [comment]
> all of the ... were gone after

Gotcha. Could you also please tell me (if and when possible) how not to give rise these warnings 😅 ?

**Comment by aPonza** [comment]
I'll have to see for myself, these ones are weird as no `;` can be used since it's in the middle of a declaration. I'd have hoped doxygen-clang wouldn't show them, but I'm still waiting on a definitive answer there. Right now at least making it evident they are new should be doable (turn on warning as error once all of the warnings are gone).

**Comment by aPonza** [comment]
So the error itself is because "." ends the period if [`JAVADOC_AUTOBRIEF`](http://www.doxygen.nl/manual/config.html#cfg_javadoc_autobrief)`= YES` so the solution is either to set it to `= NO` or escape the dot like `.\ ` (notice the trailing whitespace). In both cases the version number becomes "1 . 12" which is ugly and I think there is no solution to inserted whitespace since I found the unresolved https://github.com/doxygen/doxygen/issues/6154 bug report.

If you have any ideas for a nice display do tell me. PR ready soon-ish, I'm homogenizing deprecation warnings as well while at it.

**Comment by taketwo** [comment]
> version number becomes "1 . 12" which is ugly and I think there is no solution 

Think outside of the box! This can be fixed with a single `sed` invocation :)

**Comment by kunaltyagi** [comment]
> outside the box

We can use `1_1` instead of `1.1` 😆 . Too outside?

**Comment by aPonza** [comment]
> which is ugly

I mean...this was the argument for needing the point in the first place so...I guess...
