### ISSUE TITLE
[Windows CI] Compile only for x64 bit?

### ISSUE THREAD

**Issue by larshg** [PointCloudLibrary/pcl#3869]
Should we keep compiling for both x86 and x64 or can we remove x86, since Ubuntu/Mac versions only compile x64 as well?

**Comment by taketwo** [comment]
I'm keen on freeing up some resources on CI. That said, I'm not a Windows user and don't know how important/relevant x86 build is. Do people still use this stuff? Are there differences between x86/x64 that may lead to issues and need to be checked on CI? I don't recall having problems with one job but not the other (apart from x64 being red more often due to "out-of-memory" issues).

**Comment by SergioRAgostinho** [comment]
No issues from my side as well but I'm also unaware of the importance of the build.

**Comment by traversaro** [comment]
> Are there differences between x86/x64 that may lead to issues and need to be checked on CI

I personally do not use the Windows 32-bit a lot, but just to let you know testing at least on a 32-bit platform typically is useful to catch errors in memory alignment, that sometimes do not emerge in 64-bit platforms.

**Comment by larshg** [comment]
Continueing with both for now.
