### ISSUE TITLE
Update flann version to 1.8.4 (tested, available in Ubuntu LTS 16.04)

### ISSUE THREAD

**Issue by kunaltyagi** [PointCloudLibrary/pcl#3986]
**Describe the bug**

[Documentation](http://pointclouds.org/documentation/tutorials/compiling_pcl_posix.php) says flann version 1.7.1 is minimum required. The least tested version of flann on the CI is 1.8.4:
```sh
$ docker run --rm -it ubuntu:16.04 bash
$ apt update
$ apt search libflann
Sorting... Done
Full Text Search... Done
libflann-dev/xenial 1.8.4-4.1 amd64
  Fast Library for Approximate Nearest Neighbors - development

libflann1.8/xenial 1.8.4-4.1 amd64
  Fast Library for Approximate Nearest Neighbors - runtime
```

**Context**

#3983 shows that is not true and a compiler error occurs with 1.7.1

**Comment by SunBlack** [comment]
Issue is caused by this line:
https://github.com/PointCloudLibrary/pcl/blob/7d22c77c447c0d9fe1a36fe81e3e4abc1139a169/segmentation/include/pcl/segmentation/impl/unary_classifier.hpp#L44

I don't know when flann 1.7.1 was relased as the tags are tarting with 1.8.0, but this is the [commit](https://github.com/mariusmuja/flann/commit/5b5ebfba32a6845426e865a28ada77283629418b) which adds the required class.

Only thing: Do we really need this include? As we don't seems to use any instance of `CenterChooser` - so maybe just cleanup the includes before checking if we need to increase the required minimum version

**Comment by kunaltyagi** [comment]
I still think we should only support versions that are tested on the CI, one LTS minimum, one bleeding edge. Since 1.7.1 can't be found anyways, we should update minimum supported to 1.8.4

**Comment by SergioRAgostinho** [comment]
> Since 1.7.1 can't be found anyways, we should update minimum supported to 1.8.4

I'm okay with this.

**Comment by mvieth** [comment]
@kunaltyagi What is left to do here? We now [require flann 1.9.1](https://github.com/PointCloudLibrary/pcl/blob/007ac5746661e20b411b81c9baddd24c2505b038/CMakeLists.txt#L306), which [all current Ubuntu versions use](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=libflann-dev&searchon=names).
