### ISSUE TITLE
Autoware has potentially copied PCL's code for NDT without attribution

### ISSUE THREAD

**Issue by rsasaki0109** [PointCloudLibrary/pcl#4139]
Autoware's ndt is a pcl ndt copy?
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto

However, there is no copyright notation of pcl on the Autoware side, is this okay?
If it's like this, is there no problem without it?

There are problems with the line search method of NDT in PCL, for example, but AUTOWARE also carries this over.
Issue [Registration] There is likely a bug in the implementation of line search in the NDT
https://github.com/PointCloudLibrary/pcl/issues/3832

Autoware's NDT skips this line search method as well as PCL.
PCL
```
 while (!interval_converged && step_iterations < max_step_iterations && !(psi_t <= 0 /*Sufficient Decrease*/ && d_phi_t <= -nu * d_phi_0 /*Curvature Condition*/))
```
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L670
Autoware
```
while (!interval_converged && step_iterations < max_step_iterations &&
      !(psi_t <= 0 && d_phi_t <= -nu * d_phi_0))
```
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/common/optimization/include/optimization/line_search.hpp#L163

This part and others are the same word for word.
PCL
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L596-L752
Autoware
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/common/optimization/include/optimization/line_search.hpp#L100-206

There are other parts of it, such as.
PCL
https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/ndt.hpp#L235-L309
Autoware
https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/localization/ndt/include/ndt/ndt_optimization_problem.hpp#L233-273

Is this a problem?
I think it's difficult to call this a logic copy (i.e., if you implement the paper without looking at the code, it just happens to be similar) rather than a code copy, but isn't that the case?

I am very interested about this because it is a crossroads for me of what is and what is not a port in programs.

**Comment by kunaltyagi** [comment]
> However, there is no copyright notation of pcl on the Autoware side, is this okay?

PCL uses a BSD license. The first clause requires (**must retain**) the copyright **if** it originates from PCL.

I'm not a lawyer, but 2 implementations of the same source material can be the same, yet differ. This is visible in a several of the snippets you've provided. Similar structure isn't sufficient to ascertain the origin.

A more concerning item is replication of bugs in PCL, which indicate either a copy and modification of PCL, or a theoretical error in original paper.

> what is and what is not a port

* Some ports carry on the same code unmodified and attribute it as such (due to such attribution also getting carried forwards). This is common in forks. Future modifications will have a different copyright owner
* Others rewrite it from scratch, with similar interface/results as the inspirational material, but no common code. This doesn't require attribution to the original material
* Most however, fall in between these 2. They can for example, copy-paste the code and refactor it. This requires attribution.

Advice for you: All 3 are ports. Giving credit where credit is due is simply good manners (1st and 3rd instance). It doesn't hurt to say: "Hey, this code originates from this implementation of that paper". It just takes time to note it down while copying. Simple and modern example:
```cpp
// SPDX-License-Identifier: <LICENSE NAME>
^^ at top of file
---- other content -----
/**
 *  <scope: file/function/class>
 *  Copyright (C) Y1_start-Y1-end Author1
 *  Copyright (C) Y2_start- Yourself
 **/
stuff that this copyright matters for
```

**Comment by rsasaki0109** [comment]
> A more concerning item is replication of bugs in PCL, which indicate either a copy and modification of PCL, or a theoretical error in original paper.

It's not an error in the paper.
The paper only says that when optimizing the NDT, we run the line search method .
Not executing that line search method is a bug on the PCL side. 
(The optimization works to some extent even if you don't run the line search method.)

> Similar structure isn't sufficient to ascertain the origin.

It would be nice if the structure was just similar, but what about the variable names being exactly the same?

> It just takes time to note it down while copying. 

Yes, that's right. I don't mean to blame the Autoware people, I asked the question because I was curious after learning about the license.

**Comment by kunaltyagi** [comment]
> what if the names of the variables and methods and comments are exactly the same? And those names don't appear in the paper

That's a bad sign.

> this issue was a case I was concerned about.

That's a good thing to be aware of 😄

**Comment by kunaltyagi** [comment]
Tagging all @PointCloudLibrary/maintainers since I believe the original case has been strengthend.

PCL has a permissive license (3 clause BSD) which doesn't restrict modification, just requires attribution (which is missing). Sole attribution is to Apex.AI with Apache v2 license (different license isn't an issue).

The issue can be resolved by
1. Finding if PCL's code is original. If not, we need attribution in PCL
2. Provided 1., an attribution in Autoware code

**Comment by SergioRAgostinho** [comment]
>   1. Finding if PCL's code is original. If not, we need attribution in PCL

It's hard to track down because it's from the SVN era. At the same time it makes it more likely to be an in-house implementation from Willow Garage. Maybe @rbrusu has some memories about the conditions in which ndt was added to the lib.

**Comment by rbrusu** [comment]
They should just reference PCL as a whole. I don't remember when and how the NDT code got added in, sorry - it's been a while.

**Comment by JWhitleyWork** [comment]
Thank you for bringing this to our attention! I am the Software Architect for Autoware.Auto representing The Autoware Foundation. We are very concerned about this and are addressing it with the original developers of the NDT implementation immediately. We will respond here as soon as we have a resolution.

**Comment by kunaltyagi** [comment]
> we found a solution to an issue with the current PCL code

Can you please point towards the MR implementing the solution?

> This attribution is being added in this merge request.

Thanks for adding the attribution 😄.

(I'm not a lawyer: I'm unsure about the re-licensing though)

**Comment by JWhitleyWork** [comment]
@kunaltyagi @rsasaki0109 I am still trying to get someone to respond about the fix. Is the attribution good? We aren't re-licensing but are dual-licensing (some code under Apache 2.0 and some under BSD). AFAIK, this is the easiest way to handle this.

**Comment by kunaltyagi** [comment]
Yes, this looks good. Thanks for the followup @JWhitleyWork
