### ISSUE TITLE
PCLVisualizer does not add circle or cone to qvtkwidget

### ISSUE THREAD

**Issue by MBSadeghzadeh** [PointCloudLibrary/pcl#4453]
using **pcl-1.8.1** , **vtk-8.1.2** and **Qt-5.14**, I can not add circle or cone to qvtkwidget but point clouds, coordinate or sphere added correctly. 

```
 pcl::ModelCoefficients circle_coeff;
  circle_coeff.values.resize(3);    // We need 3 values
  circle_coeff.values[0] = 0;
  circle_coeff.values[1] = 0;
  circle_coeff.values[2] = 100;
 viewer->addCircle(circle_coeff, "circle1")
```
last line returns **false**!!

**Comment by mvieth** [comment]
If `addCircle` returns false, there should be some kind of warning printed. What does it say? (I assume `viewer` is a `PCLVisualizer`?)
Also: what OS are you using?

**Comment by MBSadeghzadeh** [comment]
`viewer` is `PCLVisualizer` . 
`OS` is `windows 10`
There is not any kind of warning about this line.

**Comment by mvieth** [comment]
That is strange because if you look [here](https://github.com/PointCloudLibrary/pcl/blob/39732f5a7c8455ed51fd0f6278d8b25322a68dd9/visualization/src/pcl_visualizer.cpp#L2529), there are only two cases where `addCircle` can return false, and there should be a warning in both cases. To be clear, the warning is printed when you run the program. Maybe try another name for the circle? Or it might be helpful if you post your whole code, not just the small snippet.

**Comment by MBSadeghzadeh** [comment]
Names are ok, I tried others but the same bug. The thing that is strange for me is that I can't find code definition for `addCircle` in `pcl_visualization.hpp` but I can see declaration in `pcl_visualization.h`.

**Comment by MBSadeghzadeh** [comment]
I did debugging again. I believed in your comment, yes the result was `true`. I was wrong in debugging. I don't know, strange behavior in `RealWithDebInfo` in `vs14`.
By the way, the result is true. Why can't I see the circle although when I rotate screen by mouse, I feel a square around circle sometimes but circle is hidden, I changed color and point and line size but nothing changed!!

**Comment by MBSadeghzadeh** [comment]
I applied below code to make it visible :)
`viewer->setShapeRenderingProperties(pcl::visualization::PCL_VISUALIZER_REPRESENTATION, 0, idCircle);`
