### ISSUE TITLE
[custom] Do the cuda filters actually exist? 

### ISSUE THREAD

**Issue by niwhsa9** [PointCloudLibrary/pcl#4474]
Hi, we are trying to use the VoxelGrid filter and PassThrough filter in the CUDA directory (as opposed to the CPU counterpart): https://github.com/PointCloudLibrary/pcl/tree/master/cuda/filters/include/pcl/cuda/filters.  However, we have no idea how to compile it. As far as we can tell, there is no compilation option in cmake for it.
![image](https://user-images.githubusercontent.com/10037572/97646609-7ccfba80-1a26-11eb-98a1-5763ebe584a4.png)

We noticed there are no source files only headers, have these filters not yet been implemented or are we missing something

**Comment by mvieth** [comment]
Disclaimer: I am no CUDA expert, and I haven't used the module yet, so this may be wrong.
It seems like the implementation is in the header files, so no compilation necessary, you should be able to just include the files in your program and then use the filters. However, the filters do not seem to do what they are supposed to do, they just filter out points that contain NaNs or infinity. And they haven't seen much development/maintenance in the last years, so I would not recommend you to use them.
May I ask why you want to use the CUDA filters instead of the "normal" ones (CPU)? Unless you process very large clouds or speed is extremely important, the CPU filters should be sufficient.

**Comment by niwhsa9** [comment]
@mvieth thanks for the info. We are using PCL for real time processing of point clouds from a ZED stereo camera for navigation in our autonomous rover competition. Speed is quite important to us, and right now our PCL pipeline on the CPU is the limiting factor. We were hoping we could optimize things using the parallelized algorithms. Seems like that isn't possible though for these filters.

**Comment by mvieth** [comment]
Ah, I see. Real-time processing with PCL is a very interesting topic that I am also currently looking into. There are a few open pull requests (and more coming) that make PCL functions faster.
Regarding your case: did you profile your program (e.g. with valgrind's callgrind) to see which functions use the most CPU time? There may not be a parallel filter implementation right now, but in my experience the filters are generally "cheap". Maybe you use other, expensive functions for which there are parallel implementations available?

**Comment by larshg** [comment]
The cuda filters seems to be header only yes, but they doesn't seem to be added for installation. So the files are probably not present if you have installed them/build locally and make install.

They would have to be copied manually to actually be usable (or add a CMakeLists that adds them as header only for installation. (last part I'm looking into sparsely)

**Comment by larshg** [comment]
I wouldn't spent more time on these filters. They doesn't seem to be properly implemented, hence not shipped.

**Comment by kunaltyagi** [comment]
@niwhsa9 I use OpenMP on CPU since adding a GPU usually costs too much in power consumption in my case. Are you using OpenMP for your filters?

If using OpenMP isn't giving enough boost, you can use OpenMP (> v4.0) on GPU as well using something like 
```cpp
#pragma omp target map<what in, out data here>
#pragma omp teams distribute parallel for
```

This will allow you to modify PCL and build it to use on GPU, but it might be a tad bit difficult since you also have to modify the compiler flags to set the offload target.

**Comment by mvieth** [comment]
I am going to close this issue because I think the question has been sufficiently answered. If not, feel free to reopen.
