### ISSUE TITLE
PCL can't build with qhull 8.0.2

### ISSUE THREAD

**Issue by tkircher** [PointCloudLibrary/pcl#4517]
As of this version of qhull, the deprecated version of the library qhull_p has been removed, and because pcl doesn't use the reentrant version, this means it can no longer be linked with a recent version of qhull. There are directions for updating code that uses qhull in an obsolete way:

http://www.qhull.org/html/README_r.txt

Edit: This may be fixed by https://github.com/PointCloudLibrary/pcl/pull/1565

**Comment by mvieth** [comment]
@kunaltyagi @larshg @koide3 I think we should solve this issue with qhull soon. PCL currently uses the non-reentrant C interface which is not available in newer qhull versions (e.g. in Ubuntu 20.10 and newer). There are two PRs which (I think) would both fix this:
PR #4540 switches to the reentrant C interface. This PR is recent and has few line changes, so should be easy to review.
PR #1565 switches to the C++ interface (which is also reentrant). It is much older, but was already approved (3 years ago). It has merge conflicts though, and I don't know if the author is still interested in working on the PR. It is also much bigger (more line changes)
I would tend to review and merge the first (newer) PR since its much easier with a similar effect, but I would also like to know your opinions.

**Comment by tkircher** [comment]
PR #4540 looks good to me. I'll give it a try this week and run some tests and report back.

**Comment by mvieth** [comment]
Fixed by pull request #4540
