### ISSUE TITLE
[pcl-1.8.1]"make -j" compilation doesn't work

### ISSUE THREAD

**Issue by JeongJae0815** [PointCloudLibrary/pcl#4532]
Hi guys, I am a huge fan of pcl libraries, and my c++ project is based on pcl 
Unfortunately, I have a problem on parallel compilation which it just use single core with 'make -jN'
What should I do to enable parallel compilation?

------------------------------------------------------------------------
system configuration
ubuntu 18.04
pcl 1.8.1(install from github)

Thank you 
---------Here is my Cmake Project(it is very simple for test)---------------------
    1cmake_minimum_required(VERSION 3.15)
    2 # set the project name and version
    3 project(pcl-clangd-test VERSION 1.0)
    4
    5 # Find PCL
    6 find_package(PCL 1.8 REQUIRED)
    7 include_directories(${PCL_INCLUDE_DIRS})
    8 link_directories(${PCL_LIBRARY_DIRS})
    9 add_definitions(${PCL_DEFINITIONS})
   10
   11 add_executable(test test.cxx)
   12 target_link_libraries(test ${PCL_LIBRARIES})

---------test.cxx(it is very simple for test)---------------------
    1 #include<iostream>
    2 #include<string>
    3 #include<pcl/registration/icp.h>
    4 #include<pcl/registration/gicp.h>
    5
    6 int main(int argc, char *argv[]){
    7     std::cout<<"adfdsaf"<<std::endl;
    8     std::cout<<"afcdefg"<<std::endl;
    9
   10 }

**Comment by mvieth** [comment]
Just to make sure I understand you correctly: you want to compile your own project, which uses PCL. Your project has only one executable ("test"), compiled from a single source file ("test.cxx"), and you want to use multiple jobs to do it (e.g. make -j2 for two jobs)? That is not possible. As far as I know, there is no compiler and no tool that creates a single executable from a single source file in parallel. If you would split your source code into multiple files, they could be compiled in parallel. But even without doing that, the compilation should not take that long, probably not more than a few minutes at most?

**Comment by JeongJae0815** [comment]
I appreciate your reply :)
Yes you've understood me correctly(I've got completely wrong information about parallel compilation.)
So Does it means that, in "make -jN", the number of N can be decided by the number of executable(not including the number of library[add_library()])?

++. One more thing, I compile the simple project that I mentioned with both gcc7 and clang11. However, gcc7 is 4 times different in the time it takes than clang11. I have no idea about it

**Comment by mvieth** [comment]
> So Does it means that, in "make -jN", the number of N can be decided by the number of executable(not including the number of library[add_library()])?

From the man page of make:
> -j [jobs], --jobs[=jobs]
>            Specifies the number of jobs (commands) to run simultaneously.  If
>            there is more than one -j option, the last one is  effective.   If
>            the  -j  option  is given without an argument, make will not limit
>            the number of jobs that can run simultaneously. When make  invokes
>            a sub-make, all instances of make will coordinate to run the spec‐
>            ified number of jobs at a time; see the section PARALLEL MAKE  AND
>            THE JOBSERVER for details.

Generally I would say that it is not a problem if you set the number of jobs higher than you actually need, `make` will figure out how many jobs it wants to/can run. However, I often have the problem that I can't run as many jobs as I want to, because I don't have enough RAM, and my computer would crash. How many jobs you should run depends highly on your computer and what you are compiling, so it might require some experiments: start with e.g. 2 jobs, open a system monitor, and if your computer can handle it, try out more jobs.

> If so, Is there any way to make them join in parallel compilation?

Sorry, I don't understand the question. What do you mean by "join in parallel compilation"?

> One more thing, when I compile the simple project that I mentioned with both gcc7 and clang11, gcc7 is 4 times different in the time it takes than clang11(clang11 is slower). is it possible?

That is possible, although I would not have expected such a difference. The compilation time also depends on the flags/options you give to the compilers, e.g. the optimization level.

**Comment by gedikli** [comment]
Actually that should work. Except you have dependencies that can not be unrolled (topological order). Then the make system will not have many sources it can compile in parallel, since they depend on each other.
If you compile just PCL, it should be able to do that in parallel. However, when doing this the even 32GB of RAM is not enough (This is due to the heavy templated classes in PCL.) and your computer will start using the swap partition, which is slow as hell.

**Comment by JStech** [comment]
On that note, make sure you _do_ have lots of memory/swap if you're building PCL in parallel. I learned that the hard way. 32 GB ought to be enough for anybody.

**Comment by JeongJae0815** [comment]
@mvieth 
> Sorry, I don't understand the question. What do you mean by "join in parallel compilation"?
Oh Please forget it. I got wrong idea. Thank you :)

@gedikli , @JStech 
> Thank you for replying! My question was compiling my own project with pcl, not comiling pcl itself(If I understood you correctly)

**Comment by mvieth** [comment]
> If so, is there any way to make clang compiling fast ?

The only way I can think of right now is to turn off optimizations with `-O0`: your program will compile faster, but possibly run slower than with optimizations enabled (e.g. `-O1`, `-O2`, etc.). For ways to make it faster, I would recommend a google search.

**Comment by JeongJae0815** [comment]
@mvieth 
Let me google it :)Thank you so much!
