### ISSUE TITLE
Will it be possible to implement/develop a code for voxelization of point cloud?

### ISSUE THREAD

**Issue by Suri12990** [PointCloudLibrary/pcl#4576]
Hey,

I need to use voxelization of point cloud feature.  For an example [this](https://github.com/qianguih/voxelnet/blob/master/utils/preprocess.py). Will it be possible to achieve this using C++ and eigen library?.  I think this feature helps the people working on Point clouds and Deep Learning. Nowadays, in autonomous driving, use of Lidar has been increasing. I think this feature helps lots of people. 

I know that voxelization feature is already exist in PCL in the form of pointer and octree. But I tried a lot to use both of them in the above mentioned form. But I do not think, without new implementation, it is possible.  

Thanks in advance

**Comment by JStech** [comment]
Can you say more about how your desired format differs from an octree? Is there a particular library you're trying to interface with?

**Comment by mariya12290** [comment]
Yeah, I am trying to interface the voxelization of point clouds as a backbone to different deep learning neural networks. For an example, RPN, Mask RCNN and with other neural networks for semantic segmentation and object tracking algorithms.  I have the code for the different networks in C++(save model), So If I have voxelization of piont clouds, I can use with different networks. I can implement it on myself, But I am a student still, I need to finish my tmaster hesis by the end of June, Since I already registered for thesis in the examination center,  I do not want to get into any trouble now.

**Comment by Suri12990** [comment]
Yeah, I am trying to interface the voxelization of point clouds as a backbone to different deep learning neural networks. For an example, RPN, Mask RCNN and with other neural networks for semantic segmentation and object tracking algorithms. I have the code for the different networks in C++(save model), So If I have voxelization of piont clouds, I can use with different networks. I can implement it on myself, But I am a student still, I need to finish my tmaster hesis by the end of June, Since I already registered for thesis in the examination center, I do not want to get into any trouble now.
