### ISSUE TITLE
[tools] mesh_sampling.cpp    will convert .obj file  of shapenet  to incomplete point cloud   in many case 

### ISSUE THREAD

**Issue by resplendent-star** [PointCloudLibrary/pcl#4622]
**When I use a to convert shapenet's obj file into a point cloud, there is about 1 / 3 probability that I will get the wrong point cloud. For example, a table has only table legs but no desktop; a chair has a back but no lower chair legs**

What are you trying to accomplish? Providing context helps us come up with a solution that is most useful in the real world

**Expected behavior**

right point cloud

**Current Behavior**

incomplete  point cloud

**To Reproduce**

Provide a link to a live example, or an unambiguous set of steps to reproduce this bug. A reproducible example helps to provide faster answers.

**Screenshots/Code snippets**

![obj_picture](https://user-images.githubusercontent.com/41502003/108953711-9ae0bb00-76a6-11eb-83ef-48fabefd0503.png)
![incomplete_point_cloud](https://user-images.githubusercontent.com/41502003/108953741-a633e680-76a6-11eb-8c0c-85cd970071cf.png)
[3.txt](https://github.com/PointCloudLibrary/pcl/files/6033661/3.txt)

BTW:the 3.txt is the  .obj file,you need to edit its name from  .txt  to  .obj(because of  github dont support the .obj file,so i have to edit its name form .obj to   .txt)

CODE file  :
[mesh_sampling.txt](https://github.com/PointCloudLibrary/pcl/files/6033677/mesh_sampling.txt)
(the same reason,,,this  txt  is  also  a  cpp file,you need to change its name from  txt 
 to  .cpp)

**Your Environment (please complete the following information):**

 Ubuntu 18.04
gcc version 7.5.0

 - PCL 1.9

**Comment by mvieth** [comment]
`mesh_sampling` uses the `vtkOBJReader`, which seems to be the problem here. I tried [this example](https://lorensen.github.io/VTKExamples/site/Cxx/IO/ReadOBJ/), which also only displays the legs of the chair. It seems like the reader cannot understand some of the face definitions, which are in [this format](https://en.wikipedia.org/wiki/Wavefront_.obj_file#Vertex_normal_indices_without_texture_coordinate_indices), although they appear to be valid regarding the file format. Perhaps the `vtkOBJReader` works correctly with newer versions, I can only confirm that the problem appears with VTK version 7.1.1. If the issue appears with all VTK versions, you could inform the VTK developers of this behaviour. You could also try to convert the obj file to a ply file (or export it as a ply file in the first place) and see if it works then.

**Comment by mvieth** [comment]
I now tested again with VTK 9.1.0, and everything works as you would expect (complete chair). So I am closing this.
