### ISSUE TITLE
[feature] Bug in the normal calculation of computePointNormal

### ISSUE THREAD

**Issue by miixam** [PointCloudLibrary/pcl#4625]
**Describe the bug**
The normals, which are calculated in computePointNormal by calling solvePlaneParameters and eigen33, are based on the largest scalar of the eigenvectors instead of the smallest one.

**Context**
By definition the smallest eigenvector will indicate the normal vectors of the planes best fitting to its neighborhood. Each eigenvector shows in the direction of the principal variations. The eigenvector with the smallest eigenvalue corresponds to the direction of the least variation, which is geometrically perpendicular to the direction of the most variations. Thus it is the normal vector.

Slide 21: https://www.slideshare.net/PirouzNourian/tu-delft-geo1004-2015-point-cloud-processing-estimating-normal-vectors-and-curvature-indicators-using-eigenvectors

**Similar issues/pull requests**
There are two open issues/pull requests, which focus the normals:
https://github.com/PointCloudLibrary/pcl/issues/2403
https://github.com/PointCloudLibrary/pcl/pull/3169

Maybe these can profit from the bugfix as well.

**Comment by mvieth** [comment]
Thank you for voicing your suspicion, however it seems to me that there is no such bug.
I assume you are talking about [this eigen33 version](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/eigen.h#L113). The documentation says that it returns the smallest eigenvalue (and corresponding eigenvector). In the implementation, the [first eigenvalue is chosen](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/impl/eigen.hpp#L311), which is the smallest, since they are [in increasing order](https://github.com/PointCloudLibrary/pcl/blob/master/common/include/pcl/common/impl/eigen.hpp#L116). The function name `getLargest3x3Eigenvector` might have led to the confusion, however that does not mean that it returns the eigenvector corresponding to the largest eigenvalue.
I verified experimentally that `eigen33` returns the smallest eigenvalue (and corresponding eigenvector). I would encourage you to verify this, too.
If the computation would actually use the largest eigenvalue instead of the smallest, the normals would be completely wrong (more like tangents to the surface, I think). That is not the case, so I am confident that the normal calculation is correct.
I looked at the current PCL master. If you looked at some older version of the code, or you still have substantiated suspicions that the code is wrong, please say so.

**Comment by miixam** [comment]
I see, the problem is that I'm using pcl 1.7, where [the function computeCorrespondingEigenVector](https://github.com/PointCloudLibrary/pcl/blob/793a2074235ae9402e7139e3928ee693031dd419/common/include/pcl/common/impl/eigen.hpp#L226) is used to be named eigen33 and is utilized in the normal calculation.

Thanks for the clarification. I'll close the issue, since it doesn't persist in the current master.
