### ISSUE TITLE
[io] Point Cloud compression logic is inconsistent between octree_pointcloud_compression and {point,color}_coding

### ISSUE THREAD

**Issue by BryceVichiOJ** [PointCloudLibrary/pcl#4631]
**Describe the bug**

The time it takes to compress a PointCloud of type PointXYZRGB increases rapidly the more times encodePointCloud is called.

**Context**

I am creating an application which ships large PointCloud data across a network. Compression for doing this is a must. Most point clouds that I work with are of size 100,000 points. The OctreePointCloudCompression class solves a large chunk of my size issues. Upon doing some performance testing, I have found that the time taken by the Compression class increases drastically when working with XYZRGB clouds. This does not appear to be the case.

**Expected behavior**

Calling encodePointCloud on a PointXYZRGB point cloud should take roughly the same time over the course of several calls.

**Current Behavior**

Instead, the time it takes to encode a point cloud is increasing quite rapidly. Making faster to always reset the Encoder rather than re-use it. 

**To Reproduce**

Here is a sample of the code which reproduces this issue.
```
void main()
{
	int size = 100000;

	auto cloud = boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB>>(new pcl::PointCloud<pcl::PointXYZRGB>());

	for (int i = 0; i < size; i++)
	{
		cloud->push_back(pcl::PointXYZRGB(0, 0, 0));
	}

	pcl::io::OctreePointCloudCompression<pcl::PointXYZRGB> encoder(pcl::io::compression_Profiles_e::HIGH_RES_OFFLINE_COMPRESSION_WITH_COLOR);
	
	for (int i = 0; i < 100; i++)
	{
		std::stringstream stream;
		encoder.encodePointCloud(cloud, stream);
	}
}
```

**Your Environment (please complete the following information):**

I have tested this issue on both Window and Linux, using both Release/Debug modes, and it appears to be present in all. I am using PCL 1.9.1, though the OctreePointCloudCompression class has not seen any structural updates since 1.9.1 (as far as I can tell).

**Additional Information**
- This issue does not appear to effect PointXYZ point clouds from my testing and is less likely to be seen a lower compression profile (though still present on LOW).
- Modifying the point cloud between calls also seems to affect it.
- The addPointIdx function seems to store an integer for each point but never clears out the vector (perhaps it does on intra frames?). This vector becoming increasingly large could be the reason this occurs.

**Comment by mvieth** [comment]
Hm, interesting. Did you test whether the clouds are the same after encoding and the decoding? Especially whether they have the same number of points?

> This issue does not appear to effect PointXYZ point clouds from my testing

In my tests it does.

> Modifying the point cloud between calls also seems to affect it.

Affect how? Decreasing the time?

It seems like the points/indices from each previous iteration are kept in the octree (not cleared on intra frames either, I think). Maybe there is a bug in `switchBuffers()`? Replacing `switchBuffers()` with `deleteTree()` in `encodePointCloud()` stops the increasing time with the iterations, but that can't be a good solution. I don't have much experience with the double-buffer octree, does one of you @kunaltyagi @larshg @koide3 ?

**Comment by kunaltyagi** [comment]
I think I might have found something: at a glace, it seems that `deserialize` might have a bug. It leaves the tree_dirty flag as false, but that should be true. It'd take me time to verify that's the case so if one of you could flip the flag (in all occurrences of deserialize calls in octree2buf_base) and test, that'd be nice :)

I'm anyways trying to reproduce this, so if you can't, no issues :)

**Comment by kunaltyagi** [comment]
So, I did a little investigation:

1. I'll create a PR to reduce 10% of dynamic memory allocated during 500 iterations of encoding.
2. There are no memory leaks, and there needs to be no reclamation of any nodes (if the point cloud stays constant)
3. This implies, the slowdown might not be due to PCL, but the allocator (as in the underlying malloc/calloc/realloc implementation). This is just my hypothesis, and it's not verified. Still needs lots more digging into.

The major contributor of dynamic allocations:
![dyn-alloc](https://user-images.githubusercontent.com/2657068/110205917-430b3680-7e94-11eb-8395-4626c95392ab.png)

It'd be very helpful if someone else can tackle (try to reduce) these, while I figure out why the total memory use (virtual and allocated) is increasing per iteration for no discernible reason.

**Comment by kunaltyagi** [comment]
Found the issue. We're going quadratic in memory allocation in `StaticRangeCoder`. Remains to be seen why.

**Comment by kunaltyagi** [comment]
I think this is due to the color and point coders not clearing their internal vectors. I've got to go now. Hopefully someone else can pick up now. Problem is simple enough:
* `reserve` call in `encode{Int,Char}VectorToStream` is making growth linear on gcc
* size of input keeps growing each iteration
* input comes from internal state of point and color coders, which are never cleared/reset, but always appended to.

**Comment by mvieth** [comment]
Seems like they clear their internal vectors in [`initializeEncoding`](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/compression/point_coding.h#L106), called [here](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/compression/impl/octree_pointcloud_compression.hpp#L111). Or do you mean some other vectors?

**Comment by BryceVichiOJ** [comment]
Thanks for the good discussion on this. To answer some questions.

> Hm, interesting. Did you test whether the clouds are the same after encoding and # the decoding? Especially whether they have the same number of points?
>
Yes, the decoding part seems to have no issues. One issue I noticed was that encoding RGBA does not encode the Alpha channel, though that is an entirely different issue.

> > Modifying the point cloud between calls also seems to affect it.
>>
> Affect how? Decreasing the time?
>
The time it takes decreases. The increasing memory issue still exists.

**Comment by rabaho** [comment]
The problem I believe, is in [serializeTree](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/compression/impl/octree_pointcloud_compression.hpp#L125). That method takes a boolean flag where it decides whether to append previous octrees or not. It calls a [serializeTreeCallback](https://github.com/PointCloudLibrary/pcl/blob/master/io/include/pcl/compression/impl/octree_pointcloud_compression.hpp#L471) where leafIdx vector size is doubled with every call.

**Comment by mvieth** [comment]
If that flag of [serializeTree](https://pointclouds.org/documentation/classpcl_1_1octree_1_1_octree2_buf_base.html#a4ab50312544738fbcb2dcec19be7d1c0) is true, it does not append the previous octree. It basically generated a diff between the previous and the current octree, that should be fine and even helps the compression when the trees did not change much.
I am pretty sure the problem is [here](https://github.com/PointCloudLibrary/pcl/blob/master/octree/include/pcl/octree/impl/octree2buf_base.hpp#L390), where the octree copies a leaf node from the previous octree, which might still contain indices. I will try to open a PR tomorrow.

**Comment by rabaho** [comment]
Yeah, that's what serializeTree with the true flag is supposed to do, but I don't think it's doing that. It's somehow adding previous leaf indices from the previous octree somewhere between when serializeTree is called and encodePoints, most likely in the octree base class.

**Comment by mvieth** [comment]
Please have a look at pull request #4642 and (if possible) test whether it fixes the bug.

**Comment by BryceVichiOJ** [comment]
Apologize for the delay. After testing, it appears PR #4642 fixes the issue. Thank you to all who helped work on this.
