### ISSUE TITLE
[compile error] "Can't find "pcl/test/gtest.h"."

### ISSUE THREAD

**Issue by yokinglou** [PointCloudLibrary/pcl#4820]
I installed PCL on Ubuntu18.04 with command `sudo apt install libpcl-dev`.

I tried to run test programs under `pcl/test/features`, but the error raises: 

```
test_flare_estimation.cpp:40:10: fatal error: pcl/test/gtest.h: No such file or directory
 #include <pcl/test/gtest.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I locate the files in `/usr/local/include/pcl-1.11/pcl/`, but can not find the test directory.

Is there anything else I need to install?

**Comment by mvieth** [comment]
`libpcl-dev` on Ubuntu 18.04 has version 1.8.1. But it also seems you have some 1.11 version installed? Did you compile it from source? Having multiple versions installed might lead to problems.
That header only exists since PCL 1.10.1.
How exactly did you try to compile/run the test program?
You also need to install `libgtest-dev`, but the error message is unrelated to that.

**Comment by yokinglou** [comment]
I install `libgtest-dev` and solve this problem.
Thanks.
