### ISSUE TITLE
Region growing bug??

### ISSUE THREAD

**Issue by songgod** [PointCloudLibrary/pcl#4823]
https://github.com/PointCloudLibrary/pcl/blob/d98313133b014553ab1b1b5b112f9aade837d55c/segmentation/include/pcl/segmentation/impl/region_growing.hpp#L530

"initial_point - nghbr_point" should be normalize.

**Comment by mvieth** [comment]
The idea with the residuals is described in the paper (https://www.isprs.org/proceedings/XXXVI/part5/paper/RABB_639.pdf) in sections 2.1.1 and 2.1.2. A residual is the distance of a point to a plane, which is n * p - rho. In the code, n = initial_normal, p = nghbr_point, and rho = initial_normal.dot(initial_point). The sign is switched, but that does not matter because of the abs. So I don't see anything wrong with the current code?
Why do you think it should be normalized? Please explain ...

**Comment by songgod** [comment]
> The idea with the residuals is described in the paper (https://www.isprs.org/proceedings/XXXVI/part5/paper/RABB_639.pdf) in sections 2.1.1 and 2.1.2. A residual is the distance of a point to a plane, which is n * p - rho. In the code, n = initial_normal, p = nghbr_point, and rho = initial_normal.dot(initial_point). The sign is switched, but that does not matter because of the abs. So I don't see anything wrong with the current code?
> Why do you think it should be normalized? Please explain ...

sorry, my understanding about the idea is wrong. the idea is perfect. 
thanks for you reply.
