### ISSUE TITLE
[filters] Passthrough not work for field label

### ISSUE THREAD

**Issue by pettaa123** [PointCloudLibrary/pcl#4862]
**Passthough not work for field label with PointXYZL**

I think it is desirable that one can filter a pointcloud by it's points labels. 

**To Reproduce**

```
pcl::PointCloud<pcl::PointXYZL>::Ptr testCloud (new pcl::PointCloud<pcl::PointXYZL> ());
std::vector<pcl::PointXYZL, Eigen::aligned_allocator<pcl::PointXYZL> > testCloudPts;
testCloudPts.push_back(pcl::PointXYZL(0,0,0,1));
testCloudPts.push_back(pcl::PointXYZL(0,0,0,3));
testCloud->points=testCloudPts;
testCloud->width=testCloudPts.size();
pcl::PointCloud<pcl::PointXYZL>::Ptr labelCloud (new pcl::PointCloud<pcl::PointXYZL> ());
pcl::PassThrough<pcl::PointXYZL> pass;
pass.setInputCloud (testCloud);
pass.setFilterFieldName ("label");
pass.setFilterLimits (2, 4);
pass.filter (*labelCloud);
std::cout << labelCloud->width << std::endl; //is 0
```

I expect having point (0,0,0,3) of testCloudPts in labelCloud. But it is empty.

 - OS: [e.g. Ubuntu 20.04]
 - Compiler: [GCC]
 - PCL Version [e.g. 1.10.1]

**Comment by tin1254** [comment]
I just dive deep into the source code, the problem is the following `memcpy`. It copies `std::uint32_t` label to `float`, and resulting in `float` with 0 value. 

https://github.com/PointCloudLibrary/pcl/blob/7194dd7f4c03220d0be84d37c3560d600f695113/filters/include/pcl/filters/impl/passthrough.hpp#L100-L101

I would suggest we can use`getFieldType` to avoid that problem

https://github.com/PointCloudLibrary/pcl/blob/7194dd7f4c03220d0be84d37c3560d600f695113/common/include/pcl/common/io.h#L158

**Comment by mvieth** [comment]
I am not sure if it makes sense to develop the `PassThrough` filter further, because the FunctorFilter/FunctionFilter could replace it in the long run.
@pettaa123 Maybe have a look at the `ConditionalRemoval` filter

**Comment by pettaa123** [comment]
@mvieth thanks, ConditionalRemoval works with label.
