### ISSUE TITLE
[Voxel Filter] voxel filter generate points at wrong position

### ISSUE THREAD

**Issue by kosuke55** [PointCloudLibrary/pcl#4895]
**Describe the bug**
It seems that the voxel filter is generating a point cloud at the wrong position.
It is generated where the original point cloud does not exist.
Also, it seems that there are areas that will be deleted.

Please see the video for details.
https://user-images.githubusercontent.com/39142679/129371902-ae39a975-1002-4ed7-9037-96fb7009200c.mp4
The red point cloud is a downsample. There is a point cloud in a strange position on the right side. In addition, there is a defect in the point cloud restored from the map with the downsampled point cloud and the original point cloud.

**Context**

I tried to processe the downsampled point cloud as a representative point and restore it to the original point cloud.

**Expected behavior**

The voxel filter can generate points at the correct position.

**Current Behavior**

The voxel filter generates points at the wrong position.

**To Reproduce**

I prepare code to reproduce.
https://github.com/kosuke55/debug_pcl_voxelgrid
```
cd build
cmake ..
make
./main 2.0 2.0 2.0
# sudo snap install cloudcompare
cloudcompare.CloudCompare input.pcd downsampled.pcd restored.pcd
```

**Screenshots/Code snippets**

![Screenshot from 2021-08-14 00-10-46](https://user-images.githubusercontent.com/39142679/129379809-252aaa31-e996-4cc3-b243-c0ff0f76c6e5.png)

The red point surrounded by the green circle seems to be in a strange position.

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: GCC 9.3.0
 - PCL Version: 1.12, 1.10

**Comment by mvieth** [comment]
@tin1254 As our voxel grid expert, would you have a look at this issue?

**Comment by tin1254** [comment]
I've looked at the example and the provided cloud yesterday but every seems right. I'll dig deeper into the source code during this weekend

**Comment by tin1254** [comment]
The reason is the coordinate of your cloud is too large. When the filter computing a voxel centroid, the accumulating value will be up to `2.21371e+08`. With this magnitude every `float` arithmetic operations are inaccurate, so some centroids which accumulated many points are shifted from the true location by 1~2 meters

https://github.com/PointCloudLibrary/pcl/blob/d615a74beccb4ed504e61c040529870e5f57e5e7/filters/include/pcl/filters/impl/voxel_grid.hpp#L406-L412

A quick fix would be offsetting the cloud before filter.

@mvieth @kunaltyagi I feel like it's not a corner case. We should implement some smart way to accumulate centroid, e.g. offset by us internally in the code (should be a lot faster since accumulation can be done in one loop instead of requiring users to have a separate loop)

**Comment by kosuke55** [comment]
@tin1254 
Thank you very much!!  Offsetting the cloud before filter fixed the problem.
![Screenshot from 2021-08-15 00-01-12](https://user-images.githubusercontent.com/39142679/129450631-81942d08-7a0c-41db-84ea-4b9fab162ca2.png)
