### ISSUE TITLE
[common] `transformPointCloud` expects `Affine3f` even for `PointXY`

### ISSUE THREAD

**Issue by BaltashovIlia** [PointCloudLibrary/pcl#4905]
**Describe the error**

pcl::PointXYZ is implemented as a union-like structure and has a field .data. 
pcl::PointXY is however implemented as a “pure” structure and does not have a .data field.

**To Reproduce**

The result of this inconsistency are a weird compilation errors for the following code:
```C++
#include <pcl/point_types.h>
#include <pcl/common/transforms.h>

int main()
{
    using PointT = pcl::PointXY; // compile with pcl::PointXYZ
    pcl::PointCloud<PointT> cloud_in;
    pcl::PointCloud<PointT> cloud_out;
    Eigen::Affine3f transform;

    pcl::transformPointCloud(cloud_in, cloud_out, transform);

    return 0;
}
```

**Screenshots/Code snippets/Build information**

```
In file included from /usr/local/include/pcl-1.12/pcl/common/transforms.h:493,
                 from /home/baltic/CLionProjects/untitled1/main.cpp:2:
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp: In instantiation of ‘void pcl::transformPointCloud(const pcl::PointCloud<PointT>&, pcl::PointCloud<PointT>&, const Eigen::Matrix<Scalar, 4, 4>&, bool) [with PointT = pcl::PointXY; Scalar = float]’:
/usr/local/include/pcl-1.12/pcl/common/transforms.h:74:48:   required from ‘void pcl::transformPointCloud(const pcl::PointCloud<PointT>&, pcl::PointCloud<PointT>&, const Affine3f&, bool) [with PointT = pcl::PointXY; Eigen::Affine3f = Eigen::Transform<float, 3, 2>]’
/home/baltic/CLionProjects/untitled1/main.cpp:11:60:   required from here
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp:244:27: error: ‘const struct pcl::PointXY’ has no member named ‘data’
  244 |       tf.se3 (cloud_in[i].data, cloud_out[i].data);
      |               ~~~~~~~~~~~~^~~~
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp:244:46: error: ‘struct pcl::PointXY’ has no member named ‘data’
  244 |       tf.se3 (cloud_in[i].data, cloud_out[i].data);
      |                                 ~~~~~~~~~~~~~^~~~
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp:254:39: error: ‘const struct pcl::PointXY’ has no member named ‘z’
  254 |           !std::isfinite (cloud_in[i].z))
      |                           ~~~~~~~~~~~~^
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp:256:27: error: ‘const struct pcl::PointXY’ has no member named ‘data’
  256 |       tf.se3 (cloud_in[i].data, cloud_out[i].data);
      |               ~~~~~~~~~~~~^~~~
/usr/local/include/pcl-1.12/pcl/common/impl/transforms.hpp:256:46: error: ‘struct pcl::PointXY’ has no member named ‘data’
  256 |       tf.se3 (cloud_in[i].data, cloud_out[i].data);
      |                                 ~~~~~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/untitled1.dir/build.make:72: CMakeFiles/untitled1.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/untitled1.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

**Your Environment (please complete the following information):**

 - OS: Ubuntu 20.04
 - Compiler: GCC 9.3.0
 - PCL Version: HEAD
 - PCL Type: Compiled from source

**Possible Solution**

What's the best way to fix this? Rewriting pcl::PointXY like pcl::PointXYZ will only solve half of the problem, since transformPointCloud calls se3, which assumes that a point has all three coordinates.

**Comment by mvieth** [comment]
Yes, we could add a `data` member to `PointXY` in combination with a union. We could add a third `z` coordinate that is always zero, but that probably does not make much sense.
`transformPointCloud` expects either an `Eigen::Affine3f` or an 4x4 matrix as a transformation, but it does not make sense to apply either to a 2-dimensional point. So the question would be, what result should `transformPointCloud` give in that case?
If anything, we could add an overload for `transformPointCloud` that expects `Eigen::Affine2f` or a 3x3 Matrix.

**Comment by kunaltyagi** [comment]
> If anything, we could add an overload for transformPointCloud that expects Eigen::Affine2f or a 3x3 Matrix.

100% behind you on this. The internals of Point type shouldn't affect the usage.

**Comment by BaltashovIlia** [comment]
I additionally tested some other PCL functions and found that a lot of them have internal compilation errors when used with 2D points. 

A few examples:

.data: 
- Registration<PointSource, PointTarget, Scalar>::align (pcl/registration/impl/registration.hpp:210:15:)
- setInputSource (pcl/registration/gicp.h:146:16:)
- transformPoint (pcl/common/impl/transforms.hpp:439:17:) 

.z: 
- pcl::PassThrough<PointT>::applyFilterIndices (pcl/filters/impl/passthrough.hpp:63:41)
- pcl::search::OrganizedNeighbor<PointT>::nearestKSearch (pcl/filters/impl/voxel_grid.hpp:306:65:)
- pcl::SampleConsensusModelPlane<PointT>::projectPoints (pcl/sample_consensus/impl/sac_model_plane.hpp:429:44:)

.getVector4fMap
- pcl::VoxelGrid<PointT>::applyFilter (pcl/filters/impl/voxel_grid.hpp:409:67:)
- pcl::SampleConsensusModelPlane<PointT>::computeModelCoefficients (pcl/sample_consensus/impl/sac_model_plane.hpp:80:51:)
- pcl::PFHEstimation<PointInT, PointNT, PointOutT>::computePairFeatures (pcl/features/impl/fpfh.hpp:56:42:)

.getVector3fMap
- pcl::getMaxDistance (pcl/common/impl/common.hpp:209:43:)
- pcl::SampleConsensusModelSphere<PointT>::selectWithinDistance (/home/baltic/Downloads/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_sphere.hpp:205:55:)
- RangeImage::doZBuffer (pcl/range_image/impl/range_image.hpp:250:44:)

**Comment by mvieth** [comment]
We can consider adapting some of the examples you gave (e.g. using `pcl::isFinite` in PassThrough instead of checking x, y, z), but IMO not all of these classes can/should be applied to 2D points. For example, it only make sense to apply the plane model to 3D points, but not to 2D points (a line model may be the right equivalent for 2D points). Similarly, the sphere model is designed for 3D points; for 2D points the `SampleConsensusModelCircle2D` would be appropriate. I am not very familiar with the PFH/FPFH features, but I doubt that they translate well to 2D points.
Generally I would say that PCL is mainly for 3D point processing, and the PointXY is only a special case. IMO asking that _all_ classes and functions in PCL work with PointXY is too much. Rewriting the code so that it can be used with PointXY, would likely result in reduced performance, more code, and especially more complex code. And I am not sure if anyone actually _needs_ all the classes to work with PointXY.
IMO a good strategy would be to act on a per-case basis, guided by use cases. If you (or anyone else) come across a case where you want to use a class/function with PointXY in your code/project, there is no other work-around, and the specialization for PointXY fits nicely into the existing code, then we could consider adapting the code. E.g. for the function you gave initially, `transformPointCloud`, I would agree that it makes sense to add a simple implementation like `transformPointCloud(const pcl::PointCloud<pcl::PointXY>& cloud_in, pcl::PointCloud<pcl::PointXY>& cloud_out, const Eigen::Affine2f& transform, bool copy_all_fields = true)` or similar.

**Comment by BaltashovIlia** [comment]
Yes, I understand that many functions have no meaning when they are used with 2D points. But what about adding SFINAE or static_assert for such functions? In this case, it will be easier for the user to understand that he is doing something wrong.

**Comment by mvieth** [comment]
Yes, that sounds good. A static_assert with a nice message would be very helpful

**Comment by ArkaprabhaChakraborty** [comment]
Is this issue still open? f so, I want to work on it.

**Comment by mvieth** [comment]
> Is this issue still open? f so, I want to work on it.

Yes, that would be great! Feel free to open a pull request (and ask any questions if anything is unclear)

**Comment by ArkaprabhaChakraborty** [comment]
What are the things that I should be doing for this issue?

**Comment by mvieth** [comment]
In summary:
- add a new function `transformPointCloud` that works for `pcl::PointXY`
- add `static_assert` to any class/function that cannot be used with `pcl::PointXY` (especially those mentioned above). The idea is to give the user a nice message why that does not work
- ... maybe more, but those are the two most important points

Please read through the comments again, I think it is explained quite detailed what is desired. You don't have to do both tasks at once, better in multiple pull requests one after another

**Comment by ArkaprabhaChakraborty** [comment]
Got it. I read through the comments but i found the above description more helpful.

**Comment by ArkaprabhaChakraborty** [comment]
This means I have to add a Transformer method too ?

**Comment by ArkaprabhaChakraborty** [comment]
I think a transformer method will be required using a 2x2 rigid body matrix. I might be wrong though so please do correct me.

**Comment by mvieth** [comment]
I would say a `Transformer` struct that uses SIMD like for the other `transformPointCloud` functions is not the way to go here, partly because SIMD is not usable efficiently due to the smaller size. I would suggest to create an `Eigen::Vector2f` from each point, then use the transform on that. We could even consider to add a `getVector2fMap()` to `PointXY` in point_types.hpp

**Comment by ArkaprabhaChakraborty** [comment]
Okay. But what would be the transformation function then. I'm sorry I'm new to rigid body simulations. So can I get some hints ?

**Comment by mvieth** [comment]
Just a multiplication: https://eigen.tuxfamily.org/dox/group__TutorialGeometry.html

**Comment by ArkaprabhaChakraborty** [comment]
what does this line mean ?
`inline PointXY(float _x, float _y): x(_x), y(_y) {}`
within `struct PointXY`

**Comment by mvieth** [comment]
> what does this line mean ?
> `inline PointXY(float _x, float _y): x(_x), y(_y) {}`
> within `struct PointXY`

That's a constructor. If you e.g. write `pcl::PointXY point(1.0, -2.0);`, then this constructor sets the `x` and `y` of the point, so that `point.x == 1.0` and `point.y == -2.0`.

**Comment by ArkaprabhaChakraborty** [comment]
` struct PointXY`   
`{`
    `float x = 0.f;`
    `float y = 0.f;`
    `inline PointXY() = default;`
    `inline PointXY(float _x, float _y): x(_x), y(_y) {};`
    `inline Eigen::Map<Eigen::Vector2f> getVector2fMap()`
    `{`
      `Eigen::Vector2f  v1(x,y);`
      `Eigen::Map<Eigen::Vector2f> mapped_points = Eigen::Map<Eigen::Vector2f>(v1);`
      `return mapped_points; `
    `}`
    `friend std::ostream& operator << (std::ostream& os, const PointXY& p);`
  `};`

Im trying to make a getVector2fMap() for PointXY, but I get the error:
`error: no matching function for call to ‘Eigen::Map<Eigen::Matrix<float, 2, 1> >::Map(Eigen::Vector2f&)`
Maybe I'm making a dumb mistake. How do I correct this?

**Comment by ArkaprabhaChakraborty** [comment]
Or I should just return an Eigen::Vector2f ? because the map is not making any sense.

**Comment by ArkaprabhaChakraborty** [comment]
Im keeping it 
`
  struct PointXY
  {
    float x = 0.f;
    float y = 0.f;

    inline PointXY() = default;

    inline PointXY(float _x, float _y): x(_x), y(_y) {};

    inline Eigen::Vector2f getVector2fMap()
    {
      return Eigen::Vector2f(x,y); 
    }

    friend std::ostream& operator << (std::ostream& os, const PointXY& p);
  };
`
But is this logic correct?

**Comment by mvieth** [comment]
A map is preferable because then it is possible to not only read from a point, but also assign to it (and there is no copy). You may have to wrap the x and y fields in a union with a new field `float data[2]` or similar (check how it is done for XYZ points. BTW let's discuss these details in the pull request you opened; if you want feedback on code, you can also push the code

**Comment by ArkaprabhaChakraborty** [comment]
okay I'll push the code.
