### ISSUE TITLE
max_points_per_leaf parameter in gpu-based octree construction 

### ISSUE THREAD

**Issue by Ziyu98** [PointCloudLibrary/pcl#4928]
Does the max_points_per_leaf parameter (below please find the link) in octree_builder.cu have to be a multiple of 32? I would like to make the tree more precise, thus I changed this parameter to 2 (say, max_points_per_leaf=2). However, the resulted octree turns to be incorrect (I have put the codes vector and parent vector below)
https://github.com/PointCloudLibrary/pcl/blob/1f71d6444cf0c40248ce7316bfa9b1518aee35b9/gpu/octree/src/cuda/octree_builder.cu#L105
![image](https://user-images.githubusercontent.com/55168912/131598585-5144cec7-aa0f-41df-b1bf-368ec0b50a40.png)

**Comment by kunaltyagi** [comment]
@haritha-j could you please take a shot at this?

**Comment by alexswerner** [comment]
I tried to investigate why this happens and found that below `max_points_per_leaf = 4`, the octree seems to get corrupted. Suspecting that this is caused by a memory limit, I increased  `int cols = std::max<int>(points_num, transaction_size * 4);` to be twice the size, and that seems to remove the issue.
