### ISSUE TITLE
[compression] Default compression generate negative effect

### ISSUE THREAD

**Issue by whatisor** [PointCloudLibrary/pcl#4966]
**Describe the bug**

**Context**

Using pointcloud compression api to compress pointcloud from realsense

**Expected behavior**

Data size is smaller after compressed

**Current Behavior**

Data size is bigger after compressed

**To Reproduce**
https://github.com/IntelRealSense/librealsense/blob/master/wrappers/pcl/pcl/rs-pcl.cpp
Using realtime data from realsense for this example:
https://pointclouds.org/documentation/tutorials/compression.html#octree-compression

**Screenshots/Code snippets**
`*** POINTCLOUD ENCODING ***
Frame ID: 27
Encoding Frame: Prediction frame
Number of encoded points: 307200
XYZ compression percentage: 435.518311%
XYZ bytes per point: 52.262199 bytes
Color compression percentage: 342.510010%
Color bytes per point: 13.700400 bytes
Size of uncompressed point cloud: 4800.000000 kBytes
Size of compressed point cloud: 19788.781250 kBytes
Total bytes per point: 65.962601 bytes
Total compression percentage: 412.266266%
Compression ratio: 0.242562`

**Your Environment (please complete the following information):**

 - OS: Ubuntu 18.04
 - Compiler:GCC 7.5
 - PCL Version 1.8

**Possible Solution**

**Additional context**

**Comment by whatisor** [comment]
I've checked default specification.
It is not really "Compression". It includes downsampling and upsampling base on configuration:
https://pointclouds.org/documentation/compression__profiles_8h_source.html

So , if data is high accuracy (0.001m), compressor with MED profile will "upsample".
As a result, it makes data size bigger.

**Comment by mvieth** [comment]
I am not sure I understand the problem yet.
With default compression/default specification, you mean `MED_RES_ONLINE_COMPRESSION_WITH_COLOR` that is used in the tutorial? This is just an example, you can/should use another compression profile that fits your needs and your data.
I would also recommend you to try out the most recent PCL release, 1.12.0, because we fixed a bug in a class that is involved in the compression, and as a result, the compression might now work better.

**Comment by whatisor** [comment]
You are correct, new version fixed on Windows.
Thanks
