### ISSUE TITLE
[Feature] The fpfh.hpp after modification and recompiling doesn't take effect

### ISSUE THREAD

**Issue by RanchoLin** [PointCloudLibrary/pcl#5007]
I would like to modify the source code of calculating the FPFH descriptor. But when I modified the functions in [fpfh.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/fpfh.hpp#L238), like `computeFeature()`,  it didn’t change after recompiling. When I modified something in [feature.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/feature.hpp), it took effect. 

I am wondering why their performances are different. Am I modifying the function the wrong way? Is there a correct and convenient method to modify the function like [computeFeature()](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/fpfh.hpp#L238)?

The -DCMAKE_BUILD_TYPE I tried was None or RelWithDebInfo.

Thanks in advance.

**Comment by mvieth** [comment]
You have to recompile and reinstall PCL after the modification, then recompile you own project that uses PCL (not sure if this is what you tried). What the `CMAKE_BUILD_TYPE` is, should not make a difference.
For some functions, it is enough to just change the code in the header files that are used by you own project (without recompiling PCL), because those functions are compiled in your own project, but to be safe you should always recompile PCL like I described above

**Comment by RanchoLin** [comment]
> You have to recompile and reinstall PCL after the modification, then recompile you own project that uses PCL (not sure if this is what you tried). What the `CMAKE_BUILD_TYPE` is, should not make a difference. 

Thanks for your reply. I am sure that both PCL and my project are recompiled after modification. 

    cmake -DCMAKE_BUILD_TYPE=None ..  
    make -j2  
    sudo make install

I added  an `std::cout << "filename" <<std::endl` as a test in  `compute()` in [feature.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/feature.hpp#L194) and `computeFeature()` in [fpfh.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/fpfh.hpp#L238). And these files both updated in the install path `/usr/include/`. 

However, which makes me most confused, when I ran my project to calculate the FPFH descriptor, the modification in  `compute()` in [feature.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/feature.hpp#L194) took effect and `computeFeature()` in [fpfh.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/fpfh.hpp#L238) was seems not changed. 

Besides, the same problems exert in `computeFeature()` in [normal_3d.hpp](https://github.com/PointCloudLibrary/pcl/blob/master/features/include/pcl/features/impl/normal_3d.hpp) and other feature calculation. They are all the virtual functions. 

Is there anything else could go wrong?

**Comment by mvieth** [comment]
Which operating system do you use?
Do you have PCL installed via any other way than the self-compiled version (e.g. via apt)? If yes, remove the other version.
To be sure, you should remove any temporary build files from PCL and from your project, and the installed PCL files, so that you basically build PCL and your own project from scratch and it is not possible that any old files or libraries are still there

**Comment by RanchoLin** [comment]
Thanks for your reply. 
The solution is adding `#define PCL_NO_PRECOMPILE` to `.h` file. Then it works.
