### ISSUE TITLE
is there a win32 release?

### ISSUE THREAD

**Issue by jinneigeyu** [PointCloudLibrary/pcl#5104]

**Comment by kunaltyagi** [comment]
@UnaNancyOwen PTAL

**Comment by UnaNancyOwen** [comment]
For example, OpenCV provide only x64 pre-built libraries.
For example, CMake default generater is x64 for Visual Studio.
For these reasons, I believe that pre-built libraries for x64 alone can cover a lot of demand.

I used to provide that, but I stopped because it was so much work.
If there is a satisfied reason and more demand, I will consider re-start provide it.

However, In most cases, vcpkg will be sufficient. 
And, I has published the [build notes](https://gist.github.com/UnaNancyOwen/59319050d53c137ca8f3#file-pcl1-12-1-md). If you want win32, You can build from source code yourself.
