### ISSUE TITLE
Why does a little difference in a PCL program make a difference?

### ISSUE THREAD

**Issue by 155cannon** [PointCloudLibrary/pcl#5171]
typedef pcl::PointXYZ PointT;
typedef pcl::PointCloud<PointT> PointCloudT;

The first way to write the program:

**some codes (generate the cloud_a) 

pcl::io::savePCDFile("w.pcd", *cloud_a);
PointCloudT::Ptr cloud_b(new PointCloudT);
cloud_b = cloud_a;

some other codes (cloud_b Region Growing Segmentation)**
/////////////////////////////////////////////////////////////////////////////
The second way to write the program:

**some codes (generate the cloud_a)

pcl::io::savePCDFile("w.pcd", *cloud_a);
PointCloudT::Ptr cloud_b(new PointCloudT);
pcl::io::loadPCDFile("w.pcd", *cloud_b);

some other codes (cloud_b Region Growing Segmentation)**

I think the two programs are the same. But the final output of the latter is good. And why?

**Comment by mvieth** [comment]
This is very difficult to answer since you didn't include the code after each snippet (where the region growing segmentation happens), and you didn't say in which way the final output is "good" or "bad".
Notice however, that in the second case, `cloud_b` is a distinct object from `cloud_a` (values are the same though), but in the first case, you only have _one_ object/cloud with two pointers to it. You can verify it by changing something in `cloud_b` and checking the values in `cloud_a`

**Comment by 155cannon** [comment]
pcl::search::Search<pcl::PointXYZ>::Ptr tree(new pcl::search::KdTree<pcl::PointXYZ>);
     pcl::PointCloud <pcl::Normal>::Ptr normals(new pcl::PointCloud <pcl::Normal>);
     pcl::NormalEstimation<pcl::PointXYZ, pcl::Normal> normal_estimator;
     normal_estimator.setSearchMethod(tree);
     normal_estimator.setInputCloud(cloud_b);
     normal_estimator.setKSearch(50);
     normal_estimator.compute(*normals);


     pcl::RegionGrowing<pcl::PointXYZ, pcl::Normal> reg;
     reg.setMinClusterSize(2000);
     reg.setMaxClusterSize(50000);
     reg.setSearchMethod(tree);
     reg.setNumberOfNeighbours(30);
     reg.setInputCloud(cloud_b);
     reg.setInputNormals(normals);
     reg.setSmoothnessThreshold(5.0 / 180.0 * M_PI);
     reg.setCurvatureThreshold(1.0);

     vector <pcl::PointIndices> jclusters;
     reg.extract(jclusters);
     cout << jclusters.size()  << endl;

The result "jclusters.size()" is different.  In the first case, it's 6. In the second case, it's 7.

**Comment by mvieth** [comment]
`savePCDFile` (https://pointclouds.org/documentation/group__io.html#ga5e406a5854fa8ad026cad85158fef266) saves the file in ASCII mode by default (you can choose to save it in binary mode instead). In ASCII mode, you might not get a cloud with the _exact_ same values back (due to rounding errors etc), but in binary mode, you will.
You might have to tune the segmentation parameters if the result is not what you want.
So far, nothing indicates a bug in PCL, so I am inclined to close this issue. For questions, please use stackoverflow or discord.

**Comment by 155cannon** [comment]
I find something:

In the second case
    
    pcl::io::savePCDFile("w.pcd", *cloud_a);
    PointCloudT::Ptr cloud_b(new PointCloudT);
    pcl::io::loadPCDFile("w.pcd", *cloud_b);

run the "memcmp(&(cloud_b->points), &(cloud_a->points), sizeof(cloud_a->points))" and the return is not 0. It should be 0 in truth?

**Comment by 155cannon** [comment]
Thank you! @mvieth
