### ISSUE TITLE
undefined reference to `pcl::ExtractIndices<pcl::PointXYZ>::applyFilterIndices(std::vector<int, std::allocator<int> >&)'

### ISSUE THREAD

**Issue by Tony-TF** [PointCloudLibrary/pcl#5228]
Hello everyone：
              I have a problem, please help me to solve it，Thanks! The problem is that Use pcl::ExtractIndices<PointType> extract_indices; to compile successfully, but the following error occurs when running:
![image](https://user-images.githubusercontent.com/35761167/164357473-966a3cb8-bea6-4800-a519-40be2ab2d8a1.png)

The Code is pcl filter  example
![Screenshot from 2022-04-21 10-04-20](https://user-images.githubusercontent.com/35761167/164357058-945786b8-6312-4f44-804f-32fc22bf5e7c.png)

The CmakeLists.txt is 

![image](https://user-images.githubusercontent.com/35761167/164357180-d1b3639c-c228-465b-9882-bb2742f6c828.png)

The system is Ubuntu 16.04 + PCL 1.9.1 + CLion 2021.3.4 ,CLion Build environment
![image](https://user-images.githubusercontent.com/35761167/164357629-d5ee8824-4ed1-45ea-997d-61e70dfc747b.png)

Thanks!

**Comment by mvieth** [comment]
The problem is this line: `find_package(PCL 1.9 REQUIRED COMPONENTS common io)`. You are using `ExtractIndices` from the filters module, so you also have to specify that there: `find_package(PCL 1.9 REQUIRED COMPONENTS common io filters)`. Alternatively, you can request all available modules: `find_package(PCL 1.9 REQUIRED)`. More on that here: https://pcl.readthedocs.io/projects/tutorials/en/master/using_pcl_pcl_config.html
