### ISSUE TITLE
hi guys is there any ways to make the pcl::MarchingCubesHoppe faster?

### ISSUE THREAD

**Issue by guyuezuntinggithub** [PointCloudLibrary/pcl#5262]
os: windows 10
pcl version:1.12.1
install: build from souce code with vs2017,GPU ON
compiler: vs2017+Qt

the following is my code:
![image](https://user-images.githubusercontent.com/63081832/168526285-bb05edef-0bab-46a0-a3a0-5dddc9971df6.png)
It's so slow that I can't use it in my project.

**Comment by mvieth** [comment]
Might be possible to speed it up using OpenMP, CUDA, or similar. Since this is not a bug, this is not high priority and I don't know when I or someone else will look into it. If you need this in the near future, I would recommend you to look into it yourself. I would also recommend to first check, where the program spends a lot of time (for Linux I would use valgrind's callgrind, there might be something similar for Windows)

**Comment by guyuezuntinggithub** [comment]
> Might be possible to speed it up using OpenMP, CUDA, or similar. Since this is not a bug, this is not high priority and I don't know when I or someone else will look into it. If you need this in the near future, I would recommend you to look into it yourself. I would also recommend to first check, where the program spends a lot of time (for Linux I would use valgrind's callgrind, there might be something similar for Windows)

thank you for your reply!
