### ISSUE TITLE
[Registration] Template alignment from the tutorial performs poorly

### ISSUE THREAD

**Issue by alex-klimov** [PointCloudLibrary/pcl#5329]
I have a task to register known 3D object in a scene (align scale, rotation, translation). Both the object and the scene are colored.

I have followed the tutorial shown here:
https://pcl.readthedocs.io/projects/tutorials/en/master/template_alignment.html

It performs poorly as it is at the moment - the object is placed at random place in a scene after two warnings about failing to find a match after 30K iterations. Reading the code - I don't think the code uses color value and it looks like it cannot match the size.

Is there a documentation on what can/should be tried next? What is the recommended way to use color in the alignment? What algorithm should be used to also get transformation for the object scale?

**Comment by mvieth** [comment]
Since I don't see any indication of a bug, GitHub is not the right place for such questions. For algorithm recommendations etc. you can try [stackoverflow or the discord community chat](https://github.com/PointCloudLibrary/pcl#community). And of course the documentation if you haven't checked that yet:
https://pointclouds.org/documentation/group__recognition.html
https://pointclouds.org/documentation/group__registration.html
