### ISSUE TITLE
[Data loader] Suppress "Failed to find match for field" message

### ISSUE THREAD

**Issue by kosmastsk** [PointCloudLibrary/pcl#5413]
There are some times that we need to convert between pointclouds of different data types and the warning message "Failed to find match for field" appears. Actually it spams continuously on the terminal, even though the user may be aware of it. 

There should be a clear way to suppress this message and allow the developer to hide it, if needed.

**Comment by mvieth** [comment]
@kosmastsk Do you have a suggestion how to achieve this?

**Comment by kosmastsk** [comment]
While searching on how to achieve this, I found this page about PCL console.
[(https://pointclouds.org/documentation/namespacepcl_1_1console.html#a9aaacc5ccdc4afd16cf13ecff7c1b88e)]
So, maybe it just requires to apply the proper verbosity level that you need. I will try it in my code and update this issue.

Apart from that, I have no other suggestion for now .

**Comment by kosmastsk** [comment]
By using the pcl::console::setVerbosityLebel(pcl::console::L_ERROR) all messages apart from errors do not appear. Since "Failed to find match for field" is a warning message,   that seems like a good workaround for now.

**Comment by mvieth** [comment]
Ah yes, that works. I would recommend to set the verbosity level to L_ERROR just before the line where the warnings appear that you want to suppress, and reset it to L_INFO directly afterwards. Otherwise, you might also suppress other warnings unintentionally.
It would be nice to have a way to suppress only certain messages, maybe based on a regex, but I haven't checked yet how that could be implemented

**Comment by crisz94** [comment]
> By using the pcl::console::setVerbosityLebel(pcl::console::L_ERROR) all messages apart from errors do not appear. Since "Failed to find match for field" is a warning message, that seems like a good workaround for now.

FYI, typo appears at 'setVerbosityLebel'. It should be 'setVerbosityLevel'
