### ISSUE TITLE
It reports "segment fault(core dump)", when I use RANSAC module.

### ISSUE THREAD

**Issue by MonsterQhz** [PointCloudLibrary/pcl#5469]
Dear author:
I tried to learn RANSAC algorithm. But it reportd "segment fault(core dump)" on my new computer(computer A). And then I tried this project on another computer(computer B), it worked well. I wonder whether the PCL version leads to the different results?The following is my computer environment, attaching my cpp and CmakeLists file.
Environment:
computer A: Ubuntn 20.04, PCL 1.12.1(or 1.12.0, forget)    ----> fail to run;
computer B: Ubuntn 18.04, PCL 1.7.2          ---->success to run;
Addition:
It can be compiled, but will stop when it runs to line 28. The error statement is “ransac.computeModel();”.
[CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/files/9776966/CMakeLists.txt)
![cpp](https://user-images.githubusercontent.com/53841077/195606906-923acecd-c724-41cb-a999-725e98f4c130.png)
Thanks a lot！

**Comment by mvieth** [comment]
On your computer A, you compile PCL from source, is that correct? Do you use any non-default options or compiler flags?
Can you run your program with valgrind, e.g. like `valgrind ./ransac`?
If you compile PCL yourself and want to use pcl_ros, you typically also have to compile pcl_ros yourself.
And another note: In your CMakeLists.txt, you call `find_package` twice for PCL and twice for catkin. I would strongly recommend to only call it once per package, otherwise it might lead to problems.

**Comment by MonsterQhz** [comment]
Thank you. According to your advice, I try to use valgrind to run the program. Could you help me analyze the result? And I change the CMakeLists.txt. I will try to change older PCL vision.
![valgrind](https://user-images.githubusercontent.com/53841077/195750993-203f2784-b709-4684-9d6c-e29a305d6894.png)
[CMakeLists.txt](https://github.com/PointCloudLibrary/pcl/files/9782048/CMakeLists.txt)

**Comment by mvieth** [comment]
You have to call valgrind with the name of the executable, not with the name of the source code file (not ./ransac.cpp)

**Comment by mvieth** [comment]
@MonsterQhz Have you found a solution? If yes, please describe it here so that other people with the same problem can find it

**Comment by MonsterQhz** [comment]
I reinstall PCL 1.12, and it works. Maybe I broke some files by accident.
