### ISSUE TITLE
[pcl] Mathematical error in GeneralizedIterativeClosestPoint::applyState method

### ISSUE THREAD

**Issue by nemeshnorbert** [PointCloudLibrary/pcl#5488]
**Describe the bug**

[Current implemetation](https://github.com/PointCloudLibrary/pcl/blob/41e83323b6d04f7db711d6f3e94e2ffafa36dc7a/registration/include/pcl/registration/impl/gicp.hpp#L560) uses wrong formula for the composition of two transforms.

**Context**

The method applyState is used internally in the optimization process of GeneralizedIterativeClosestPoint algorithm

**Expected behavior**

Correct matrix multiplication

**Current Behavior**

Incorrect matrix multiplication

**To Reproduce**

The bug is minor since the algorithm still works fine.

**Possible Solution**

For two transforms given by matrices
| R1 | t1 |
|---|---|
| 0 | 1 |

and

| R2 | t2 |
|---|---|
| 0 | 1 |

their composition should be

| R1 * R2 | R1* t2 + t1 |
|---|---|
| 0 | 1 |

The actual code uses

| R1 * R2 | t2 + t1 |
|---|---|
| 0 | 1 |

**Comment by mvieth** [comment]
Hi, thanks for reporting this. I checked and it seems like currently this error does not matter since `applyState` is always called with `t`, the first transformation, set to identity (`base_transformation_` is set to identity [here](https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/impl/gicp.hpp#L425)). Still it would be nice to fix this. Are you interested in creating a pull request for that?

**Comment by nemeshnorbert** [comment]
Here is my pull request
https://github.com/PointCloudLibrary/pcl/pull/5489
