### ISSUE TITLE
How to introduce PCL library into the project of WindowsAppSDK

### ISSUE THREAD

**Issue by munitioner** [PointCloudLibrary/pcl#5599]
How to introduce PCL library into the project of WindowsAppSDK and display 3D point cloud in the window?

**Comment by mvieth** [comment]
Due to limited time, we don't offer that kind of support/answer this kind of questions. Unless you want to report a bug in PCL, for example if PCL couldn't be used together with the Windows App SDK, the GitHub issues are not the right place for this. You can consider asking on [Stackoverflow or the Discord community chat](https://github.com/PointCloudLibrary/pcl#community)
