### ISSUE TITLE
[compile error]  faild to compile cuda and gpu due to c++11 compatibility issue 

### ISSUE THREAD

**Issue by kamel271** [PointCloudLibrary/pcl#5686]
** error**

Please paste the compilation results/errors.

/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&& __f)

**Environment *

 - OS: ubuntu1~22.04
 - Compiler: g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
 - PCL Version 1.13.0
 - PCL Type: Compiled from source

If PCL was compiled from source or failure in compiling PCL itself:
 - GPU, Kinfu, CUDA enabled? Yes 
 - List and Version of dependencies used 
 - Compilation flags are used  -DCMAKE_BUILD_TYPE=Release -DBUILD_GPU=ON -DBUILD_CUDA=ON

**Possible Solution**

including the option to compile  cuda and gpu seperatly with c++11

**Comment by larshg** [comment]
Its a gcc 11.3 error with Cuda. Use another gcc compiler or clang.

Please search for similar errors on the web and you'll notice its not just a PCL error. 

We could detect it and produce a error in cmake.

**Comment by larshg** [comment]
@kamel271 please look through https://github.com/NVlabs/instant-ngp/issues/119 and others. They come with suggestions of what to use.

Maybe you could also try upgrade cuda  - that seems also mentioned. I can't remember what I did, since I primarily use windows.

Closing as it is a bug in GCC / Nvidia. But feel free to continue discussion.
