### ISSUE TITLE
"k" value for computing point cloud normals

### ISSUE THREAD

**Issue by drathin4** [PointCloudLibrary/pcl#5757]
I want to know how to determine the optimal range of `k` in `kNN (k nearest neighbors)` or `r` in `rSearch` for computing point normals. In the following tutorial ( [https://pcl.readthedocs.io/en/latest/normal_estimation.html](url) ), PCL has mentioned about `ScaleFactor` which ideally should be a function of the input point cloud, but they haven't given any method/algorithm to compute it. In most open source examples, I have seen `k=30` or `r=0.03 (cm)` irrespective of the point cloud. In my understanding, the question boils down to: `how many neighbors of a query point are required to construct a surface so that computed point normal is sufficiently accurate?` Any suggestions for that?

Also I found some kNN algorithms in AI/ML where they use `k ~ sqrt(N)`, but that definitely isn't going to work in my case since the points are of the order of `10^6 - 10^9`

**Comment by mvieth** [comment]
@drathin4 I think the section [`Selecting the right scale`](https://pcl.readthedocs.io/en/latest/normal_estimation.html#selecting-the-right-scale) explains this quite well: there is no single right answer to this question, it depends on your application and whether you are interested in the fine details (and some noise is acceptable) or you are interested in the larger details (normals are smoothened, comparable to a gaussian-blurred image).
In my opinion, the radius of the radius search can be more difficult to tune because it depends on the local density of your point cloud, which can vary from region to region, or from sensor to sensor.
