### ISSUE TITLE
[improve] Remove redundant steps in extractEuclideanClusters

### ISSUE THREAD

**Issue by daohu527** [PointCloudLibrary/pcl#5786]
The function of the following 2 lines is to delete duplicate indexes. However, during the process of putting each point into the seed_queue, the processed label has been set, so it is absolutely impossible to have duplicate indexes.

So I think the following 2 lines can be removed, it will speed up the process.

https://github.com/PointCloudLibrary/pcl/blob/3ed96c246e5c873713ec670b895469d09149a552/segmentation/include/pcl/segmentation/impl/extract_clusters.hpp#L109-L111

**Comment by mvieth** [comment]
I agree that line 111 does not seem necessary. However, I would not remove line 110 (sorting): not only is it nice to have the indices sorted in each cluster, it might even make further processing slower if the points are accessed in totally random order (instead of ascending order) because the cache is less effective.
I did a quick test and measured the time: these two lines took roughly 900 microseconds, while the whole extract function took 157429 microseconds. That would mean these two lines account for roughly half of a percent of the runtime of the whole function. I think that is negligible and we should rather check if there are other things in that function we can change to make it faster.

**Comment by daohu527** [comment]
There is no problem with sorting each cluster, but we need to ensure that the code is not redundant. As you said, I suggest deleting line 111 and adding a comment to line 110.

I will also test the sorting time, it seems that the time is a bit fast.

**Comment by mvieth** [comment]
@daohu527 If you want to delete line 111 (`erase ... unique`), feel free to create a pull request. Please also delete line 209 then.

**Comment by daohu527** [comment]
ok, I also found other code also have this error, I will fix it together.  Also I will test the speed.
