### ISSUE TITLE
DefaultConvergenceCriteria::hasConverged() returns true if rotation delta is larger than threshold, as opposed to smaller

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5800]
https://github.com/PointCloudLibrary/pcl/blob/f2492bd65cb1e9c48a60f5e27296e25e1835169a/registration/include/pcl/registration/impl/default_convergence_criteria.hpp#L88

I don't understand entirely the use of the cosine here to encode the rotation delta between consecutive alignment iterations, but it stuck out to me that `hasConverged()` says true if the translation increment is smaller than the translation limit (makes sense), but also wants the rotation increment _larger_ than the rotation cosine limit. Is this correct for all rotation matrices?

I assume the cosine business is basically taking the axis-angle representation of the Rotation matrix and checking what the angle is here. So how to check the cosine of that would depend on the value of the angle, would it not?

**Comment by themightyoarfish** [comment]
What value range does the input angle take here? cosine is decreasing from 0 to pi obviously, but then it increases again.

**Comment by mvieth** [comment]
If the angle of the rotation increment is close to zero, then the cosine of the angle is close to one. The further away from zero the angle is, the smaller the cosine of the angle will be. So if we for example require the cosine to be larger than 0.99, then the angle must be between acos(0.99)=8.11 and -8.11.

There was [a discussion](https://github.com/PointCloudLibrary/pcl/issues/5199) some time ago whether using the cosine is a good idea because the limited floating point precision may not be sufficient in some cases. Feel free to check out the discussion and comment your opinion.
