### ISSUE TITLE
[sample_consensus] should add `isModelValid` check inside `computeModelCoefficients`?

### ISSUE THREAD

**Issue by gscholer** [PointCloudLibrary/pcl#5847]
**Describe the bug**

Consider the following code snippet:

https://github.com/PointCloudLibrary/pcl/blob/dc7aec5d38dc6f2e27d7138c03714dfbcdf28ea6/sample_consensus/include/pcl/sample_consensus/impl/msac.hpp#L82-L102

When `sac_model_` is a `SampleConsensusModelPerpendicularPlane` and `selection` is a valid sampling, but the plane is not a valid model because it does not satisfy the angular constraints, then calling `computeModelCoefficients` at line 82 will return true and calling `getDistancesToModel` will give a empty `distances`. If this occurs at `k = 1.0` then we will reach to line 96, since `distances` is empty, the variable `d_cur_penalty` will be 0, and `d_best_penalty` will be set to 0 at line 102 and we can never get a better model after that.

I encounter above case with actual pointcloud data, and I could think two methods to solve this problem:

1. add a `isModelValid` check inside the method `computeModelCoefficients`, so that it will return false at line 82
2. change line 93 to `if (distances.empty ())`, so that we can always skip if `distances` is empty, and I think it should also update the  `skipped_count` before continue

**Comment by mvieth** [comment]
Hi, thanks for reporting this! I think removing `&& k > 1.0` and initializing `k` to `std::numeric_limits<double>::max()` instead of `1.0` in the beginning, would be a good solution.
I am not really sure about incrementing `skipped_count`. What's your reasoning there?
Also, we should apply the same changes in rmsac.hpp.
Would you be interested in creating a pull request?

**Comment by gscholer** [comment]
> Would you be interested in creating a pull request?

Ok, I will create a PR
