### ISSUE TITLE
[filters] VoxelGridOcclusionEstimation does not work with larger FOVs than 180°

### ISSUE THREAD

**Issue by themightyoarfish** [PointCloudLibrary/pcl#5858]
**Describe the bug**

`VoxelGridOcclusionEstimation` computes ray-box intersections, but does deal correctly with the situation when casting backwards. This is common in rotating LIDARs with 360° FOV.

**Expected behavior**

Voxel intersection test should work correctly with target voxel "behind" the sensor, i.e. where X is negative

**Current Behavior**

The filter does not work correctly on 360° clouds.

**To Reproduce**

tbd

**Screenshots/Code snippets**

In this rendering, the green points represent occluded voxels, white unoccluded.

The input data looks like this:

<img width="1608" alt="Screenshot 2023-10-25 at 16 03 15" src="https://github.com/PointCloudLibrary/pcl/assets/11613312/bfe2c181-5b39-48cb-8f5a-f4a301180755">

With the current filter we can see that basically only voxels in the forward-facing 180° are considered

<img width="1608" alt="Screenshot 2023-10-25 at 16 05 20" src="https://github.com/PointCloudLibrary/pcl/assets/11613312/6635bec6-9c48-475e-8c44-03e5af5598d6">

When adding an `abs()`, the filter behaves more as expected

<img width="1608" alt="Screenshot 2023-10-25 at 16 04 37" src="https://github.com/PointCloudLibrary/pcl/assets/11613312/9dadb740-cc2d-4db0-951c-fb040c64539a">

**Your Environment (please complete the following information):**

 - OS: macos
 - Compiler: apple clang 14
 - PCL Version HEAD

**Possible Solution**

I think this is related to the use of `tmin` in the code, which is a fraction along the ray at which a box intersects. If I apply `abs()` to that, it works, but I'm not yet sure what the actual solution is.

**Comment by themightyoarfish** [comment]
it might be that `abs()` always has to be applied to `tmin` e.g. here: https://github.com/PointCloudLibrary/pcl/blob/be7a26c13c0fb59f1023241b045eb9f7de4f7a95/filters/include/pcl/filters/impl/voxel_grid_occlusion_estimation.hpp#L160

because the `direction` vector may already be negative, and tmin has to be positive, or the `rayBoxIntersection()` just doesnt work correctly when casting backwards. `tmin` is checked for `== -1.0` though in places, so just `abs`-ing is probably incorrect.

**Comment by themightyoarfish** [comment]
Well the direction vector is created from the sensor origin and the center of each voxel, and some more will be behind the sensor and thus have negative X coordinates.

**Comment by mvieth** [comment]
It seems like the problem is not so much the direction of the ray, but rather whether the sensor origin is inside the bounding box of the cloud or not. `rayBoxIntersection` seems to assume that the origin is outside of the bbox, and that the ray enters the box somewhere. So `std::max(tmin, 0)` might be the solution, but I will do some further tests.

**Comment by mvieth** [comment]
@themightyoarfish Can you post a point cloud that I can use for reproducing?

**Comment by themightyoarfish** [comment]
[cloud.pcd.zip](https://github.com/PointCloudLibrary/pcl/files/13186804/cloud.pcd.zip)

I used this one here, with voxel size e.g. 0.1 or 0.2.

**Comment by mvieth** [comment]
@themightyoarfish Thanks for the cloud. So I think `std::max(tmin, 0)` is the solution. `tmin` says at which fraction along the ray direction vector the algorithm has to start checking for occupied voxels. Currently, the algorithm seems to assume that the origin of the ray is outside of the bounding box, meaning that `tmin` would be positive. However, if the ray origin is inside the bounding box, `tmin` is negative, and the algorithm will either start checking "behind" the ray and will thus check voxels that shouldn't be checked, or the algorithm will believe that it is already outside of the bounding box and check no voxels at all. `std::max(tmin, 0)` fixes this by forcing it to start ray tracing at the ray origin instead. `std::abs(tmin)` is not quite correct because the part between 0 (the ray origin) and `std::abs(tmin)` is not checked for occupied voxels (but it should be).
Here is a visualization of your cloud with the tool `pcl_voxel_grid_occlusion_estimation`:
Original:
![original](https://github.com/PointCloudLibrary/pcl/assets/39675748/09f039a4-1ab1-45b5-bb83-fb226714e164)

With `abs(tmin)`:
![abs](https://github.com/PointCloudLibrary/pcl/assets/39675748/39cbf423-d805-4c0b-9e25-5875b993ca9b)

With `max(tmin, 0)`:
![max](https://github.com/PointCloudLibrary/pcl/assets/39675748/7632745d-ebc7-4120-badc-41d61968aa1e)

Note: there was a point (0, 0, 0) in your cloud, which I removed. Otherwise the voxel with the camera would be occupied, and all voxels would be occluded.
Feel free to test `std::max(tmin, 0)` yourself, I will open a pull request with this fix soon.

**Comment by themightyoarfish** [comment]
Might I ask how you ran this tool? When I execute it on macOS, I just get a blank white VTK window.

About the point at the origin, I feel like it is a common representation of LIDAR rays without returns, would it make sense to ignore points at the origin? Otherwise users will always have to remember to manually remove such points, and I don't see how they would ever represent a real structure.

**Comment by mvieth** [comment]
> Might I ask how you ran this tool? When I execute it on macOS, I just get a blank white VTK window.

I had to add `cube->Update ();` and 2x `treeWireframe->Update ();` at the appropriate places. I will push those changes, too

> About the point at the origin, I feel like it is a common representation of LIDAR rays without returns, would it make sense to ignore points at the origin? Otherwise users will always have to remember to manually remove such points, and I don't see how they would ever represent a real structure.

Yes, I see how that would be convenient. I will check how to implement it

**Comment by mvieth** [comment]
@themightyoarfish I created a pull request, feel free to take a look
