### ISSUE TITLE
[custom] Correspondence Estimation using Normals

### ISSUE THREAD

**Issue by drathin4** [PointCloudLibrary/pcl#5874]
I want to use correspondence estimation classes like `CorrespondenceEstimationBackProjection, CorrespondenceEstimationNormalShooting` etc. Is it mandatory that the `InputSource/InputTarget` size be equal to the `InputSourceNormal/InputTargetNormal` size respectively? If different sizes are allowed, is it advisable to use InputSource/InputTarget as `SIFT keypoints` (which are much lesser than the normal size)?

I had posted this on Discord server on Friday itself, but didn't receive any response, hence posting it again in `GitHub Issues`

[https://discord.com/channels/694824801977630762/694824801977630765](url)

**Comment by mvieth** [comment]
> I had posted this on Discord server on Friday itself, but didn't receive any response, hence posting it again in `GitHub Issues`

Nonetheless, I would ask you to not create a GitHub issue with such questions. If you don't receive an answer on Discord, you can try Stackoverflow instead or try to find the answer yourself (by looking into the source code or by experimenting with the class). If I find time in the next few days, I will answer you on Discord. The GitHub issues are intended for bugs and compile errors (things that should be fixed in PCL so that the next user doesn't run into them as well). But please understand that we maintainers can't answer every question about how to use PCL, so we refer to Discord and Stackoverflow where other PCL users are more likely to see and answer them.
