### ISSUE TITLE
[custom] Error occurs after running and standing for a bit : Failed to find match for field 'rgb'. det_final: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = pcl::PointCloud<pcl::PointXYZRGB>; typename boost::detail::sp_member_access<T>::type = pcl::PointCloud<pcl::PointXYZRGB>*]: Assertion `px != 0' failed.

### ISSUE THREAD

**Issue by yamada-shi** [PointCloudLibrary/pcl#5876]
Hey everyone.
This is my first time using this site so I may be asking the wrong questions.

Usage environment
ubuntu 20.04
PCL 1.10 (libpcl-dev installed with apt)
cuda 12.2
gcc 9.4.0
ros noetic

Error contents

Failed to find match for field 'rgb'. det_final: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = pcl::PointCloud<pcl::PointXYZRGB>; typename boost::detail::sp_member_access<T>::type = pcl::PointCloud<pcl::PointXYZRGB>*]: Assertion `px != 0' failed.

I get an error after a while of running the following code with catkin_make.

**Comment by mvieth** [comment]
@yamada-shi  This assertion usually happens if a shared pointer (`pcl::PointCloud<pcl::PointXYZRGB>::Ptr` or `pcl::PointCloud<pcl::PointXYZRGB>::ConstPtr`)  is accessed but it doesn't actually point to any cloud object. Have you tried to find out where in your code this error happens? For example by using a debugger like gdb or valgrind, or by adding prints in your code?

**Comment by yamada-shi** [comment]
Problem solved. Sorry for the delay in replying to your comment.

**Comment by yamada-shi** [comment]
Problem solved. Sorry for the delay in replying to your comment.
