### ISSUE TITLE
SampleConsensusModel computeModel results are different on windows and Linux

### ISSUE THREAD

**Issue by wx79889960** [PointCloudLibrary/pcl#5946]
The fitting ball code based on pcl 1.12.1 was transplanted from Linux to windows. It was found that the fitting results of the same data were different, so the eigen version was unified. Compared with the ball parameters obtained in the first iteration, the ball parameters are still different. Thanks for your reply if there is any possible reason for this difference,
[sphere.pdf](https://github.com/PointCloudLibrary/pcl/files/14136688/sphere.pdf)

**Comment by mvieth** [comment]
I would say the likeliest reason is that the compilers generated different machine code, perhaps because of different compiler flags (e.g. optimization flags, which can influence the accuracy of mathematical operations). The centre of your sphere is far away from the origin (0, 0, 0), which might lead to numerical instability.
Another possible reason could be that you told the model to use a random seed based on the current time, so that each time you run the code, different samples are selected. However, the default is to use a fixed random seed (12345).
You might also want to consider using a newer PCL version. In PCL 1.13.0, the sphere model computation was [changed from single precision to double precision](https://github.com/PointCloudLibrary/pcl/commit/f1a5291d7f9bf10ffed9921ef267a93f871df446). This might improve the results in your case.
In the end, both programs have found models with a similar number of inliers and similar coefficients, in a similar number of trials.

**Comment by wx79889960** [comment]
Thank you for your response!The default seed 12345 was used in both tests in the pdf, and I tried to reproduce computeModelCoefficients using the sampling index and data used in the first iteration

**Comment by wx79889960** [comment]
When I debug the computeModelCoefficients interface, m12 starts to show differences

**Comment by wx79889960** [comment]
You are right, the difference is caused by the optimization flag. I compared the Debug of Windows and the ReleaseWithDebugInfo of Linux, so the difference is caused; Thank you very much, this question can be closed
