### ISSUE TITLE
hv_go.hpp   mets::simulated_annealing<pcl::GlobalHypothesesVerification<pcl::PointXYZ, pcl::PointXYZ>::move_manager>' has no member named 'setApplyAndEvaluate'

### ISSUE THREAD

**Issue by pammacdotnet** [PointCloudLibrary/pcl#605]
[ 55%] Building CXX object recognition/CMakeFiles/pcl_recognition.dir/src/hv/hv_go.cpp.o
In file included from /home/acorbi/pcl/recognition/src/hv/hv_go.cpp:37:0:
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp: In instantiation of 'void pcl::GlobalHypothesesVerification<ModelT, SceneT>::SAOptimize(std::vector<int>&, std::vector<bool>&) [with ModelT = pcl::PointXYZ; SceneT = pcl::PointXYZ]':
/home/acorbi/pcl/recognition/src/hv/hv_go.cpp:42:1:   required from here
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp:451:3: error: 'class mets::simulated_annealing<pcl::GlobalHypothesesVerification<pcl::PointXYZ, pcl::PointXYZ>::move_manager>' has no member named 'setApplyAndEvaluate'
   sa.setApplyAndEvaluate(true);
   ^
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp: In instantiation of 'void pcl::GlobalHypothesesVerification<ModelT, SceneT>::SAOptimize(std::vector<int>&, std::vector<bool>&) [with ModelT = pcl::PointXYZRGB; SceneT = pcl::PointXYZRGB]':
/home/acorbi/pcl/recognition/src/hv/hv_go.cpp:43:1:   required from here
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp:451:3: error: 'class mets::simulated_annealing<pcl::GlobalHypothesesVerification<pcl::PointXYZRGB, pcl::PointXYZRGB>::move_manager>' has no member named 'setApplyAndEvaluate'
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp: In instantiation of 'void pcl::GlobalHypothesesVerification<ModelT, SceneT>::SAOptimize(std::vector<int>&, std::vector<bool>&) [with ModelT = pcl::PointXYZRGBA; SceneT = pcl::PointXYZRGBA]':
/home/acorbi/pcl/recognition/src/hv/hv_go.cpp:44:1:   required from here
/home/acorbi/pcl/recognition/include/pcl/recognition/impl/hv/hv_go.hpp:451:3: error: 'class mets::simulated_annealing<pcl::GlobalHypothesesVerification<pcl::PointXYZRGBA, pcl::PointXYZRGBA>::move_manager>' has no member named 'setApplyAndEvaluate'
make[2]: **\* [recognition/CMakeFiles/pcl_recognition.dir/src/hv/hv_go.cpp.o] Error 1
make[1]: **\* [recognition/CMakeFiles/pcl_recognition.dir/all] Error 2
make: **\* [all] Error 2

**Comment by Wildcarde** [comment]
Quick note, this issue is still alive and well.  I'm attempting to build PCL on CentOS 6 and grabbed the latest version of metslib from source and built it (version 0.5.3) which results in:
`                 from /jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/src/hv/hv_go.cpp:37:
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/filters/include/pcl/filters/voxel_grid.h: In instantiation of ‘pcl::VoxelGrid<pcl::PointXYZRGBA>’:
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/include/pcl/recognition/impl/hv/hv_go.hpp:497:   instantiated from ‘bool pcl::GlobalHypothesesVerification<ModelT, SceneT>::addModel(typename pcl::PointCloud<PointT>::ConstPtr&, typename pcl::PointCloud<PointT>::ConstPtr&, boost::shared_ptr<pcl::GlobalHypothesesVerification<ModelT, SceneT>::RecognitionModel>&) [with ModelT = pcl::PointXYZRGBA, SceneT = pcl::PointXYZRGBA]’
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/src/hv/hv_go.cpp:44:   instantiated from here
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/filters/include/pcl/filters/voxel_grid.h:457: warning: ‘pcl::VoxelGrid<pcl::PointXYZRGBA>::leaf_size_’ contains empty classes which may cause base classes to be placed at different locations in a future version of GCC
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/filters/include/pcl/filters/voxel_grid.h:472: warning: ‘pcl::VoxelGrid<pcl::PointXYZRGBA>::min_b_’ contains empty classes which may cause base classes to be placed at different locations in a future version of GCC
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/filters/include/pcl/filters/voxel_grid.h:472: warning: ‘pcl::VoxelGrid<pcl::PointXYZRGBA>::div_b_’ contains empty classes which may cause base classes to be placed at different locations in a future version of GCC
In file included from /jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/src/hv/hv_go.cpp:37:
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/include/pcl/recognition/impl/hv/hv_go.hpp: In member function ‘void pcl::GlobalHypothesesVerification<ModelT, SceneT>::SAOptimize(std::vector<int, std::allocator<int> >&, std::vector<bool, std::allocator<bool> >&) [with ModelT = pcl::PointXYZRGBA, SceneT = pcl::PointXYZRGBA]’:
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/src/hv/hv_go.cpp:44:   instantiated from here
/jukebox/pkgs/PCL/src/pcl-pcl-1.7.2/recognition/include/pcl/recognition/impl/hv/hv_go.hpp:451: error: ‘class mets::simulated_annealing<pcl::GlobalHypothesesVerification<pcl::PointXYZRGBA, pcl::PointXYZRGBA>::move_manager>’ has no member named ‘setApplyAndEvaluate’
`

The cmake build doesn't note anything about a local version being available to build against just generates an error noting there isn't one available which is what prompted me to install 0.5.3.

**Comment by Today20180409** [comment]
I had the same problem compiling PCL 1.7 on raspberry pi. Especially when I spent 8 hours compiling it to 90%, it made me crazy.
I installed metslib manually，now I will uninstall it, and try again.

**Comment by monajalal** [comment]
@Today20180409 what solved your problem? I installed metslib from scratch and it didn't resolve the problem
