### ISSUE TITLE
c++: fatal error: Killed signal terminated program cc1plus compilation terminated.

### ISSUE THREAD

**Issue by liuhai-source** [PointCloudLibrary/pcl#6075]
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:121: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_cylinder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1136: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 17%] Building CXX object search/CMakeFiles/pcl_search.dir/src/octree.cpp.o
[ 17%] Building CXX object io/CMakeFiles/pcl_io.dir/src/png_io.cpp.o
[ 17%] Building CXX object io/CMakeFiles/pcl_io.dir/src/libpng_wrapper.cpp.o
[ 17%] Linking CXX shared library ../lib/libpcl_search.so
[ 17%] Linking CXX shared library ../lib/libpcl_io.so
[ 17%] Built target pcl_search
[ 17%] Built target pcl_io
make: *** [Makefile:171: all] Error 2

**Comment by mvieth** [comment]
@liuhai-source Which PCL version are you using? With which command did you start the compilation?

**Comment by themightyoarfish** [comment]
It's probably the same as #5787, i also had another colleague on an intel macbook report this again.

**Comment by mvieth** [comment]
@liuhai-source Which Operating System and which compiler are you using?
@themightyoarfish I don't think it is the same because here the crash happens while compiling sac_model_cylinder.cpp (not sac_model_ellipse3d.cpp), and the error message is quite different. My best guess is that here, the crash happens because the memory/RAM runs full (can be solved by using fewer threads for compiling or switching to the newest PCL version)
