### ISSUE TITLE
[CMakeLists] Build will fail due to multiple definition of target "flann"

### ISSUE THREAD

**Issue by jujozi** [PointCloudLibrary/pcl#6101]
CMake Error when using colmap and PCL together in one project

CMakeLists
```
find_package(Eigen3 REQUIRED)
find_package(OpenCV REQUIRED)
find_package(colmap REQUIRED)
find_package(Pangolin CONFIG REQUIRED)
find_package(PCL REQUIRED)
```

Error

```
CMake Error at /usr/local/share/colmap/cmake/FindFLANN.cmake:94 (add_library):
  add_library cannot create imported target "flann" because another target
  with the same name already exists.
Call Stack (most recent call first):
  /usr/local/share/pcl-1.14/PCLConfig.cmake:253 (find_package)
  /usr/local/share/pcl-1.14/PCLConfig.cmake:298 (find_flann)
  /usr/local/share/pcl-1.14/PCLConfig.cmake:559 (find_external_library)
  CMakeLists.txt:23 (find_package)
```

Hot Fix
Make sure to import PCL before colmap. 
```
find_package(PCL REQUIRED)
find_package(Eigen3 REQUIRED)
find_package(OpenCV REQUIRED)
find_package(colmap REQUIRED)
find_package(Pangolin CONFIG REQUIRED)

```

Modify CMakeLists to check for existing targets named flann

**Comment by mvieth** [comment]
@jujozi The `add_library` call that causes the problem is in colmap: https://github.com/colmap/colmap/blob/main/cmake/FindFLANN.cmake#L93 They should add a check whether the CMake target `flann` already exists. PCL has a similar check: https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindFLANN.cmake#L39

I am just wondering why the `find_package(FLANN)` call from PCLConfig.cmake jumps to the FindFLANN.cmake from colmap instead of the FindFLANN.cmake from PCL.

**Comment by mvieth** [comment]
Oh, and why do they store the original `CMAKE_MODULE_PATH` but do not restore it later? https://github.com/colmap/colmap/blob/main/cmake/colmap-config.cmake.in#L63

**Comment by mvieth** [comment]
I fixed the problem that `CMAKE_MODULE_PATH` was not restored to the original value in colmap: https://github.com/colmap/colmap/pull/2699 That should now allow to find_package colmap before find_package PCL.
You can also reset `CMAKE_MODULE_PATH` yourself between `find_package` calls: `set(CMAKE_MODULE_PATH "")`
