### ISSUE TITLE
BUG: Signed to Unsigned casting. I cannot build PCL in Windows

### ISSUE THREAD

**Issue by tricostume** [PointCloudLibrary/pcl#6110]
Hi I cannot build PCL in windows (nor Debug or Release)
The problem I get seems to come from this line.

pcl\segmentation\include\pcl/segmentation/extract_labeled_clusters.h(190): error C2397: conversion from 'int' to 'unsigned int' requires a narrowing conversion

I guess this implicit casting from int to unsigned int is dangerous, you intend there to have the maximum number of a signed type copied into an unsigned one (overflow somehow?) and still expect to have a max_label_ ... 

https://github.com/PointCloudLibrary/pcl/blob/e2c94fb642bdaead3f5bee727cf603fedee5c6a2/segmentation/include/pcl/segmentation/extract_labeled_clusters.h#L190

I created a PR: Could we push ASAP?
https://github.com/PointCloudLibrary/pcl/pull/6111

**Comment by mvieth** [comment]
Thanks for reporting. In this case, casting `std::numeric_limits<int>::max()` to an unsigned int is actually not a problem because the largest number representable by an unsigned int is (roughly) twice as big as `std::numeric_limits<int>::max()`. A problem could only arise when casting a negative int to an unsigned int.
Anyway, the `max_label_` member is actually not used any more (compare https://github.com/PointCloudLibrary/pcl/commit/06a07484f49caa4dea13815f683825633e70b87c and https://github.com/PointCloudLibrary/pcl/commit/b4c975871267edb4827bd27fbf9a0a59a69d40ae ). So initializing it with a different value is fine, but even better would be to also mark it as deprecated (see https://github.com/PointCloudLibrary/pcl/blob/master/visualization/include/pcl/visualization/pcl_visualizer.h#L1964 ). If you could as do that, that would be great.

**Comment by tricostume** [comment]
ok so should I set it as deprecated from 1.14.2 on?

**Comment by mvieth** [comment]
> ok so should I set it as deprecated from 1.14.2 on?

No, 1.18.0 please: `PCL_DEPRECATED(1, 18, "this member variable is unused")`

**Comment by tricostume** [comment]
Done: See PR.. do you merge it after checks are passing yourself?

**Comment by tricostume** [comment]
hey I guess the checks are ready... do they look OK?
