### ISSUE TITLE
pcl version 1.12 and 1.10 library conflicts

### ISSUE THREAD

**Issue by bulingbu0** [PointCloudLibrary/pcl#6137]
In Linux, I used sudo apt install libpcl-dev to install, but the following problems occurred when I catkin_make. I hope it can be solved. Thank you.

CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a configuration file for package "PCL" that is compatible
  with requested version "1.12".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.10.0
    /lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake, version: 1.10.0

**Comment by mvieth** [comment]
From apt you got PCL 1.10.0. In the CMakeLists.txt, there is a line like `find_package(PCL 1.12)`, which means that the package needs PCL in the version 1.12 or higher (so for example PCL 1.12.0, PCL 1.12.1, PCL 1.13.0, PCL 1.13.1, ...). In the error message, CMake informs you that it has found the PCL 1.10.0 installation, but will not use it because it does not match the requested version. So you have to install a newer PCL version, for example by building from source. Here are some hints how to do that: https://pcl.readthedocs.io/projects/tutorials/en/master/compiling_pcl_posix.html#compiling-pcl-posix

**Comment by mvieth** [comment]
@bulingbu0 Did my last comment help? If I don't receive an answer, I will close this issue soon.

**Comment by bulingbu0** [comment]
> @bulingbu0我上次的评论有帮助吗？如果没有收到回答，我会很快结束这个问题。

Yes, it helped me, thank you
