### ISSUE TITLE
Spelling error in pcl::NormalDistributionsTransform API

### ISSUE THREAD

**Issue by thallerod** [PointCloudLibrary/pcl#6139]
Oulier -> Outlier

https://github.com/PointCloudLibrary/pcl/blob/d1c34a873bf98be2b747fa511fd2d07285e4ca5f/registration/include/pcl/registration/ndt.h#L178
https://github.com/PointCloudLibrary/pcl/blob/d1c34a873bf98be2b747fa511fd2d07285e4ca5f/registration/include/pcl/registration/ndt.h#L187

**Comment by mvieth** [comment]
Thanks for reporting. Unfortunately, we can't just rename the functions, or else everyone who uses the misspelled names gets compile errors. What we can do is create a copy of each function (but with the corrected name) and deprecate the misspelled functions. Something similar was done here: https://github.com/PointCloudLibrary/pcl/commit/ca1ba30deb9c7125a7ff88592990b7a178c8865e
If you like, feel free to open a pull request (the version number in the `PCL_DEPRECATED` macro has to be 18 instead of 16 now).
