### ISSUE TITLE
[filters] ConditionalRemoval - FieldComparison does not work

### ISSUE THREAD

**Issue by alexeygritsenko** [PointCloudLibrary/pcl#6183]
Hi, if I count the number of points that I want to delete manually, then there are such points. But when I use the `FieldComparison`, it seems that it does not find anything. Example code:
```
void CountPointsLess20(const pcl::PointCloud<pcl::PointXYZRGB>::Ptr& cloud, pcl::PointCloud<pcl::PointXYZRGB>::Ptr& cloud_filtered) 
{
    long match = 0;
    for (size_t i = 0; i < cloud->points.size(); i++)
    {
        if (cloud->points[i].x < 20.0)
        {
            match++;
        }
    }

    std::cout << "match = " << match << '\n';
}

void DelPointsLess20(const pcl::PointCloud<pcl::PointXYZRGB>::Ptr& cloud, pcl::PointCloud<pcl::PointXYZRGB>::Ptr& cloud_filtered)
{
    // build the condition
    pcl::ConditionAnd<pcl::PointXYZRGB>::Ptr range_cond(new
        pcl::ConditionAnd<pcl::PointXYZRGB>());

    range_cond->addComparison(pcl::FieldComparison<pcl::PointXYZRGB>::ConstPtr(new
        pcl::FieldComparison<pcl::PointXYZRGB>("x", pcl::ComparisonOps::LT, 20.0)));

    // build the filter
    pcl::ConditionalRemoval<pcl::PointXYZRGB> condrem;
    condrem.setCondition(range_cond);
    condrem.setInputCloud(cloud);
    condrem.setKeepOrganized(true);
    // apply filter
    condrem.filter(*cloud_filtered);
}

//call in main() 
    CountPointsLess20(cloud, cloud_filtered);
    DelPointsLess20(cloud, cloud_filtered);
    std::cout << "Diff = " << ((cloud->width * cloud->height) - (cloud_filtered->width * cloud_filtered->height)) << std::endl;
```
 Output:
 ```
match = 214278
Diff = 0
```

**Your Environment (please complete the following information):**

 - OS: Windows 10 Pro x64
 - Compiler: Visual Studio 2022
 - PCL version: 1.14.1
 - vcpkg version: 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321

**Comment by larshg** [comment]
Since you ask the ConditionalRemoval to keep your pointcloud organized, it has to set the "points" as matches to some value - and default is quite_nan.

Hence the width and height is the same.

If you want to crop the pointcloud you could use [Cropbox](https://pointclouds.org/documentation/classpcl_1_1_crop_box.html) or perhaps [passthrough](https://pointclouds.org/documentation/classpcl_1_1_pass_through.html).

The fastest filter in this case, is however probably [FunctorFilter](https://pointclouds.org/documentation/classpcl_1_1experimental_1_1advanced_1_1_functor_filter.html) however its still experimental, but works quite nice.

**Comment by larshg** [comment]
Some more elaborate tutorials are available [here](https://pcl.readthedocs.io/projects/tutorials/en/latest/#filtering)

**Comment by alexeygritsenko** [comment]
Thanks, I got it. Yes, `FunctorFilter` looks good, it's flexible enough to build complex conditions, which reminds me of `LINQ`. It's great that you implemented.
