### ISSUE TITLE
[registration] print mse error

### ISSUE THREAD

**Issue by YeHuanjie** [PointCloudLibrary/pcl#6190]
MSE result error when implementing ICP:

> Applying a correspondence rejector method: CorrespondenceRejectorSurfaceNormal.
> [pcl::DefaultConvergenceCriteria::hasConverged] Iteration 1 out of 100.
> [pcl::DefaultConvergenceCriteria::hasConverged] Current transformation gave 0.998857 rotation (cosine) and 0.000576 translation.
> [pcl::DefaultConvergenceCriteria::hasConverged] Previous / Current MSE for correspondences distances is: 179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368.000000 / 0.000001.
> Applying a correspondence rejector method: CorrespondenceRejectorSurfaceNormal.

**Comment by mvieth** [comment]
Hi, this is not really a bug or an error, it just does not look so nice when printed. The previous MSE is initially set to a very large value (see https://github.com/PointCloudLibrary/pcl/blob/master/registration/include/pcl/registration/default_convergence_criteria.h#L283 ) so that the registration does not stop after the first iteration. If you have an idea how to make this look better, feel free to make a suggestion.

**Comment by YeHuanjie** [comment]
will it be better to print "INIT"/"NAN"/"INF" instead std::numeric_limits<double>::max() value?

**Comment by mvieth** [comment]
> will it be better to print "INIT"/"NAN"/"INF" instead of value of std::numeric_limits::max()?

Yes, that would be an option. Or just print the current MSE in iteration 1 (but not the previous MSE). Feel free to create a pull request.
