### ISSUE TITLE
Tracking with normals

### ISSUE THREAD

**Issue by jpmerc** [PointCloudLibrary/pcl#727]
For the particle filters, if we want to use normals for the coherence (NormalCoherencepcl::PointXYZRGBNormal) and setUseNormal(true), it outputs 3 main errors : 

[pcl::ApproxNearestPairPointCloudCoherence::initCompute] PointCloudCoherence::Init failed.

[pcl::ApproxNearestPairPointCloudCoherence::compute] target_input_ is empty!

[pcl::KLDAdaptiveParticleFilterOMPTracker::computeTransformedPointCloudWithoutNormal] use_normal_ == true is not supported in this Point Type

I do not get any errors while setting setUseNormal to false. Every points are of the type pcl::PointXYZRGBNormal.

Thanks.

**Comment by zengzhen** [comment]
Hi, I also think tracking with normals would be very valuable. I'm using PCL 1.7.2(built from source). When I use KLDAdaptiveParticleFilterOMPTracker to track with normals, the warning (which leads to various errors as mentioned by jpmerc) said
```
[pcl::KLDAdaptiveParticleFilterOMPTracker::computeTransformedPointCloudWithoutNormal] 
use_normal_ == true is not supported in this Point Type
```
as I traced down the PCL source code to see what really happened, it occurred to me that when this function
```cpp
//in pcl/tracking/impl/kld_adaptive_particle_filter_omp.hpp
pcl::tracking::KLDAdaptiveParticleFilterOMPTracker<PointInT, StateT>::weight ()
```
is called internally by the tracker, and since `_use_normal=true`, it uses function
```cpp
//in pcl/tracking/impl/particle_filter.hpp
template <typename PointInT, typename StateT> void
pcl::tracking::ParticleFilterTracker<PointInT, StateT>::computeTransformedPointCloudWithNormal (
#ifdef PCL_TRACKING_NORMAL_SUPPORTED
    const StateT& hypothesis, std::vector<int>& indices, PointCloudIn &cloud)
#else
    const StateT&, std::vector<int>&, PointCloudIn &)
#endif
{
#ifdef PCL_TRACKING_NORMAL_SUPPORTED
  // transform cloud based on hypothesis
  // store indices of points that are not occluded
  }
#else
  PCL_WARN ("[pcl::%s::computeTransformedPointCloudWithoutNormal] use_normal_ == true is not supported in this Point Type.",
            getClassName ().c_str ());
#endif
}
```
As you can see, the reason that why we are receiving the warning is because somehow **PCL_TRACKING_NORMAL_SUPPORTED** is not defined, and the only place it has been defined is in pcl/tracking/src/particle_filter.cpp
```
#define PCL_TRACKING_NORMAL_SUPPORTED
PCL_INSTANTIATE_PRODUCT(ParticleFilterTracker, ((pcl::PointNormal) (pcl::PointXYZINormal) (pcl::PointXYZRGBNormal))(PCL_STATE_POINT_TYPES))
PCL_INSTANTIATE_PRODUCT(ParticleFilterOMPTracker, ((pcl::PointNormal) (pcl::PointXYZINormal) (pcl::PointXYZRGBNormal))(PCL_STATE_POINT_TYPES))
#undef PCL_TRACKING_NORMAL_SUPPORTED
PCL_INSTANTIATE_PRODUCT(ParticleFilterTracker, ((pcl::PointXYZ) (pcl::PointXYZI) (pcl::PointXYZRGBA) (pcl::PointXYZRGB) (pcl::InterestPoint) (pcl::PointWithRange) (pcl::PointWithViewpoint) (pcl::PointWithScale))(PCL_STATE_POINT_TYPES))
PCL_INSTANTIATE_PRODUCT(ParticleFilterOMPTracker, ((pcl::PointXYZ) (pcl::PointXYZI) (pcl::PointXYZRGBA) (pcl::PointXYZRGB) (pcl::InterestPoint) (pcl::PointWithRange) (pcl::PointWithViewpoint) (pcl::PointWithScale))(PCL_STATE_POINT_TYPES))
```
and similarly in pcl/tracking/src/kld_adaptive_particle_filter.cpp. 

It seems that when pcl instantiate the trackers that take in information of normals, they are meant to be compiled with the **PCL_TRACKING_NORMAL_SUPPORTED** being defined, and we would not encounter the warnings and errors that we see, somehow that definition does not get through.

I'm not sure what happened during PCL_INSTANTIATE_PRODUCT and why the definition did not get through. 

Can anyone help? Is it possible to get this issue fixed anytime soon? I really need this to be working.

Thanks a lot!

**Comment by ghanimmukhtar** [comment]
Same problem here, with pcl-1.7, any help is highly appreciated.

**Comment by SergioRAgostinho** [comment]
- First comment: pcl 1.7 was released in 2013. We already have 1.8.1 which includes  number of fixes and new features. Why are you making your life harder? :sweat_smile: 
- To work around the issue do the following (making sure the defines come before the header inclusion)
```cpp
#define PCL_NO_PRECOMPILE
#define PCL_TRACKING_NORMAL_SUPPORTED
#include <pcl/tracking/particle_filter.h> // and whatever else you need

[rest of your code here] 

```
This should work for the current version. I can't ensure the same for the one you're working with, but you can always try.

**Comment by ghanimmukhtar** [comment]
Thanks a lot, yes this works :)

**Comment by taketwo** [comment]
You are instantiating tracker with a point type that does not have a normal field (`PointXYZRGBA`), hence the error. If you want to use normals, you need a point type with normals, e.g. `PointXYZRGBNormal`.
